### ISSUE TITLE
Asset should support node version, teraslice version and OS restrictions

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1008]
Our `asset.json` should be able to optionally restrict the version of node, teraslice, and os/arch it supports. I imagine this should be similar to how the [package.json](https://docs.npmjs.com/files/package.json#engines) works. The versions restrictions need to handle semver [ranges](https://www.npmjs.com/package/semver#ranges). Teraslice should verify these restrictions every time an asset is deployed, or a job is submitted/started.

This metadata should also exist in the assets elasticsearch index as well since we could use this information to find the "latest" asset and prevent potential avoid attempting to load incompatible assets.

**Comment by jsnoble** [comment]
We have this currently, its used to create names and loading of assets

**Comment by godber** [comment]
> We have this currently, its used to create names and loading of assets

This is technically true but teraslice doesn't use these at asset upload time in any way.  I'm not sure this matters at this point thought.
