### ISSUE TITLE
needs to handle array input

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#1025]
In elasticsearch lucene queries `foo:bar` would both match `{ foo: 'bar' }` and  `{ foo: ['baz', 'bar']}`. We would need xlucene evaluator to behave the same way.

https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html

**Comment by kstaken** [comment]
Has this been resolved?

**Comment by jsnoble** [comment]
This has not been addressed yet
