### ISSUE TITLE
tjm stop/ restart errors if status is already stopped

### ISSUE THREAD

**Issue by ciorg** [terascope/teraslice#1027]
commands stop or restart throw an error if the job status is already stopped.

error example:
```
Unable to set execution 6ae2830f-5043-4f45-93e3-49467bae5f9e 
status code to stopping, caused by Error: Cannot update terminal job status of "stopped" to "stopping"
```

Tjm should handle the error returned from teraslice and notify the user that the job is already stopped or in the case of restart continue with the restart.

**Comment by jsnoble** [comment]
this has been fixed
