### ISSUE TITLE
Concretely associate git commit with nightly build of Teraslice

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1038]
We've had some trouble properly tracking what is being tested in the daily builds.

Perhaps we should use the short commit hash:

```
git rev-parse --short HEAD
3495d5c3
```

* write it into the image: `git rev-parse --short HEAD > .gitCommit`
* add to tag `terascope/teraslice:daily-03.09.19-3495d5c3`

Thoughts?

At least one of the two would be sufficient.

**Comment by godber** [comment]
Also, I have a slight preference for ISO 8601 datestamps since they are more easily sortable.

```
date -I
2019-03-11
```

`date "+%Y-%m-%d"` on OS X.

**Comment by kstaken** [comment]
How helpful is knowing the latest commit if there are many commits in a nightly? 

The bigger issue to me seems to be that the nightly build is being created at the wrong time. Shouldn't it be done at 3AM not 3PM?

**Comment by godber** [comment]
You know it's the head of the master branch, so it helps constrain the problem.

I agree the timing is bad, but I don't think that argues against knowing what we're testing.

**Comment by godber** [comment]
I don't think time is configurable:

https://github.com/travis-ci/travis-ci/issues/8705

It seems to be implied by the time the cronjob was started.

**Comment by peterdemartini** [comment]
I think knowing the commit hash is good information especially when figuring out whether a commit was included in the nightly build or not.

**Comment by peterdemartini** [comment]
I think using the format `terascope/teraslice:daily-2019.03.11-3495d5c3` should work well enough. It would be nice to set it run at midnight and I think calling it daily is odd more accurate. Regardless I think changing the tag to represent exactly what you are using is more important.
