### ISSUE TITLE
Improve Teraslice Job Targets to support k8s tolerances and preferences

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1055]
We have internal use cases that will require the use of k8s tolerances, others are likely to encounter the same sort of needs.  We'll add support for preferences too.

**Comment by godber** [comment]
Here's the details on the proposed solution that I've discussed with several of you ... if people have opinions about names of properties or values, let me know, I've taken a stab at them.


## Node Affinity and Tolerance Using Teraslice Job Targets

If you need the workers (and execution controller) of your job to execute on
specific set of nodes or tolerate node taints, you can use the Teraslice
`targets` property on your job.  The simplest form of using `targets` is to
specify a single target and by default Teraslice will configure your workers to
only run on nodes who's labels match the `key` and `value` specified as shown
below:

```
"targets": [
    {"key": "zone", "value": "west"}
],
```

More advanced options are also available to control how your Teraslice workers
are scheduled in your Kubernetes cluster.  These options can be used by
specifying an optional `constraint` property on the `targets` specified on your
Teraslice job.  The available `constraint`s are:

* `required` - Pods will only be scheduled to nodes that match the label.  If
there are insufficient resources on the target nodes your job may have fewer
workers than requested.  This is the **default** if is `constraint` is omitted.
* `preferred` - Pods will be scheduled to nodes with this label, but if there
are insufficient resources, they may be scheduled on nodes without this label.
* `accepted` - Pods may be scheduled to nodes with the kubernetes taint
provided by this label.  This uses a Kubernetes tolerance.

### Examples

If you want to force pods to run on nodes with a given label, you can simply
specify a target with just a `key` and `value`:

```
"targets": [
    {"key": "zone", "value": "west"}
],
```

Using the `"constraint": "required"` property, as shown below, achieves the same
thing:

```
"targets": [
    {"key": "zone", "value": "west", "constraint": "required"}
],
```

Using `"constraint": "preferred"` establishes a looser constraint on the label:

```
"targets": [
    {"key": "zone", "value": "west", "constraint": "preferred"}
],
```

If you wanted your Teraslice workers to target a set of nodes with a given label
but also wanted to guarantee the availability of these nodes for this workload
by applying a taint, you could use `required` to target the label, then use
`accepted` to tolerate that taint as follows:

```
"targets": [
    {"key": "zone", "value": "west", "constraint": "required"}
    {"key": "gen4", "value": "NoSchedule", "constraint": "accepted"}
],
```

**Comment by godber** [comment]
Relevant k8s docs:

* [Node Affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)
* [Taints and Tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)

Note that `preferred` has a required argument of `weight`.  So far our usage of this has always set the value to `1`.  So I am going to hard code that value into Teraslice currently.  In the future when some real need drives us to support variable weights we can choose between packing it into the constraint like this `"constraint": "preferred:80"` or adding a property to the target that is only used by `preferred` like this `"constraint": "preferred", "weight": 80`.  Right now I don't think it's worth thinking about and we don't have internal use cases driving the need or helping the decision making.  I'll call this out in the code.

Reviewing the docs also brought to my attention that some day we may want **pod affinity** support.  Obviously I don't care now, but it will probably not be part of `target`.  I figure `target` targets resources ... while something else ... like `workload` enforces constraints between jobs/workloads.  Though maybe not.

**Comment by kstaken** [comment]
Was this completed in 0.5.1?

**Comment by godber** [comment]
`v0.51.0` yeah
