### ISSUE TITLE
assets init should create a new style processor stub

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1062]
When you run `teraslice-cli assets init` it asks you if you want to create a processor. It then proceeds to setup an old style processor with an empty index.js. Instead it should create a new style processor with stubbed out code in each of the files. 

The code should probably be based on the batch processor by default and it should be possible to build and run the asset with no further changes by the end user. It won't do anything useful but the user shouldn't have to do any additional work to see it function. Maybe it should just log a simple message. 

The other sections in the code should have short comments that help guide the user in figuring out what each section is for.

**Comment by kstaken** [comment]
This should also include a passing test suite out of the box.

**Comment by godber** [comment]
New Style Processor ✅ 

```
cat asset/example/processor.js
'use strict';

const { BatchProcessor } = require('@terascope/job-components');

class Example extends BatchProcessor {
    onBatch(dataArray) {
        // example code, processor code goes here
        dataArray.forEach((doc) => {
            doc.type = this.opConfig.type;
        });
        return dataArray;
    }
}

module.exports = Example;
```

Passing test suite ✅ 

```
yarn test
yarn run v1.12.3
warning package.json: No license field
$ jest
jest-haste-map: Haste module naming collision: foobha
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/asset/package.json
    * <rootDir>/package.json

 PASS  test/example-spec.js
  example should
    ✓ generate an empty result if no input data (7ms)
    ✓ add type to all the docs (3ms)


=============================== Coverage summary ===============================
Statements   : 100% ( 5/5 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 2/2 )
Lines        : 100% ( 5/5 )
================================================================================
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.038s
Ran all test suites.
✨  Done in 3.31s.
```

**Comment by kstaken** [comment]
This looks good.
