### ISSUE TITLE
Teraslice cli command name change

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1085]
@peterdemartini and I have talked a few times about changing how the cli works and this ties in a bit usability and the `teraslice` command.  The suggestion is that we rename the existing `teraslice-cli` command to be just `teraslice` and move the server start functionality to something like `teraslice server` or `teraslice server start`.

I think the broader question is: is there some inherent reason that there should be two separate commands or is it an artifact of how we organically developed these things?

@kstaken do you have thoughts along these lines?

**Comment by kstaken** [comment]
Hmm, we've already talked about having a command to bootstrap a cluster in K8s so maybe it would make sense to generalize that and have the same thing to bootstrap / control local installs or a docker install. 

Not sure on taking over the name though. This should not be the only way to run locally but maybe we could use `teraslice-server` for the server instead. Worth considering.

**Comment by godber** [comment]
Looking at what the commands would look like, if we unified them:

```
teraslice <command>

Commands:
  teraslice aliases <command>         commands to add and remove cluster aliases
  teraslice assets <command>          commands to manage assets
  teraslice jobs <command>            commands to manage jobs
  teraslice ex <command>              commands to manage execution ids
  teraslice nodes <command>           commands to list nodes
  teraslice workers <command>         commands to manage worker
  teraslice controllers <command>     commands to manage controller
  teraslice tjm <command> <job-file>  commands to manage jobs through job files
  teraslice server <command>          commands to create local teraslice server
  teraslice cluster <command>         commands to create remote teraslice cluster

Options:
  --version   Show version number                                      [boolean]
  --help, -h  Show help                                                [boolean]
```

There is a difference in that all of the commands from `teraslice-cli` are intended to operate on existing clusters.  Whereas the notional `server` and `cluster` commands shown above create or destroy clusters.

I know @peterdemartini and I had some ideas other than `teraslice server` ... I'm not recalling them ATM.

**Comment by kstaken** [comment]
Not sure there needs to be a difference between deploying / managing a local single node "cluster" vs a multi-node cluster. They're largely the same thing and hopefully the differences can be hidden in the implementation.

**Comment by kstaken** [comment]
Is this something that's still useful?

**Comment by godber** [comment]
I'll say no and err on the side of closing.  We can always re-open.
