### ISSUE TITLE
Proposal for Data Type Config

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1092]
We've add the concept of data types to `data-access` but currently our implementation uses the `TypeConfig` from xlucene. We have a lot of code that would benefit from this abstraction, especially some of model configuration in data-access. I have come up with a proposal that I think would work well given the requirements.

### Requirements

The types configuration should be fairly flexible but also simple enough none-technical users read and use. This configuration should be able to transpile to at least the following configuration formats (although full-compatibility is not-likely). 

- `Elasticsearch Index Mapping` (including some of the analyzers)
- `GraphQL Schema`
- `JSON Schema`

This configuration should be able to be used as replacement for the xlucene's `TypeConfig` and it should be used in the context of input validation.

### Proposal

```ts
interface DataTypeConfig {
    /**
     * Field (use dot notation for nested)
    */
    [field: string]: FieldTypeConfig;
}

interface FieldTypeConfig {
    /**
     * The datatype of field
    */
    type: FieldType;

    /**
     * Default value for field
     *
     * if data-type is 'date-time' this value can a fixed time or datemath
     */
    default_value?: any;

    /**
     * Make the field an array of this specific data type.
     * This makes compatibility easier in elasticsearch and the
     * type configuration easier to read and use
     *
     * @default false
    */
    is_array: boolean;

    /**
     * Require the field on either update or create
    */
    required_on?: FieldRequiredOn;

    /**
     * A list of normalize methods for field values (pre/post processing)
    */
    normalizer?: FieldNormalizer[];

    /**
     * Full text search filters (lucene supported)
     */
    search_analyzer?: FieldSearchAnalyzer;
}

type FieldType = 'string'|'integer'|'number'|'boolean'|'geo'|'ip'|'date-time'|'object';

type FieldRequiredOn = 'update'|'create'|'both';

/**
 * - 'lowercase' - `input.toLowerCase()`
 * - 'uppercase' - `input.toUpperCase()`
 * - 'trim' - `input.trim()`
 * - 'safe-string' - Convert input to an elasticsearch/url safe string
*/
type FieldNormalizer = 'lowercase'|'uppercase'|'trim'|'safe-string';

/**
 *
 * - 'keyword' - Use search input as a single token.
 * - 'lowercase' - Search case-insensitive
 * - 'standard' - Splits tokens by word, ignores non-word punctuation.
*/
type FieldSearchAnalyzer = 'keyword'|'lowercase'|'standard';
```

**Comment by kstaken** [comment]
There are a number of additional considerations around the typing for elasticsearch mappings as the mappings are more complex. I think this implies the field type list needs to be extensible to accommodate a richer set of types. This will require some discussion so we can look at the categories of mappings and how they often manifest as virtual fields on records.

**Comment by peterdemartini** [comment]
Closing issue in favor of changes in https://github.com/terascope/teraslice/pull/1100
