### ISSUE TITLE
Make jobs prometheus-scrapable

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#1108]
Similar to #861 but for `/cluster/slicers`.  Doing this paves the way for us to wean off our zabbix implementation, which isn't horrible but probably simpler to prometheus+alert-manager all the things.

Another option is for us to write a teraslice exporter so we don't have to muck with core teraslice for something like this.  I don't have a strong opinion so whatever y'all prefer works for me.

**Comment by godber** [comment]
I am beginning an implementation of an external exporter that scrapes `/cluster/controllers` and exposes as a prometheus exporter.

**Comment by godber** [comment]
This was completed by implementing this: https://github.com/terascope/teraslice-exporter
