### ISSUE TITLE
Data with coarse dates can result in slices that are too large

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#111]
If a high volume index has dates that are in increments of minutes or seconds it can lead to a scenario where it's not possible to slice the data down to a reasonable chunk. Even going to the ms or ns level won't matter because all data would be grouped at the second level with no further divisions possible.

**Comment by kstaken** [comment]
For dealing with this we might be able to take the smallest range slice possible then start to subslice using the ES document ID to pull it down further. This won't work in every instance but will anytime ES generates the IDs. So it could be possible to subslice based on the HEX values in the identifier and adding characters until you get deep enough to limit the size. Ugly but probably possible.

**Comment by jsnoble** [comment]
Id's for documents are generated by mixing the timestamp, mac address and a counter together.

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/TimeBasedUUIDGenerator.java

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/UUIDs.java

after reviewing the code, it seems the first 6 bytes of the id are from the timestamp in milliseconds and is base64 encoded to be the first part of the string. 
We considered creating a range of the slice, and then convert from time bytes > hexidecimal (we need 12 here ) > base64 encode. We would generate every permutation within that time range and then use the strings to regex the id's within the given slice range to further subdivide the query up.

we need to consider how restarts act, and how to keep proper logging of the same time range but what id strings were used in the slice etc etc

**Comment by jsnoble** [comment]
This has been fixed with the id_slicing  in elasticsearch_reader
