### ISSUE TITLE
Add option to save node_modules in teraslice-cli assets build

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1112]
I encountered a situation today where I was sad that the local `node_modules` directory gets deleted during asset build.  It would have been super convenient if there was an option that allowed the build to keep this directory.

I think it's important that the default behavior is to remove the directory and build cleanly so users don't accidentally shoot them selves in the foot.  But I think users should be permitted to deliberately shoot themselves in the foot by using something like a `--save-node-modules` option.

See the relevant code here:

https://github.com/terascope/teraslice/blob/0079984aa4df0c2eb4b54ee1dbe23682ea4ea287/packages/teraslice-cli/lib/asset-src.js#L83-L87

**Comment by peterdemartini** [comment]
With yarn you don't need to remove `node_modules`, you can use the flags `--force --check-files` and it will verify / cleanup any packages that have been modified or changed.
