### ISSUE TITLE
Breaking change in Convict v5.0.0

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1114]
`node-convict` released a breaking changed in `v5` that is not compatible with our current use of it. They officially removed support for `allowed: false` which silently ignored properties not specified in the schema. The supported values are `strict` and `warn`, after a quick test I found that breaks any `terafoundation` connector configuration and possibly a ton of other values.

We can stick to `v4` for now but eventually we need to figure out what to do. Regardless of this breaking change, I don't know if `node-convict` is going to be the best solution long term since its support for complex configuration options is limited.

See the [changelog](https://github.com/mozilla/node-convict/blob/master/CHANGELOG.md#500---2019-05-06). It is also important note that using a boolean was previously deprecated.

**Comment by A-312** [comment]
> They officially removed support for allowed: false which silently ignored properties not specified in the schema.

If you don't want warning messages set `allowed` to other value than `warn`:

```js
const blueconfig = require('blueconfig');
let conf = blueconfig({
  ip: {
    doc: 'The IP Address to bind.',
    format: 'ipaddress',
    default: '127.0.0.1',
    env: 'IP_ADDRESS'
  }
}).merge({
  "port": 8080,
}).validate({ allowed: 'silent' });
```

**Comment by jsnoble** [comment]
we have solved this issue and are using a higher convict library verison
