### ISSUE TITLE
Was able to create two spaces with the same name through the API

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1133]
The data-access API allowed me to create two spaces with the same name and same endpoint name. This resulted in one shadowing the other. I think the problem is more with the endpoint name but we should consider if space name should be required to be unique. I'm thinking it probably should.

**Comment by peterdemartini** [comment]
The endpoint should already be unique, I added more tests to confirm it so I am not sure how this happened.

**Comment by kstaken** [comment]
Is this a recent restriction? This was done by a script I ran about a week ago. Didn't notice the duplication until today.

**Comment by peterdemartini** [comment]
It might be about a week old, I remember we talked about it last week and I fixed it soon after.

**Comment by peterdemartini** [comment]
Can we close this?
