### ISSUE TITLE
Migrating to the new Elasticsearch Client

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1211]
There are a few problems that come into play here:

1. The underlying legacy elasticsearch client seems to get in an unrecoverable state if the cluster is partially or unavailable after running under load. (this is difficult to reproduce). This appears to be affecting the teraslice state store the most.
1. We need to switch the newer version of the elasticsearch client to get future bug fixes and features.
1. Our `elasticsearch-api` will need to be rewritten to support the new client.

The first priority is to get the teraslice storage module to use the new elasticsearch client to fix any potential issues in the state store. IMO there are two approaches:

1. Create a one of usage of the new elasticsearch client and delay making similar changes to the `elasticsearch-api`.
    - This has the advantage of getting the fix out the door sooner because the surface area for issues is smaller. BUT this also means that we won't have generic enough solution that will work correctly. 
1. Create a new version of the `elasticsearch-api` that works with the new API and use that within the teraslice storage module.
   - This has the advantage of allowing build a more generic solution, and it will make it easier to start using the client in other places.

There are also other factors that need to be considered:

1. The `elasticsearch-api` library is fragile to changes and even creating a new major version of is potential for problems, and it may be confusing that that v1 and v2 work the old client and v3 uses the new client.
1. We should continue to push towards to using the `elasticsearch-store` vs the `elasticsearch-api` since having two implementations of abstracted API doesn't make sense.
1. Since we need to add a new connector to `terafoundation` we should make it so it returns our abstracted elasticsearch client instead of base one, because in 99% of the cases we wrap the `elasticsearch` client with our wrapped after get it and we often refer them using the same name (client) or (esClient).

I purpose we create a lower level `SimpleClient` class inside of `elasticsearch-store`, create a connector that returns it and uses that `SimpleClient` inside the teraslice storage.

**Comment by kstaken** [comment]
This has been completed.
