### ISSUE TITLE
Query length limitations with many OR clauses

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1227]
This hasn't been confirmed but I've had a report of an issue with xlucene and queries that contain long lists of OR clauses. In this instance the end user is reporting that they had a stored query that ran fine against a v1 API but failed with `query restricted` against a v2 API. It's likely this involved hundreds, maybe thousands of OR clauses. Simply reducing the number of OR clauses was sufficient to work around it but we should better understand the limitations since this a difference with prior behavior.

**Comment by peterdemartini** [comment]
I was able to create a query with thousands of random joined queries and it seemed to still work. [see the gist](https://gist.github.com/peterdemartini/54ce6fd56a322a2b3548a237bbf339b1)

**Comment by peterdemartini** [comment]
@kstaken is it safe to close this?

**Comment by kstaken** [comment]
yes
