### ISSUE TITLE
teraslice-cli improvements

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1238]
After using `teraslice-cli` I have a few improvements or suggestions:

- When running `teraslice-cli controllers list` and there are no controllers to list, I get an error `No controllers on <cluster-alias>` and exit code of `1`. However that is not really an error and I expected to just get an empty list of controllers returned with an exit code of `0`. This applies to `teraslice-cli ex list`, `teraslice-cli ex errors`, `teraslice-cli jobs list`, `teraslice-cli nodes list`, `terasilce-cli workers list`.
- When using `--help` it would be nice to use the [full terminal width](http://yargs.js.org/docs/#api-wrapcolumns) so it looks better on larger screens.
- Some of the tables that get outputted wrap the screen which makes it unreadable, we should either show less info or find a better a way of displaying the table.
- When running any `list` command, I saw there were a few output options (`pretty` and `txt`), which is good but I expected there should be a `json` option as well.

**Comment by kstaken** [comment]
The CLI has evolved.
