### ISSUE TITLE
v2 ui dependency on v1 users index

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1243]
I switched a system to just use v2 users today and then `closed` the old v1 users index in ES. When I closed the index the v2 UI started receiving 500 errors and completely stopped working. Obviously a highly befuddling thing to happen. Reopening the v1 users index stopped the errors and returned the UI to a functioning state. 

Logs weren't particularly helpful but it dumped the entire req object and this stood out.

```
"_passport":{"instance":"[Circular]","session":"[Circular]"}},"res":"[Circular]"
```

**Comment by peterdemartini** [comment]
This issue has migrated to the closed source repo
