### ISSUE TITLE
v1 -> v2 inconsistency in response result count metadata

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1268]
The v2 API is not correctly handling the `returning` count on search results.

In v2 (size=0 on the query):

```
{
  "info": "437503 results found.",
  "total": 437503,
  "returning": 437503,
  "results": []
}
```

in v1

```
{
  "info": "437460 results found. Returning 0.",
  "total": 437460,
  "returning": "0",
  "results": []
}
```

Returning count is wrong and is missing from the info field in the v2 response.

**Comment by peterdemartini** [comment]
Does returning need to be a `string`?

**Comment by kstaken** [comment]
hmm, that is odd. It can be corrected to be a number.
