### ISSUE TITLE
teraslice-cli asset deploy should support specific asset versions

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1305]
There needs to be a way in the `teraslice-cli assets deploy` command to specify a particular version when retrieving a pre-built asset from GitHub.

**Comment by godber** [comment]
Talking with Jared, I think we're adding this as an option like this:

```
earl assets deploy ts-test1 --asset-version v1.5.6 terascope/file-assets
```

We considered adding it as an optional positional at the end, but the asset name `terascope/file-assets` is optional as well and I don't think yargs can disambiguate from those, so option it is.
