### ISSUE TITLE
datatypes  - Elasticsearch Error: [illegal_argument_exception] Limit of total fields [1000] in index has been exceeded

### ISSUE THREAD

**Issue by ciorg** [terascope/teraslice#1307]
getting this error when I try to add additional field types to a datatype. 

`Elasticsearch Error: [illegal_argument_exception] Limit of total fields [1000] in index [x] has been exceeded`

**Comment by peterdemartini** [comment]
How many fields do you have?

**Comment by ciorg** [comment]
9 fields

**Comment by ciorg** [comment]
several of the data types have duplicate fields, I think employing a better overall strategy of inheritance would reduce the number of fields.

**Comment by kstaken** [comment]
Obviously fields should not be duplicated when inheritance is involved. But wanted to note this is an index level setting that can be adjusted if it's ever really needed.

```
PUT my_index/_settings
{
  "index.mapping.total_fields.limit": 2000
}
```

**Comment by peterdemartini** [comment]
I am using a index type: [`object`](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/object.html) for the fields and that auto-indexes those fields, we can also set [`enabled`](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/enabled.html) to `false` which may help this problem? But it would require a reindex...
