### ISSUE TITLE
More analytics for teraslice jobs

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1373]
Currently we only track the analytics for the each operation, but now that we have more [lifecycle events](https://terascope.github.io/teraslice/docs/jobs/slices#worker-lifecycle-events), it would be nice if we had analytics for the those too.

Also tracking purely diffs isn't always useful. For example, you'd never be able tell how much is used, and when the operation actually started, or when there is a gap in processing.

**Comment by kstaken** [comment]
Not relevant anymore.
