### ISSUE TITLE
getClient in job-components should raise error when connector creation fails

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1390]
I had an issue with the `s3_reader` where [this line](https://github.com/terascope/file-assets/blob/53fa7e2951e3fa0d8d4c9590743615060701287d/asset/s3_reader/slicer.js#L39) would throw `TypeError: Cannot read property 'listObjects_Async' of undefined`.  The root cause of this was that the S3 connector wasn't created because of a configuration issue.

`getClient()` should throw an error instead of returning nothing.

The job should end up in `terminated` with an informative error on it.

**Comment by godber** [comment]
You removed the `client:initialization:error` emitter in this PR:

https://github.com/terascope/teraslice/pull/1393/files

Can that handler here be removed as well?

https://github.com/terascope/teraslice/blob/0c948b73f074965364f6927755d9d1843f92bfa2/packages/teraslice/lib/workers/helpers/worker-shutdown.js#L158

If this isn't an issue, go ahead and re-close.

**Comment by peterdemartini** [comment]
Maybe after we go to v1 since it might break anything that is dependent on that feature

**Comment by godber** [comment]
But isn't that just an event handler for an event that will never be emitted again?  If it's not safe to remove the handler, was it safe to remove the emitter?

**Comment by peterdemartini** [comment]
It is still being used in asset bundles with an older version of job-components. If I remove that code in `worker-shutdown`, the scope of this breaking change will expand to existing asset bundles, instead of being opt-in, (except for legacy processors which will now get auto-upgraded to the fail loudly `getClient` since they don't use job-components directly)

**Comment by godber** [comment]
Aha, that's good to know.  Thanks.
