### ISSUE TITLE
xLucene should treat single quotes the same as double quotes

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1423]
xLucene should treat single quotes the same as double quotes. The following query: `location:(geo_point:'32.1235990,23.4565990' geo_distance:'50m')` should work after that change is made.

**Comment by kstaken** [comment]
I am definitely concerned that there's more to it than this. It's strange that neither the lucene[1] nor ES[2] docs list `'` as a special character even though ES definitely allows its usage. 

1. https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
2. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

**Comment by peterdemartini** [comment]
@jsnoble and I found some big differences between single qoutes and double quotes:

### Keyword

**Expected:** 37 result

with double quotes:   (behaves the same without quotes)

```bash
$ curl -sSf 'http://localhost:9200/teracluster__ex/_search?q=_status:"terminated"' | jq '.hits.total'
37
```

with single quotes:
```bash
$ curl -sSf "http://localhost:9200/teracluster__ex/_search?q=_status:'terminated'" | jq '.hits.total'
0
```

### Analyzed Text Field Type  

**Expected:** 601 result

```json
"url": {
    "type": "text",
    "fields": {
        "keyword": {
            "ignore_above": 256,
            "type": "keyword"
        }
    }
}
```

with double quotes: (behaves the same regardless of escaping the `:` in the url)

```bash
$ curl -sSf 'http://localhost:9200/example-logs/_search?q=url:"http\://walton.name"' | jq '.hits.total'
601
```

with single quotes (without escaping the `:` in the url)

```bash
$ curl -sSf "http://localhost:9200/example-logs/_search?q=url:'http://walton.name'" | jq '.hits.total'
curl: (22) The requested URL returned error: 400 Bad Request
```

with no quotes (without escaping the `:` in the url)

```bash
$ curl -sSf "http://localhost:9200/example-logs/_search?q=url:http://walton.name" | jq '.hits.total'
curl: (22) The requested URL returned error: 400 Bad Request
```

with single quotes (with escaping the `:` in the url)

```bash
$ curl -sSf "http://localhost:9200/example-logs/_search?q=url:'http\://walton.name'" | jq '.hits.total'
10379175
```

with no qoutes (with escaping the `:` in the url)

```bash
$ curl -sSf "http://localhost:9200/example-logs/_search?q=url:http\://walton.name" | jq '.hits.total'
10379175
```

When the filed type is `date`:

### Date

**Expected:** 1 result

```bash
$ curl -sSf 'http://localhost:9200/teracluster__ex/_search?q=_created:"2019-01-11T22:16:20.564Z"' | jq '.hits.total'
1
```

with single qoutes (without escaping `:` in the date string)

```bash
$ curl -sSf "http://localhost:9200/teracluster__ex/_search?q=_created:'2019-01-11T22:16:20.564Z'" | jq '.hits.total'
curl: (22) The requested URL returned error: 400 Bad Request
```

without qoutes (without escaping `:` in the date string)

```bash
$ curl -sSf "http://localhost:9200/teracluster__ex/_search?q=_created:2019-01-11T22:16:20.564Z" | jq '.hits.total'
curl: (22) The requested URL returned error: 400 Bad Request
```

with single qoutes (with escaping `:` in the date string)

```bash
$ curl -sSf "http://localhost:9200/teracluster__ex/_search?q=_created:'2019-01-11T22\:16\:20.564Z'" | jq '.hits.total'
0
```

without qoutes (with escaping `:` in the date string)

```bash
$ curl -sSf "http://localhost:9200/teracluster__ex/_search?q=_created:2019-01-11T22\:16\:20.564Z" | jq '.hits.total'
1
```

### IP

**Expected:** 1 result

with double qoutes: (behaves the same without quotes)

```bash
$ curl -sSf "http://localhost:9200/testdata/_search?q=ip:\'139.48.0.169'" | jq '.hits.total'
1
```

with single qoutes:

```bash
$ curl -sSf 'http://localhost:9200/testdata/_search?q=ip:"139.48.0.169"' | jq '.hits.total'
0
```

### Bytes

**Expected:** 1 result

with double qoutes: (behaves the same without quotes)

```bash
$ curl -sSf "http://localhost:9200/testdata/_search?q=bytes:\'5265338'" | jq '.hits.total'
1
```

with single qoutes:

```bash
$ curl -sSf 'http://localhost:9200/testdata/_search?q=bytes:"5265338"' | jq '.hits.total'
0
```

**Comment by peterdemartini** [comment]
We found one scenario where it acts the same and another scenario where it acts more similar:

### Text (with multiple word values)

**Expected:** 2 result

```json
"text" : {
    "type" : "text"
}
```

with double, single, or no quotes, they all work as excepted:

```bash
$ curl -sSf 'http://localhost:9200/string_test/_search?q=keyword:"text%20with%20spaces"' | jq '.hits.total'
2
```

### Keyword (with multiple word values)

**Expected:** 1 result

```json
"keyword" : {
    "type" : "keyword"
}
```

with double qoutes:

```bash
$ curl -sSf 'http://localhost:9200/string_test/_search?q=keyword:"text%20with%20spaces"' | jq '.hits.total'
1
```

with single qoutes (behaves the same as without qoutes)

```bash
$ curl -sSf "http://localhost:9200/string_test/_search?q=keyword:'text%20with%20spaces'" | jq '.hits.total'
2
```

**Comment by peterdemartini** [comment]
Given the goal of xLucene, which aims to be more of a data query language than a full text search query language, it may make more sense to treat double quotes and single quotes the same. This means there would be different behavior than using lucene but it would allow us to embed this inside `json` and `graphql` more easily and it will be more intuitive for users coming from other non-lucene query languages. 

If we make this change, we should document this difference and make the goals of xLucene more clear in the documentation.

@kstaken do you think we should move forward with this change?

**Comment by kstaken** [comment]
Yes given our goals I think this is a reasonable tradeoff.
