### ISSUE TITLE
ts-transforms other_match_required error crashing workers

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1447]
We're seeing cases running in Teraslice where a rule that has `other_match_required` set logs the following error but then causes the worker to crash. The rule set will run successfully otherwise so it appears maybe this only happens when the particular rule triggers.

```
There is only a single extraction for selector SELECTOR and it has other_match_required set to true.
This will return empty results unless the data matches another selector that has reqular extractions

```

**Comment by jsnoble** [comment]
After spending some time digging into this and talking to charlie, I did find a bug in `other_match_required` but nothing that would cause a worker to crash. It would just create bad results. That log is just a warning that would happen every time the process would start up. Charlie mentioned that he updated the asset version that he has been using and the problem went away. He has been successfully using the rules and assets for multiple days now without incident. It could have been a conflict of new rules vs old code as there were major updates to how rules work in the recent versions.
