### ISSUE TITLE
Reconsider slice states for cases where slices are left in started

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1449]
There are cases where a slice can be left in the `started` state.  For instance when a pod is killed for OOM.  There is no mechanism to change the job state, the slice state or any other means of picking up that abandoned slice left in start.  The job will also remain in the `running` state.  If pods are regularly dying you can accumulate a bunch of slices left in the start state like this:

![Screen Shot 2019-09-26 at 12 41 12 PM](https://user-images.githubusercontent.com/1249/65719622-04483e80-e05b-11e9-986d-83f3aa51156a.png)

In the case where a teraslice job is reading from Kafka and experiences this, there will be no data loss, since the offsets are stored in kafka and the worker will come back up and continue.  But if this were an ES job, it's possible the records that were being worked on would be lost.

We should have a way to tell the difference between a slice that have just been created and not assigned to workers, and those that workers have begun working on.  Correct me if this already exists.

**Comment by peterdemartini** [comment]
We should probably attach the `worker_id` to the slice state when marked as running and make the worker_id deterministic (so the worker will restart with the same id).

**Comment by godber** [comment]
Keep in mind workers can be added and removed, so your suggestion would also require changes to accommodate workers that have been removed.
