### ISSUE TITLE
ts-transforms hashing is not comparable to other tools

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1475]
The hashing functions `md5`, `sha1` and `sha2` are not generating hashes that match what other tools are generating. 

With the input `123456789` ts-transforms `md5` outputs `25f9e794323b453885f5181f1b624d0b` 

Using the `md5` command line tool.

```
echo 123456789 | md5
b2cfa4183267af678ea06c7407d4d6d8
```

Working correctly these values should match.

**Comment by peterdemartini** [comment]
I have been screwed by this in past,`echo` adds a newline automatically and that gets included hashed. `echo -n` will give you the expected result: `25f9e794323b453885f5181f1b624d0b`

**Comment by kstaken** [comment]
Yep, I should have caught that.
