### ISSUE TITLE
Add GeoPoint and GeoShape Datatypes

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1524]
We need to add GeoPoint and GeoShape data-types.

refs: #1425

**Comment by godber** [comment]
Jared found this GeoJSON graphql scalar:

https://github.com/enniel/graphql-geojson-scalar-types

It is NOT a single GeoJSON type however.  It appears to implement a single type for every GeoJSON type (e.g. `Point`, `Polygon`, `MultiPolygon`, [ref](https://github.com/enniel/graphql-geojson-scalar-types/blob/master/demo/schema.js)).

**Comment by godber** [comment]
I guess it may still be possible for me to implement a `GeoShapeType` in `data-types`.  I think to do so the `toGraphQL()` method would have to know which GeoJSON type is being represented and then emit the right GraphQL thing (e.g. Point, Polygon, MultiPolygon..).

**Comment by godber** [comment]
Actually, no, I don't think what I suggest above will work since we're only talking about type DEFINITIONS in this case.  In the case of GeoJSON the GeoJSON type comes in with the data record.  So I think we have no choice but to create individual datatypes.  Or maybe I am not understanding something.

**Comment by peterdemartini** [comment]
Since we have additional validation after the graphql schema, the most simple approach would be to use [JSON](https://github.com/taion/graphql-type-json)

**Comment by jsnoble** [comment]
this was done in https://github.com/terascope/teraslice/commit/7a28af058c98cf496993188b28385859d576aa98
