### ISSUE TITLE
K8s jobs should have a labels property that gets copied to k8s resource labels

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1546]
Teraslice job authors should be able to specify a job option called `labels` that is a list of key value pairs that are simply copied to labels on k8s resources (or any other clustering service).

**Comment by godber** [comment]
Note to the person implementing this, if we chose to do so, don't forget to sanitize the values so they are valid for k8s.

**Comment by godber** [comment]
One possible use case for these labels would be to indicate teraslice jobs that have workers that maintain state and hence care needs to be taken when scaling or restarting them.

**Comment by godber** [comment]
Current details on valid k8s labels and values for k8s v1.17:

https://v1-17.docs.kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set


Note: "Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add labels to end-user objects must specify a prefix."

So right now, the other places where we add labels (e.g. `jobId`, `exId`, `jobName`) we are not compliant.  This is something we should fix.

> Labels are key/value pairs. Valid label keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

I won't fix the prefix elsewhere, but when adding these new labels I will include the prefix.  Or, for this use case, actually, perhaps the labels ARE user labels and don't need to be prefixed.

The prefix we would use would probably be `k8s.terascope.io/`

**Comment by godber** [comment]
Actually we should use prefixes as defined here: https://github.com/terascope/teraslice/issues/1583

**Comment by godber** [comment]
@kstaken do you have any concerns with me implementing this feature?  If not, do you have opinions on how you'd like these labels to appear on the jobs?

```json
{
    "labels1": [
        ["labelKey1", "value1"],
        ["labelKey2", "value2"]
    ],

    "labels2": {
        "labelKey1": "value1",
        "labelKey2": "value2"
    }
}
```

**Comment by godber** [comment]
Going with the nested array option.

**Comment by kstaken** [comment]
looks fine to me

**Comment by godber** [comment]
Actually, I am changing this config to match `env_vars`, which is an object, so instead of `label1` up above we will have:

```json
    "labels": {
        "key1": "value1",
        "key2": "value2",
    } 
```

This will catch accidental duplication of keys at job submission time.

We should eventually do the same to `targets`.
