### ISSUE TITLE
Failure to update slice state may cause slice to fail

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1548]
The elasticsearch state cluster was doing a scheduled rolling restart and a job failed because the slice state update failed. The execution controller logs showed the slice failed and the worker logged that it had a `slice ${sliceId} run error` and a `background flush error` BUT no meaning information beyond that was in the logs and no error stack was in the logs The worker didn't appear to crash after this but the execution controller shut down the execution due to the slice failure. 

It  is possible the elasticsearch connection used to do the connection died and for some reason wasn't able to become available again. I think the best thing we can do is improve the logging so we can find out the exact error.

**Comment by kstaken** [comment]
This has not proven to be a significant issue.
