### ISSUE TITLE
teraslice is not shutting down cleanly on ctrl-c

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1625]
When running Teraslice in a terminal locally it's no longer responding correctly when you hit ctrl-c. It simply exits with no appearance of a controlled shutdown.

**Comment by peterdemartini** [comment]
I believe this is a problem with piping to bunyan and it’s unavoidable to my knowledge.

**Comment by jsnoble** [comment]
yes, this is not a bug in teraslice, this is a problem with bunyan. The ctrl-c propgates to bunyan and shuts off the logs. You can see this simply by starting up teraslice without using bunyan. You can see the expected behavior using ctrl-c there

**Comment by kstaken** [comment]
I forgot we had discussed this before. It does shutdown cleanly if bunyan isn't involved.
