### ISSUE TITLE
Stopping a job does not change `_updated` in the job's execution state

### ISSUE THREAD

**Issue by macgyver603** [terascope/teraslice#1660]
I'm fairly certain this is a regression from `v0.61.0`, and I have seen this in both `v0.62.2` and `v0.63.1`. 

I dug around in my Gitlab history and looked at some execution contexts from around the times I updated a test cluster, and it looks like this is a regression between the daily build on 12/20 and the daily build on 12/21.

**Comment by peterdemartini** [comment]
@macgyver603 Do you mean the execution? The job doesn't update when changing the status on the execution.

**Comment by macgyver603** [comment]
This fix is working in `v0.63.2`
