### ISSUE TITLE
Separate and/or deprecate some terafoundation connectors

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#1672]
Currently `terafoundation` package is 80mb including it’s dependencies which is pretty slow to download all of time. The connectors should be separate and in their respective asset bundles (like the kafka connector). I purpose the following changes:

- [ ] Move `hdfs`, `hdfs_ha` and `s3` to` `file-assets`.
- [ ] Deprecate `redis` and `mongodb` until we have a good long term solution for those (we don’t actively use them and it’s hard to make changes to actively being used so if we keep them in there we are going to have support them forever)
- [ ] Possibly move out the `elasticsearch` connector but we’d need to make sure that it is still a dependency of `terafoundation` to avoid breaking things.

**Comment by kstaken** [comment]
This has happened.
