### ISSUE TITLE
Pick better timeouts in k8s waitForSelectedPod

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#1831]
There are two hard coded times in waitForSelectedPod:

* `timeout` - how long before it gives up [ref](https://github.com/terascope/teraslice/blob/master/packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8s.js#L72)
* `delay` - time between queries  [ref](https://github.com/terascope/teraslice/blob/master/packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8s.js#L94)

The `timeout` is definitely too short to accommodate image pull on job startup (10s ... what was I thinking?)

The delay is probably fine, but maybe should be configurable.  I'll review existing settings to see if anything is already appropriate.  Otherwise will improve defaults, usage or add configs.

**Comment by peterdemartini** [comment]
Maybe use the [`slicer_timeout`](https://github.com/terascope/teraslice/blob/2b3dbc5df6cf01175a14c69605e565e08b626d8a/packages/teraslice/lib/config/schemas/system.js#L146) or the [`action_timeout`](https://github.com/terascope/teraslice/blob/2b3dbc5df6cf01175a14c69605e565e08b626d8a/packages/teraslice/lib/config/schemas/system.js#L152)?

**Comment by godber** [comment]
This was fixed in the attached MRs
