### ISSUE TITLE
elasticsearch-state-storage metaKey is not consistently applied

### ISSUE THREAD

**Issue by ciorg** [terascope/teraslice#1985]
A user should be able to use the set_meta_key property on elasticsearch-state-storage to use fields other than `_key` to get and set records in elasticsearch as well as the cache.

But, the metaKey property is not applied everywhere a dataEnity is created so in some instances the metaKey is missing and breaks the state-storage functions - specifically the [_updateCacheWithEs function](https://github.com/terascope/teraslice/blob/master/packages/teraslice-state-storage/src/elasticsearch-state-storage/index.ts#L172)

Perhaps metaKey is the wrong name and it should be metaField, but tests need to be implemented to test this logic as well.

**Comment by ciorg** [comment]
After thinking through this more the problem isn't the creating a data entity but in the getIdentifier function.

I want to retrieve a doc by something other than the _key field of the incoming doc. 

For example incoming doc { _key: a, _other_field: b }, retrieved doc { _key: b }.  I want to search by _other_field, but I have to save set it in the cache by its _key field.

My solution right now is that mget/ get functions can use other metadata fields for searching, but all functions that set the doc in the cache or in es use the _key field.  I think this is correct.

**Comment by peterdemartini** [comment]
@ciorg can we close this?

**Comment by ciorg** [comment]
fixed by pr #1989
