### ISSUE TITLE
teraslice should provide more information on which asset validation check fails on job posting

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2005]
Right now, on job registration, if a job is posted that requires an asset that doesn't currently match the existing assets `node_version`, `platform` and `arch` you will get the following generic error:

```
Failure to get assets, caused by Error: No asset with the provided name and version could be located, asset: example
    at _getAssetId (/app/source/packages/teraslice/lib/storage/assets.js:148:19)
```

The error should explicitly tell you which thing is failing.

**Comment by godber** [comment]
I am also thinking that maybe `earl asset build` should have an arg that just jams *falsey** into those fields for dev purposes.  Otherwise I think we're stuck temporarily putting falsey values into the asset.json while we're fiddling around developing an asset.

**Comment by peterdemartini** [comment]
What would we call this flag, something like `--disable-restrictions` or something more generic like `--dev`?

**Comment by godber** [comment]
Let's add a `--dev` for this case.

**Comment by peterdemartini** [comment]
This is done
