### ISSUE TITLE
Add Teraslice 'snapshot' api command

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2088]
Users should be able to hit an API endpoint:

* `/ex/EXID/_snapshot -XPOST`
* `/job/JOBID/_snapshot -XPOST` (should this be on ``/job/JOBID/ex/_snapshot`

This should store a base64 encoding of the output of all of the related k8s resources somewhere.  Maybe just slap it on the ex?  It's liable to be big ... well, a few k of yaml.

**Comment by godber** [comment]
There could very well be arguments against this sort of feature ... like needlessly exposing implementation or operational details.

There may be a better way to address this need.  But I thought it might be a good idea.

**Comment by peterdemartini** [comment]
What would this be used for?

**Comment by godber** [comment]
It captures the k8s details at a specific point in time so they can be reviewed for troubleshooting purposes.

There's probably other ways to do it ... but right now, end users have no way of seeing (or saving things to be reviewed later) some of the details of what's going on in there job.

There's probably a better way to deal with this ... and slapping it on the ES is probably a bad idea.  The same info could just be exposed via the API, though storing it for review rather than exposing it to the end user could have the benefit of not leaking implementation details to the user, but storing it for operators.

**Comment by godber** [comment]
This probably shouldn't be added ... but it was interesting to consider.  Closing.
