### ISSUE TITLE
Teraslice k8s workers should be able to have different cpu request and limit

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2202]
Right now, the k8s deployment for the teraslice worker sets CPU request and limit to the same thing.  There should be a way that these can be set differently.  We are seeing some jobs that read from kafka who's workers lag more than others and eventually fall behind.  I suspect that if these workers could burst a little bit, they would probably catch up.

Initially I am thinking something like make `limit = request + limit_offest` where `limit_offset = 1` by default but can be overridden by job.

**Comment by peterdemartini** [comment]
Wouldn't it be easier to just use the same k8s config options, like `limit` and `request`?

**Comment by godber** [comment]
That would be most straight forward, sure.  I guess I could maintain backwards compatibility by doing:

* if `cpu` is a number, do what we do now `request` = `limit` = `value`
* if `cpu` is `{ request: requestValue, limit: limitValue}`, use those values as you would expect.
