### ISSUE TITLE
Job allocation fails 

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#221]
I was testing on a two node cluster where apparently there was only 1 worker available on each node. When attempting to run a job the following sequence occurred. The job was left in running state although there was no actual way for it to run. The main concern here is the reducing allocation to 0 then saying starting 0.

This is a docker-compose log.

```
teraslice-master_1 | {"name":"teraslice","hostname":"dd329cd73f67","pid":10,"level":30,"msg":"JobsService: Scheduling job: 1f64c36d-d0d6-4f64-9f72-ee10d66b2875","time":"2016-06-02T18:15:09.448Z","v":0}
teraslice-worker_1 | {"name":"teraslice","hostname":"f7f172ac70b3","pid":1,"level":30,"msg":"Starting 1 slicer","time":"2016-06-02T18:15:09.496Z","v":0}
teraslice-worker_1 | {"name":"teraslice","hostname":"f7f172ac70b3","pid":1,"level":30,"msg":"Attempting to allocate 1 workers.","time":"2016-06-02T18:15:09.515Z","v":0}
teraslice-worker_1 | {"name":"teraslice","hostname":"f7f172ac70b3","pid":1,"level":40,"msg":"Worker allocation request would exceed maximum number of workers - 1","time":"2016-06-02T18:15:09.517Z","v":0}
teraslice-worker_1 | {"name":"teraslice","hostname":"f7f172ac70b3","pid":1,"level":40,"msg":"Reducing allocation to 0 workers.","time":"2016-06-02T18:15:09.517Z","v":0}
teraslice-worker_1 | {"name":"teraslice","hostname":"f7f172ac70b3","pid":1,"level":30,"msg":"Starting 0 worker","time":"2016-06-02T18:15:09.517Z","v":0}
```

**Comment by kstaken** [comment]
The node configuration here had terafoundation.workers: 8 but came up with only 1 worker available. I believe since this is running in a VM there is only 1 CPU and it seems explicitly setting terafoundation.workers no longer works. Moving it to teraslice.workers does work but I thought terafoundation.workers should still work too.

**Comment by jsnoble** [comment]
we previously decided to control the number of workers from teraslice.workers, which overrides anything set at terafoundation level i believe. I will look into how it went into the negative for the allocations

**Comment by kstaken** [comment]
Yes teraslice.workers should override the terafoundation setting but in
this instance there was no teraslice.workers set, only
terafoundation.workers and it was ignored.

**Comment by jsnoble** [comment]
teraslice.workers is always set, it's default value is the amount of cpu cores that are available
