### ISSUE TITLE
finalize api endpoints

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#226]
This is meant to be a continuation of the discussion we had on api endpoints.

We considered following elasticsearch's way of naming endpoints vs hybrid approach vs all plain endpoints, as well on how to handle events like stop, start and resume on jobs

localhost:5678/_jobs/8718e57f-1133-451c-bcef-7946f148cc87/_slicer
vs
localhost:5678/jobs/8718e57f-1133-451c-bcef-7946f148cc87/_slicer
vs
localhost:5678/jobs/8718e57f-1133-451c-bcef-7946f148cc87/slicer

curl localhost:5678/cluster/_slicers
vs
curl localhost:5678/_cluster/slicers
vs
curl localhost:5678/cluster/slicers

Our initial thoughts were to not follow exactly elasticsearch's naming as it deals with index's and we don't, it would require us to add a '_' to pretty much everything.

**Comment by kstaken** [comment]
My thoughts on this now are that we should only use the _ when it's an action that modifies the resource.

So 

localhost:5678/jobs/8718e57f-1133-451c-bcef-7946f148cc87/_stop
localhost:5678/jobs/8718e57f-1133-451c-bcef-7946f148cc87/_start

But non-modifying requests would not use it. So the slicer endpoint would be different.

localhost:5678/jobs/8718e57f-1133-451c-bcef-7946f148cc87/slicer

And the cluster information would just be 

localhost:5678/cluster/state
localhost:5678/cluster/slicers
