### ISSUE TITLE
loading ops from an npm module needs finer grained error handling

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#239]
If an op is defined as an npm module and there's an error in the module teraslice reports:

```
Job submission failed Error validating job: Error: Could not retrieve code for: simple_api_reader, error message: Error: Cannot find module '../../readers/simple_api_reader'
```

In this instance there was a missing dependency on the module and the error teraslice is providing is misleading. The catch should only move to loading from other locations if the module truly isn't found.

**Comment by jsnoble** [comment]
resolved in latest commit
