### ISSUE TITLE
Check returned job list for empty list

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2438]
The k8s API could return an empty list here:

https://github.com/terascope/teraslice/blob/d11b5fce61f33198d531e776ec4269dcb1932341/packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/index.js#L129-L132

We should retry a few times if that is the case, then raise an error if it is retried too many times.  I think it's possible for this to return an empty list even when the execution controller is running, but the state in k8s is not updated so the list is not yet populated.

**Comment by peterdemartini** [comment]
@godber  I think we can close, this right?

**Comment by godber** [comment]
Yeah
