### ISSUE TITLE
Separate job config from job execution

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#245]
Currently we have a single job record that is overloaded with both the job configuration and job execution responsibility. It would be much more flexible to separate the roles so that a single job configuration could be executed on the cluster many times without having to be resubmitted from scratch.

**Comment by jsnoble** [comment]
the job execution context will also need to contain info regarding what is the slicer_port and slicer_hostname for the job, and get rid of hacks in the cluster service for dynamic worker addition etc

**Comment by jsnoble** [comment]
Completed
