### ISSUE TITLE
Jobs stuck in initializing

### ISSUE THREAD

**Issue by synmacs** [terascope/teraslice#2572]
I am using teraslice to do large data pulls from elastic and write them to LDJSON. A number of these jobs run on a crontab, and I use a script to generate the <job>.json file and post it. This teraslice instance is a single node instance running elastic install from repo and teraslice:0.70.0 in docker.

I am running into a problem where a job occasionally gets stuck initializing. When this occurs, all other jobs that run subsequently from the crontab get put into a pending state. The only resolution to this is to kill and restart the container or reboot the node, and then the remaining jobs kick off just fine. The job stuck in initializing becomes permanently stuck initializing. When I try and start it via teraslice-cli jobs start localhost <job_id>, I get an error stating the job is already running and that you may not start another job with the same ID. understandable. When I run 'teraslice-cli jobs stop localhost <job_id>, I get an error stating the job is not running and therefore can not be stopped. When I use the reset option, I get a job reset statement, but the job remains initializing and the timestamps do not update. Ideally I could monitor for these jobs (stuck initializing for > 1 minute), and kill them so they do not impact jobs which will run later from the crontab without having to kill the container or restart the node. The problem is that I can't kill them, so a restart script will keep the node in a reboot cycle due to a job being in initializing.

If this is not a bug and an artifact of something different (using the crontab, etc...) then I would be happy to know and use a better approach.

**Comment by peterdemartini** [comment]
Thank you for reporting this, we've recently fixed this in [v0.73.2](https://github.com/terascope/teraslice/releases/tag/v0.73.2)
