### ISSUE TITLE
Switch aws-sdk to @aws-sdk/client-s3

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#2589]
Currently we use the [aws-sdk](https://www.npmjs.com/package/aws-sdk) which is 50Mb and contains more than we need, we switch to their new s3 client to reduce the size, which also has a more modern API. This will be a breaking change to the connector since the API is changed to using async/await, so we might need to create an entirely new connector or figure out a way to safely migrate to this without breaking jobs.

**Comment by godber** [comment]
I don't think this is relevant anymore, we have updated to the v3 package that is split out, we also moved the connector into the asset.

* https://github.com/terascope/teraslice/pull/3356/files
* https://github.com/terascope/file-assets/commit/cdd037ae0f63bbb0c86a17c495ebc5c221944452
