### ISSUE TITLE
k8s - Add force parameter to Teraslice Job stop API that force deletes things

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#2670]
It would be nice if k8s pods could be forcibly deleted as an option using the Teraslice job stop API.

Currently when stopping jobs it's like

```
POST /job/JOBID/_stop
```

perhaps an option like this:

```
POST /job/JOBID/_stop?force
```

I'd have to take a look at the k8s library I am using and see how I am using it and if force parameters can be added to these API calls, but the `kubectl` equivalant would be:

```
kubectl delete pods PODNAME --grace-period=0 --force
```

I'm not sure offhand how that works when deleting k8s jobs and deployments.

**Comment by busma13** [comment]
I've spent some time playing with the `POST /job/JOBID/_stop` api endpoint as well as using `kubectl` with different combinations of `force` and `grace-period`.  Here are my thoughts so far:

- `POST /job/JOBID/_stop` is equivalent to `kubectl delete jobs`, not `kubectl delete pods`.  No combination of `force` and `grace-period` on a job will send a `SIGKILL` to worker and execution pods.  The worker pods will shutdown gracefully or timeout after `sysconfig.teraslice.shutdown_timeout` milliseconds. In prod this time is set to 5 minutes.
-  Calling `kubectl delete pods --grace-period=0` will send a `SIGKILL` to the pods specified, killing them instantly.  But without shutting down the jobs or/and resources first, the pods may restart automatically.
- Adding a `force` option to the  `POST /job/JOBID/_stop` endpoint would require adding a second request to the `jobs` section of the `k8s` client `delete` function that would delete all pods associated with the job.  This feels like the wrong approach, as we are fighting against the design principles of kubernetes. There may be possible race conditions where new worker pods are created to replace the killed pods if jobs/deployments are not yet deleted.

There are multiple scenarios that we are trying to fix:
1. A job is in a terminal state and is not allowed to be stopped. We don't need to shut pods down immediately. This should coincide with the `force` option?
2. A job is not in a terminal state, but we want the worker pods to shutdown immediately, without waiting `sysconfig.teraslice.shutdown_timeout` milliseconds. This should coincide with the `grace-period` option?
3. A combination of 1 and 2: terminal state that we want to shut down immediately.

**Comment by busma13** [comment]
I missed something earlier:
- When using `force` and `grace-period` together grace period is ignored.
- This command will achieve scenario 2:
```kubectl -n <teraslice-namespace> delete pods -l teraslice.terascope.io/jobName=<job-name> --grace-period=0```
    - The `teraslice.terascope.io/jobName` label is on the ex controller job, ex controller pod, worker deployment, worker replica set, and all worker pods for a specified job.
    - Because all jobs and deployments are deleted in tandem with the worker and ex controller pods, we won't be fighting against Kubernetes.

**Comment by busma13** [comment]
https://github.com/kubernetes/kubernetes/issues/120449

According to this issue the behavior of grace period is different between v1.18 and v1.27 than before or after those versions:
 
"In fact, processes gets killed if we set --grace-period=0 in ver1.18.
But it seems that the behavior got changed between ver1.18 and ver1.27.

    ver1.18 ... grace-period=0 kills Pod's processes immediately
    ver1.27 ... grace-period=0 sends SIGTERM to Pod's processes first, then wait for Pod's terminationGracePeriodSeconds before sending SIGKILL. As a result, when I execute kubectl delete pod grace-period=0 --force , message "pod pod-name force deleted" is shown, but pod's process is not killed immediately. It lives during terminationGracePeriodSeconds .
"

The behavior was changed back in v1.28.

**Comment by busma13** [comment]
When using `kubectl` setting the `force` flag will set `gracePeriod` to 0 in the `curl` request body.  This is why you can't use `gracePeriod` and `force` together. If you set `gracePeriod` to 0 when using the k8s node API you are actually telling k8s to use force instead.  `gracePeriod` must instead be set to 1.

**Comment by godber** [comment]
And the key to being able to reproduce this easily ourselves is this log line:

```
[2023-12-07T01:18:48.110Z]  INFO: teraslice/11 on ts-exc-data-generator-cacda274-6685-c56nr: execution_controller shutdown took 6s, exit with zero status code (assignment=execution_controller, module=execution_controller:shutdown_handler, worker_id=TQKG8Sw7, ex_id=fa92040e-b25e-464e-8b81-20edf38a99ed, job_id=cacda274-6685-4457-be88-706a15866888)
```

Specifically `execution_controller shutdown took 6s, exit with zero status code`.  So if you `process.exit(0)` from inside the slicer, I think you can reproduce this problem.  There may be a timing component to it, I'm not sure.  So if the first thing the slicer does is exit, it may not work, you may have to "process some slices" first, then exit.

**Comment by busma13** [comment]
I will definitely give this a try.

**Comment by godber** [comment]
I was given a new way to try and reproduce one of these situations.  With an elasticsearch reader, give it a query that is invalid.  Here's a sample

```
TSError: slicer for ex XXXXXXXXXXXXX had an error, shutting down execution, caused by TSError: search_phase_execution_exception: [parse_exception] Reason: parse_exception: Encountered \" \")\" \")
```

I think an operation like this would work:

```
{
    "_op": "elasticsearch_reader",
    "connection": "es_foo",
    "index": "foo-2023.12.01",
    "query": "bar:( )",
    "date_field_name": "timestamp",
    "size": 10000
},
```

It's not clear if the job didnt ultimately clean it's workers up on its own.

**Comment by godber** [comment]
This is completed and shown to work.

**Comment by godber** [comment]
I think I have identified a repeatable failure scenario where force stop does not work.

* create a failing job with the bad query shown above e.g. `"query": "bar:( )",`
* let that job run to failure
* verify with `kubectl` that the execution controller pod has `Completed`
* Try and start the job again, this second execution will fail to start because the one before it is blocking it
* **NOW** try and call force stop, you should see that it does not clean up the resources

I think the problem is that the second time the job is started it has a new `exId`, and when stop tries to delete stuff by `exId` it is of course using the "latest" one, rather than the previous one, which is the one that has failed.

I distinctly remember telling @busma13 to change the way he was doing things to target the `exId` rather than the `jobId`.  I suspect this advice broke it.

This is pretty obvious if you pay close attention to master logs and see that the `exId` its trying to delete doesn't match the `exId` on the pods still running.

We should probably fix this force stop to delete by `jobId`, which is the obvious thing to do.  But this does still point to an architectural error in how Teraslice and K8s have a state synchronization problem, very specifically a new ex can be created and associated to the job as shown here:

```
curl -Ss localhost:5678/jobs/<JOBID>/ex | jq -r .ex_id
```

While k8s resources matching a different `exId` are still present in k8s.

**Comment by godber** [comment]
When addressing the issue above, please make the following additional changes:

* provide an explicit example of `force=true` in the docs so there are no questions about the syntax
* improve logging so `stop` and `stop?force=true` are different
* the `json` returned to the user calling stop with `curl` should include some message that acknowledges the `force` parameter (e.g. it's not just indicated in the logs, but also to the end user).
* Remove no longer needed deletion of worker deployment: https://github.com/terascope/teraslice/blob/f02b3a46a274ff6ef89f19a673846cde49bb3575/packages/teraslice/src/lib/cluster/services/cluster/backends/kubernetes/k8s.ts#L377-L388

**Comment by busma13** [comment]
ref: #3519

**Comment by busma13** [comment]
This is done. We want to eventually pull force out into its own endpoint. See #3519
