### ISSUE TITLE
Update supported Node versions to node 12/14

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#2704]
Packages are coming out dropping node 10 support, which means we need to consider removing that support as well since it out of LTS. As always the biggest challenge is updating node-rdkafka. Once we can verify the new version of node-rdkafka works, we can go ahead and do the following:

- [x] Update CI in kafka-assets to support node 12/14
- [x] Update CI in file-assets to support node 12/14
- [x] Update CI in standard-assets to support node 12/14
- [x] Update CI in elasticsearch-assets to support node 12/14
- [x] Update CI in teraslice to support node 12/14
- [x] Update the teraslice image to node 14
- [x] Update tsconfig and eslint ecmascript target to "es2019"

**Comment by godber** [comment]
I think these all cover the checkboxes above:

* https://github.com/terascope/elasticsearch-assets/pull/712
* https://github.com/terascope/file-assets/pull/604
* https://github.com/terascope/kafka-assets/pull/475
* https://github.com/terascope/standard-assets/pull/465
* https://github.com/terascope/teraslice/pull/2717

The teraslice tests won't pass until we have a node14 build of the elasticsearch asset.

**Comment by godber** [comment]
All of the asset PRs are green now.

**Comment by peterdemartini** [comment]
Let's get on with it then haha

**Comment by godber** [comment]
Assets are merged and released:

* [Elasticsearch](https://github.com/terascope/elasticsearch-assets/releases/tag/v2.6.0)
* [File-asset](https://github.com/terascope/file-assets/releases/tag/v2.1.0)
* [Standard-asset](https://github.com/terascope/standard-assets/releases/tag/v0.11.0)
* [Kafka-asset](https://github.com/terascope/kafka-assets/releases/tag/v3.2.0)

**Comment by godber** [comment]
The teraslice e2e tests still fail for node 12/14

https://travis-ci.com/github/terascope/teraslice/jobs/505614200

https://travis-ci.com/github/terascope/teraslice/jobs/505614204

It says it's an asset version mismatch problem, but I don't know how/why.  I'll come back to this tomorrow.

**Comment by peterdemartini** [comment]
Sorry, I forgot to tell you about this [line](https://github.com/terascope/teraslice/blob/master/e2e/test/download-assets.js#L9), this should have pulled from the `Dockerfile` or something

**Comment by godber** [comment]
These have all been completed and the `v0.77.0` image on docker hub uses node 14.  We will open individual issues to address anything that comes up.
