### ISSUE TITLE
teraslice-cli asset init on an empty folder only creates an `asset` directory

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#2824]
When running `teraslice-cli asset init` on an empty folder, you get:

<img width="364" alt="Screen Shot 2021-06-17 at 8 22 05 AM" src="https://user-images.githubusercontent.com/1044698/122426434-1bbd0e80-cf45-11eb-97b0-344abe7e2c97.png">

**Comment by kstaken** [comment]
This operation is not longer supported.
