### ISSUE TITLE
modularize date slicer to work on other values

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#320]

**Comment by kstaken** [comment]
This is to expand the slicer to work on other range searchable types. In particular numbers and IP addresses so that there are more ways that an index can be divided up.

**Comment by kstaken** [comment]
With the issues related to the id_reader and ES 6 #687 we should look at this more closely to make sure we have plenty of options for slicing data from ES indices.

**Comment by jsnoble** [comment]
migrated issue to elasticsearch-assets repository
