### ISSUE TITLE
Teraslice Docker Images Should have Annotations (labels)

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3257]
The Teraslice Docker Image should have an image LABEL or annotation:

https://github.com/opencontainers/image-spec/blob/main/annotations.md

For example

https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile#L97-L106

or

https://github.com/elastic/dockerfiles/blob/8.1/elasticsearch/Dockerfile#L138-L156

**Comment by mkhpalm** [comment]
How about this added to the Dockerfile to add annotations for opencontainers images spec

```
LABEL org.opencontainers.image.version="$TERASLICE_VERSION" \
  org.opencontainers.image.created="$(date +'%Y-%m-%dT%H:%M:%S')" \
  org.opencontainers.image.documentation="https://terascope.github.io/teraslice/docs/overview" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.revision="$GITHUB_SHA" \
  org.opencontainers.image.source="https://github.com/terascope/teraslice" \
  org.opencontainers.image.title="Teraslice" \
  org.opencontainers.image.url="https://terascope.github.io/teraslice" \
  org.opencontainers.image.vendor="Terascope"
```

**Comment by busma13** [comment]
Are `TERASLICE_VERSION` and `BUILD_TIMESTAMP` environmental variables that will be available in CI? I know `GITHUB_SHA` is.
I can grab the teraslice version out of the package.json if needed.
