### ISSUE TITLE
pegging node 16 in tests to v16.10.0

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#3307]
there are some issues with using jest with any version of node >= 6.11.0. There is a memory leak that causes the tests to expand a lot. The addition of their work around `workerIdleMemoryLimit` didn't seem to alleviate our problem. There are other approaches we could take but after talking to Austin we decided to just use this version of node for now.

- https://github.com/facebook/jest/issues/11956

**Comment by godber** [comment]
Related to @jsnoble attempt to complete:

https://github.com/terascope/teraslice/pull/3303

Here's a few other related Refs:

* https://github.com/facebook/jest/issues/11956
  * https://github.com/luiz290788/jest-node-16
* https://github.com/nodejs/node/issues/40014
* https://github.com/nodejs/node/issues/44211
* https://bugs.chromium.org/p/v8/issues/detail?id=12198

Classic finger pointing situation.
