### ISSUE TITLE
teraslice-cli fails while trying to build an asset registry

### ISSUE THREAD

**Issue by ciorg** [terascope/teraslice#3323]
command `teraslice-cli assets init --registry` fails with the error: `Callback support have been removed.`

**Comment by ciorg** [comment]
Dug into this a little.

At some point the `yeoman-environment` stopped accepting call back functions in the options that are passed to the `environment.run` function.  Here's where the error is being thrown https://github.com/yeoman/environment/blob/main/lib/environment.js#L984 and here's an example of the cli code that is calling run and passing in a function for the options - https://github.com/terascope/teraslice/blob/master/packages/teraslice-cli/src/cmds/assets/init.ts#L61 for the options.  

Should be noted that any `teraslice-cli assets init` command will throw this error not just `--registry`, they all use the same pattern to print all done.

**Comment by godber** [comment]
The init command has been removed and the `registry` subcommand has been added to handle this issue.

```
earl  assets
earl assets <command>

commands to manage assets

Commands:
  earl assets build                              Builds asset bundle.

  earl assets delete <cluster-alias> <asset-id>  Delete asset from cluster.

  earl assets deploy <cluster-alias> [<asset>]   Uploads asset from zipfile, github, or source to Teraslice

  earl assets registry                           Creates or updates a registry for an asset bundle at `assets/index.js` or `assets/src/index.ts`

  earl assets list <cluster-alias>               List assets on a cluster.


Options:
  -h, --help     Show help                                                                                                                                                                                                         [boolean]
  -v, --version  Show version number                                                                                                                                                                                               [boolean]

Not enough non-option arguments: got 0, need at least 1
```
