### ISSUE TITLE
Build docker images against multiple versions (including node 18)

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#3354]
- need to migrate code and ensure packages can be built and work on node 18
- this will also require the base image to be able to be built with kafka on node 18

**Comment by godber** [comment]
We do have a node 18 base image here:

https://hub.docker.com/r/terascope/node-base/tags

But to be clear, we can't convert the default build of the Teraslice image in this repo (here: https://github.com/terascope/teraslice/blob/master/Dockerfile#L1) to node 18 until after all of the assets, public and internal, have been updated and work on Node 18.

So the current scope of this issue is to get our tests passing on Node 18.

**Comment by godber** [comment]
Currently, we build a single docker image with the node version shown here:

https://github.com/terascope/teraslice/blob/master/Dockerfile#L1

That yields an image like this:

```
terascope/teraslice:v0.86.1
```

I propose we change this to build images with the following names:

```
terascope/teraslice:v0.86.1-node14
terascope/teraslice:v0.86.1-node16
terascope/teraslice:v0.86.1-node18
```

These will be built using our existing base images with versions listed here:

https://github.com/terascope/base-docker-image/blob/master/.github/workflows/release.yml#L16

We can specify these versions in the top level `package.json` which is a place already used for this type in information by ts-scripts (e.g. [here](https://github.com/terascope/teraslice/blob/f682a188474721261ff802301eb5960c6197c771/packages/scripts/src/helpers/publish/index.ts#L89))

```
    "terascope": {
        ...
        "nodeVersions": [
            "14.21.3",
            "16.20.0",
            "18.16.0"
        ],
        ...
     }
```

Ideally I'd find a way to get the github actions to read the global `nodeVersions`.

**Comment by godber** [comment]
Also worth mentioning ... right now the docker image are built with the following command:

```
        run: yarn ts-scripts publish -t tag docker
```

Run here:

https://github.com/terascope/teraslice/blob/f682a188474721261ff802301eb5960c6197c771/.github/workflows/publish-tag.yml

I will make the same command, create all images against all versions listed in the top level `package.json` as suggested above.

**Comment by jsnoble** [comment]
hmm, we could do that, and have that as an option. However I think that we can also play this like the script changes for standing up test enviroments. We can have stuff set on the top level package.json, or we can have scripts search for an environmental variable set by github based off the matrix so it know what node version to build

**Comment by godber** [comment]
Ok, I need to think carefully about the naming of each type `tag`, `dev`, and `latest`.

```
 packages/scripts/bin/ts-scripts.js publish --dry-run -t tag docker
 packages/scripts/bin/ts-scripts.js publish --dry-run -t dev docker
 packages/scripts/bin/ts-scripts.js publish --dry-run -t latest docker
```

Also it looks like there are some fun couplings with other parts of the tools expecting to find the Node version in the `Dockerfile` as if it is authoritative ...

https://github.com/terascope/teraslice/actions/runs/5981467639/job/16229352995?pr=3390

```
⬤  debug     Setting e2e test suite env to HOST_IP: "10.1.32.0", NODE_ENV: "test", FORCE_COLOR: "1", TEST_NAMESPACE: "ts_test", TEST_INDEX_PREFIX: "ts_test_", ELASTICSEARCH_HOST: "http://10.1.32.0:49200/", ELASTICSEARCH_VERSION: "6.8.6", ELASTICSEARCH_API_VERSION: "6.5", SEARCH_TEST_HOST: "http://10.1.32.0:49200/", KAFKA_BROKER: "10.1.32.0:49092", KAFKA_VERSION: "3.1"
Error: Jest: Got error running globalSetup - /home/runner/work/teraslice/teraslice/e2e/test/global.setup.js, reason: Expected to find a valid node major version in the Dockerfile but found NaN
    at getNodeVersion (/home/runner/work/teraslice/teraslice/e2e/test/download-assets.js:29:15)
    at Object.<anonymous> (/home/runner/work/teraslice/teraslice/e2e/test/download-assets.js:35:21)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.newLoader (/home/runner/work/teraslice/teraslice/node_modules/pirates/lib/index.js:121:7)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/runner/work/teraslice/teraslice/e2e/test/global.setup.js:10:24)
```

**Comment by godber** [comment]
Here's the naming of the resultant images:

```bash
REPOSITORY                       TAG                      IMAGE ID       CREATED          SIZE
terascope/teraslice              v0.86.1-node-14.21.3     1b4b2817298e   7 minutes ago    1.3GB
terascope/teraslice              dev-local-node-14.21.3   4f314ef8d395   11 minutes ago   1.3GB
terascope/teraslice              dev-local-node-18.16.0   a4a4433f481e   43 minutes ago   1.39GB
terascope/teraslice              v0.86.1-node-18.16.0     a4a4433f481e   43 minutes ago   1.39GB
```

**Comment by godber** [comment]
I have gotten the e2e framework itself to work with multiple docker images at this point, though the e2e tests do not pass when using the node 18 based image:

https://github.com/terascope/teraslice/actions/runs/6437904912/job/17491393374

These "pass" on master branch:

https://github.com/terascope/teraslice/actions/runs/6441710458

But of course, the docker image that's being tested is actually a Node 14 image, not a node 18 image.  So the node version matrix in the `e2e` job below is not doing what one might think it's doing ... at least not until we accept my PR:

https://github.com/terascope/teraslice/blob/master/.github/workflows/test.yml#L215-L247

Making the docker build Node version independent is the whole point.

At this point we can pause to find out why e2e doesn't work on Node 18 and fix it in this PR.  Or pull node 18 out of that action and accept this PR and file an issue to fix node 18 in the very very near future.

/cc @sotojn @busma13

**Comment by godber** [comment]
You can find the failed `e2e` tests on this PR:

https://github.com/terascope/teraslice/actions/runs/6437904912

Specifically here:

https://github.com/terascope/teraslice/actions/runs/6437904912/job/17611495627

**Comment by godber** [comment]
Completed.
