### ISSUE TITLE
Add Opensearch 2.x support

### ISSUE THREAD

**Issue by briend** [terascope/teraslice#3357]
We should ensure teraslice can use Opensearch 2.x for its state cluster

https://github.com/opensearch-project/OpenSearch/releases

related: https://github.com/terascope/teraslice/issues/3245, https://github.com/terascope/teraslice/issues/2734

Lets target OpenSearch v2.8.0.

**Comment by godber** [comment]
We probably need an issue in The elasticsearch-asset too.  Changes are likely necessary in both projects.

**Comment by godber** [comment]
These PRs are probably related:

* https://github.com/terascope/teraslice/pull/3370
* https://github.com/terascope/teraslice/pull/3373
