### ISSUE TITLE
Update and/or verify elasticsearch index mappings on startup

### ISSUE THREAD

**Issue by briend** [terascope/teraslice#3381]
When a teraslice master starts up the first time it creates indices with correct mappings for the `__ex` execution index.  However if the mappings need to change later they are not managed automatically (see related issue https://github.com/terascope/teraslice/issues/3379, for instance, when upgrading from `v0.86.0` to `v0.86.1`).

**Comment by godber** [comment]
Let's disregard this for now since it only works in special cases and we don't even want it in the case linked to above.  If it becomes relevant again, e.g. we start adding to mappings, we can re-open this issue.
