### ISSUE TITLE
update dependency: got from v11.8.6 to v13.0.0 when we eliminate node 14

### ISSUE THREAD

**Issue by sotojn** [terascope/teraslice#3396]
Dependabot was trying to update the `got` dependency but failed because it no longer supports `node version 14`.

Below I added the closed pull request that addresses this issue. As of right now, `got` only supports `node 16` or later.

Sometime down the line when we no longer use `node 14`, we need to update this dependency and re-enable it for debendabot.

ref #3377

**Comment by godber** [comment]
`got` is already in this issue here: https://github.com/terascope/teraslice/issues/3304

I will close this one.
