### ISSUE TITLE
add feature to --replace flag within terascope-CLI

### ISSUE THREAD

**Issue by sotojn** [terascope/teraslice#3402]
I'm using the following teracope-cli command to build and deploy to my cluster.

``` $ teracscope-cli assets localhost --build --replace ```

My issue is that I expect the ``` --replace ``` flag to overwrite my old **.zip** file within the ``` build ``` folder in my asset directory.

I'm aware that if I use this command --> ``` $ teracscope-cli assets build --overwrite ``` that it correctly overwrites the file, but I feel that the ``` replace flag ``` should be expected to do the same and would be more practical in some instances.

Here is the current result when trying to use the ``` replace ``` flag.
```  
% earl assets deploy localhost --build --replace                                          
Beginning asset build.
Failure to build asset, caused by Error: Zipfile already exists "/Users/jsoto/Workspace/teraslice/joseph-asset-v-2/build/joseph-asset-v-2-v0.1.0-node-14-bundle.zip"  
```

Here is my expected output:
```
% earl2.0 assets deploy localhost --build --replace
Beginning asset build.
* copying files to the tmp directory "/var/folders/ht/_plsbr191vz0jl0br8cwypy80000gn/T/tmp-25310-RrnoUyx6zLNP"
[NOTE] Automatically added node_version, platform, arch restrictions for the asset Use --dev to temporarily disable this, or put false for the values node_version, platform, arch in the asset.json
* making tmp bundle directory "/var/folders/ht/_plsbr191vz0jl0br8cwypy80000gn/T/tmp-25310-Caa7x1NYZ0Li"
* running yarn --prod --no-progress
* entryPoint: /var/folders/ht/_plsbr191vz0jl0br8cwypy80000gn/T/tmp-25310-RrnoUyx6zLNP/asset/index.js
* doing a test require of /private/var/folders/ht/_plsbr191vz0jl0br8cwypy80000gn/T/tmp-25310-Caa7x1NYZ0Li/index.js
* overwriting /Users/jsoto/Workspace/teraslice/joseph-asset-v-2/build/joseph-asset-v-2-v0.1.0-node-14-bundle.zip
* zipping the asset bundle
Asset created:
	/Users/jsoto/Workspace/teraslice/joseph-asset-v-2/build/joseph-asset-v-2-v0.1.0-node-14-bundle.zip (158 kB)
*** Warning ***
The --replace option is intended for asset development only.
Using it for production asset management is a bad idea.
But Joseph thinks its fine.
Asset 4e4028444ccbb6a7640742f30646c0edeff deleted from localhost
Asset posted to localhost: 5a0adeb00173195c2e68bde3cde1088d9c6
```

So I was wondering inside of the **teraslice-cli** directory in ```teraslice-cli/src/cmds/assets/deploy.ts``` If we can add an ```if``` statement right before line 138 that checks to see if ```cliConfig.args.replace``` is true and then changes ```asset.overwrite``` to true before running ```asset.build()```.

Is that a viable solution or is there an alternate way to do it? Or is there potential cases where this can cause an issue.

**Comment by ciorg** [comment]
I agree would be a good improvement for the cli.  

The proposed solution sounds reasonable, it would be helpful if you added a link to line 138 in the code so that others could view what you are referring to.

**Comment by godber** [comment]
Completed
