### ISSUE TITLE
logging in regards to cluster_master

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#341]
as it stands currently, the logger used for the messaging model of cluster_master is the top level logger, not the logger for the cluster service where nearly all the registering of network calls are made. This is meant to be a standing ticket to advise as future changes are made.

**Comment by kstaken** [comment]
@jsnoble should review the current state on this and followup on this ticket if this is still a current issue.

**Comment by kstaken** [comment]
no longer relevant
