### ISSUE TITLE
Make test runner asset aware

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3413]
Update TS-scripts test to be able to find all of the test directories within an asset repository without modifying the workspaces array in the root package.json. 

TS-scripts test was originally written to run on Teraslice. When it started being used on assets, it could not find the asset's `test` directory because it is located at the root of the repository, not in the `/asset` directory. The workaround currently is to add `"."` to the workspaces array in the root package.json. If the test runner knows it is in an asset, it can find the proper test directories in a more direct manner. 

While updating bump.ts to run on assets, we had to include a workaround to filter out the `"."` when using the workspaces array, as it would throw a path not found exception.
ref:
https://github.com/terascope/teraslice/pull/3408/files#r1326211407

**Comment by sotojn** [comment]
Also it is important to remove the `.` inside workspaces within the top level `package.json` inside of the asset you are trying to run tests on. 

Lastly you need to add ` "testSuite": "none"` inside the terascope object within all `package.json` files that don't already have it or else the `-s` flag will not work.

refs to changes [here](https://github.com/terascope/file-assets/commit/e9610ffc51dc5c454c093ba798c7f748fe507fe9)

**Comment by godber** [comment]
This is all done, right?
