### ISSUE TITLE
Elasticsearch Cluster Moderator

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#344]
The cluster moderator will watch the clusters that jobs are running against with the goal of allowing jobs to run as fast as possible without overloading the clusters. Currently jobs have to be sized very carefully to take into account cluster capacity.

Initial implementation of this feature will largely watch the bulk and search queues. This will likely expand to also consider CPU and Heap usage.

**Comment by godber** [comment]
I suspect this was resolved, to some degree, in #350 right?

**Comment by jsnoble** [comment]
This service has been made, other tickets will be used to further discuss use cases and additional features
