### ISSUE TITLE
Update all spots to use cp-kafka docker image

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3444]
We want all places in Teraslice to use the same `cp-kafka` and `cp-zookeeper` Kafka setup, this should include:

* docker-compose
* e2e
* k8s e2e

I think you'll want the following two images:

* https://hub.docker.com/r/confluentinc/cp-kafka/tags
* https://hub.docker.com/r/confluentinc/cp-zookeeper

Let's keep using Kafka in Zookeeper mode, not KRaft.  Also we want Kafka 3.2, so you'll have to find which `cp-kafka` version that is.

**Comment by godber** [comment]
When this issue is complete, archive this repo: https://github.com/terascope/docker-kafka-zookeeper/settings

**Comment by sotojn** [comment]
This issue has been addressed and fixed in this merged PR #3454
Both e2e and k8se2e use the `cp-kafka` image. This carries over to kafka tests that are in the **teraslice/kafka-asset repo**.
