### ISSUE TITLE
k8s - Add option to reset ES Store to k8s-env command when rebuilding teraslice 

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3483]
The `tscripts k8s-env --rebuild` command will build a new Teraslice docker image and restart Teraslice within the Kubernetes cluster. It does not clear the elasticsearch indices. This is useful because there is no need to reload assets or register jobs after a rebuild. 

There are times where it is necessary to clear the elasticsearch indices and currently that requires you to delete the kind cluster and rerun `ts-scripts k8s-env`. 

Adding a new option, such as `clear-es` that could be used along with the `rebuild` option, would be helpful.

**Comment by godber** [comment]
This should be closed in the associated PR: https://github.com/terascope/teraslice/pull/3532
