### ISSUE TITLE
e2e asset download function for autoload does not check for node version

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3556]
I ran e2e tests in node 20. Node 20 assets were downloaded and placed in the `e2e/autoload` directory. I then ran e2e tests in node 18. The assets fail to load. I believe the `downloadAssets()` function in `e2e/test/download-assets.ts` downloads node 18 assets, then deletes them in the `deleteOlderAssets()` function in favor of the node 20 assets. There is most likely no check to see if the asset is the correct node version.

**Comment by godber** [comment]
https://github.com/terascope/teraslice/pull/3583
