### ISSUE TITLE
Fix or remove teraslice-cli asset generation tools

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3559]
The change to ESM and typescript have either already or will soon render much of the asset generation tools built into `teraslice-cli` out of date.

Even the tool that generates the registry isn't going to be doing it correctly after we switch to ESM modules:

https://github.com/terascope/teraslice/blob/93be7747cadd5da3f457be86cd22a507e232e72b/packages/teraslice-cli/src/generators/registry/index.ts

It generates code like this:

https://github.com/terascope/standard-assets/blob/master/asset/src/index.ts

It might be best just to cut this functionality out for now and consider adding it again in the future.

The registries are not that hard to write by hand, what is more important is that we protect ourselves from omitting processors when we build assets.  I think we can add a util that does something like this:

https://github.com/terascope/standard-assets/blob/master/test/index-spec.ts

Maybe `teraslice-cli assets registry-check` that gets run on asset MRs.  This way we don't forget to include our processors in the registries.

So I propose:

* removal of all asset template/generation code, including the registries
* addition of `teraslice-cli assets registry-check` utility

**Comment by godber** [comment]
@jsnoble I know you removed something relate to the generators ... I thought that would have meant the following were removed too:

* https://github.com/terascope/teraslice/tree/master/packages/teraslice-cli/src/generators
* https://github.com/terascope/teraslice/tree/master/packages/teraslice-cli/generator-templates

**Comment by godber** [comment]
See also #3611 which I have closed.

**Comment by godber** [comment]
This might be blocking our move to Node 22, so it's even more important to deal with this now.

**Comment by godber** [comment]
Here's another related issue: https://github.com/terascope/teraslice/issues/3323

**Comment by busma13** [comment]
As far as I can tell `teraslice-cli assets init --registry` can only create a JS registry file at `asset/index.js`. It can't currently create a TS registry file at `asset/src/index.ts` like we see in all of the main assets. 

Does it make sense to make one type or the other depending on if the repo uses tyepscript?

**Comment by godber** [comment]
Most of this work is completed, though the `generator-teraslice` package was removed, but it is still referenced in the documentations:

https://terascope.github.io/teraslice/docs/development/packages
