### ISSUE TITLE
Earl assets deploy does not block by default

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3565]
When deploying an asset with `earl` the request is not blocking by default. Earl will return a response that looks successful(green text) whether or not the asset upload succeeds or fails: `Asset posted to local: 94829e7e555678dda2161d6f804c13043c0f67d8`. If you pass `--blocking=false` and the asset fails to upload you will get an error message.

Is this still the desired default? Maybe this is left over from when assets were not bundled by default and took much longer to load?

@godber

**Comment by godber** [comment]
I don't think we should change this behavior, assuming things are working correctly.  We may have internal tooling that depends on the defaults.  And keep in mind there are several layers that could be blocking here:

* The Teraslice [asset API has a blocking parameter](https://terascope.github.io/teraslice/docs/management-apis/endpoints-json#post-v1assets)
* earl has it's own blocking parameter, that in turn sets the parameter on the post

It is still possible to have large assets, use `--blocking` if you want to wait for the outcome of your asset upload.

**Comment by godber** [comment]
Re-open this if the blocking itself is not working as it should be.
