### ISSUE TITLE
Track random test failures

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3589]
This is a place to link to all random, infrequent test failures. Hopefully we can better understand the problem/s if we can see them all.

4/5/2024
https://github.com/terascope/teraslice/actions/runs/8576554950/job/23507712338?pr=3584
error: `error Command failed with exit code 1.`
failed command: `yarn $YARN_SETUP_ARGS && yarn run build --force`

4/5/2024
https://github.com/terascope/teraslice/actions/runs/8576554950/job/23507715100?pr=3584
error: `fatal     TSError: Error: Command failed with exit code 125`
failed command: `docker run --rm --publish 49206:49206 --env ES_JAVA_OPTS=-Xms512m -Xmx512m --env network.host=0.0.0.0 --env http.port=49206 --env discovery.type=single-node --env DISABLE_INSTALL_DEMO_CONFIG=true --env DISABLE_SECURITY_PLUGIN=true --name ts_test_opensearch opensearchproject/opensearch:1.3.10`

4/10/2024
https://github.com/terascope/teraslice/actions/runs/8633938651/job/23668193654?pr=3584
error: `TSError: Port 37000 is already in-use`
`at pRetry (packages/utils/src/promises.ts:172:21)
      at Server.listen (packages/teraslice-messaging/src/messenger/server.ts:97:9)
      at Server.start (packages/teraslice-messaging/src/execution-controller/server.ts:53:9)
      at ExecutionController.initialize (packages/teraslice/src/lib/workers/execution-controller/index.ts:169:9)`

https://github.com/terascope/teraslice/actions/runs/8633938651/job/23668183380?pr=3584
`HTTPError: Response code 403 (rate limit exceeded)
    at Request.<anonymous> (/home/runner/work/teraslice/teraslice/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by sotojn** [comment]
To track down the `Port is already in-use` issue should we do a PR that lists all the running ports when this error occurs to get a better idea on whats going on in CI?

**Comment by godber** [comment]
The `Port is already in-use` issue could be a previous shutdown container port being in `TIME_WAIT` (2 min timeout).

**Comment by godber** [comment]
This looks new

https://github.com/terascope/teraslice/actions/runs/10728060227/job/29751854383#step:9:250

```
ℹ  info      Teraslice node version:  undefined
✖  error     Expected node version(20) does not match teraslice node version(undefined)
error Command failed with exit code 1.
```

**Comment by busma13** [comment]
I have seen this a few times. I added that check to ensure the node version was correct. I will wrap the `docker exec --version` call in a retry. That should do the trick.

**Comment by busma13** [comment]
PR here: #3741

**Comment by busma13** [comment]
https://github.com/terascope/teraslice/actions/runs/11620752664/job/32363197551?pr=3813

Summary of all failing tests
 FAIL  packages/teraslice-cli/test/helpers/jobs-spec.ts (9.849 s)
  ● Job helper class › export › should export all jobs to a custom directory

    /home/runner/work/teraslice/teraslice/packages/teraslice-cli/test/fixtures/job_exports/custom2/test-job-2.json: ENOENT: no such file or directory, open '/home/runner/work/teraslice/teraslice/packages/teraslice-cli/test/fixtures/job_exports/custom2/test-job-2.json'

      1110 |             jobFiles.push(fs.readJsonSync(path.join(customDir, 'test-job.json')));
      1111 |             jobFiles.push(fs.readJsonSync(path.join(customDir, 'test-job-1.json')));
    > 1112 |             jobFiles.push(fs.readJsonSync(path.join(customDir, 'test-job-2.json')));
           |                              ^
      1113 |
      1114 |             expect(jobFiles).toEqual(expect.arrayContaining([
      1115 |                 expect.objectContaining(

      at Object.readFileSync (node_modules/jsonfile/index.js:50:22)
      at Object.readJsonSync (packages/teraslice-cli/test/helpers/jobs-spec.ts:1112:30)

**Comment by busma13** [comment]
I broke the test failures that have not been resolved into new issues. Closing
