### ISSUE TITLE
move s3 asset storage related fields to teraslice section of config

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3601]
When the external asset storage feature was implemented, all the fields in the config were put in the `terafoundation` section, but they are specific to `teraslice` so should be in that section.

To move them to `teraslice` we need to move the validation function. Unfortunately it requires access to `terafoundation.connectors` so the inputs to validator functions will need to allow for the whole config to be passed in.

**Comment by godber** [comment]
Lets deprecate the `asset_storage_*` keys in `terafoundation.` at the same time as adding them to `teraslice.`  That way we're not making a breaking change to the `terafoundation.yml`.  Also make sure to add comments that allow us to find and remove the asset_storage keys that need to be removed in 2.0.
