### ISSUE TITLE
Adding node 22 to CI test suite

### ISSUE THREAD

**Issue by sotojn** [terascope/teraslice#3605]
We need to add node 22 to the list of node versions teraslice tests. There are several separate repos on top of teraslice that need to be changed in order to properly include a new node version. So far we don't have documentation on this topic so we should also include that in the development docs while we add node 22.

NOTE: It's required to update the base image [here](https://github.com/terascope/base-docker-image/issues/24) before moving on with doing the following steps.

We need to update the arrays in the following files:
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/publish-tag.yml#L45
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L35
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L58
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L86
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L120C33-L120C40
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L154
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L188
https://github.com/terascope/teraslice/blob/879af4247784a39449e536ca3a79165a3c902469/.github/workflows/test.yml#L226

Adding `22.1.0` to all of these will include node 22 in all of the CI tests and also build and push a node 22 teraslice image to docker hub.

**Comment by godber** [comment]
Note, these failures are not due to a missing image, but because running yarn fails
https://github.com/terascope/teraslice/actions/runs/8975998521/job/24655637262

**Comment by godber** [comment]
@sotojn added some docs here: 

https://github.com/terascope/teraslice/blob/master/docs/development/node.md

But they don't show up in the site under the development page:

https://terascope.github.io/teraslice/docs/development/overview

There's probably an index somewhere or some frontmatter we need to add to get it to show up.

**Comment by godber** [comment]
Oh, it shows up as it's own page here:

https://terascope.github.io/teraslice/docs/development/node

Maybe the use of `sidebar_label: Node` somehow breaks it out of the Development tab its supposed to be under.
