### ISSUE TITLE
Refactor promMetrics to require check for its existence

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3625]
We are going to remove the promMetricsProxy from terafoundation and instead check for the existence of promMetrics anywhere the API is called. We realized assets with promMetrics calls would need another proxy in the `job-components` core to make them compatible with older versions of teraslice.  It seems much better to just simplify things and check for the existence of the API anytime we use it. 

We will add a helper function into `job-components` to make the check a little cleaner.

We need to update the following list of asset releases to indicate that they should not be used:

* standard-assets
  * `v0.25.0`
  * `v0.24.1`
  * `v0.24.0` 
* kafka-assets
  * `v4.4.0`
  * `v4.3.0`
  * `v4.2.0`
  * `v4.1.0`
* file-asset
  * `v2.11.0`
* elasticsearch-asset
  * `v3.7.0`
  * `v3.6.0`

**Comment by godber** [comment]
This PR implements the first step: https://github.com/terascope/teraslice/pull/3629

Next we have to go update all the assets to use this.  When those are done, we need to come back here and remove the proxy in terafoundation.  If we do it in the wrong order e2e tests faile.

**Comment by busma13** [comment]
# Caution: this asset is only compatible with teraslice v1.4.0 through v1.7.1

**Comment by sotojn** [comment]
### \*Do Not Use\*
_**Reason**_: this version of the asset is incompatible with teraslice versions older than`v1.4.0` and and version greater than or equal to `v1.7.2`. This was because of a breaking change when implementing prom metrics.

**Comment by godber** [comment]
*Do Not Use This Release*: Use release X or Newer

NOTE: This release of the asset is only compatible with Teraslice versions between `v1.4.0` and `v1.7.1`. This was because of a breaking change when implementing prom metrics.

**Comment by godber** [comment]
This and all the related work is completed.
