### ISSUE TITLE
Base and teraslice image carrying unnecessary packages and deps

### ISSUE THREAD

**Issue by sotojn** [terascope/teraslice#3634]
As of right now out base image and teraslice image carries a lot of unwanted packages and utilities such as the following:

- python 
- setuptools

This list needs to be expanded on but here is the list of everything we install in the base image

```Dockerfile
RUN apk --no-cache add \
    bash \
    curl \
    tini \
    apk-tools \
    build-base \
    ca-certificates \
    libstdc++ \
    lz4-dev \
    musl-dev \
    ncurses-terminfo \
    libssh2-dev \
    openssl-dev \
    cyrus-sasl-dev \
    zstd-dev \
    python3

```

We may need to read into all of these and see why each of these are used and restructure our Dockerfiles to reduce size and cut out things that are only used during build time.

**Comment by godber** [comment]
Ultimately I see us trying to address the problem stated in this issue by making another attempt at this issue:

https://github.com/terascope/teraslice/issues/3518

**Comment by godber** [comment]
I'm going to close this for now, we'll try to reduce the image size again in the future, but probably like #3518
