### ISSUE TITLE
Add better error messaging to 'POST /v1/assets` route

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3640]
When making a curl request to `POST /v1/assets` we should check that we receive a zip file before decompressing it.  If you forget the `@` before the file path curl sends the path as a string instead of sending the file.  Since we don't confirm what we've received before decompressing and saving, the error we get back is not helpful.

**Comment by briend** [comment]
I think this would help catch a scenario I ran into where I uploaded a totally bogus "zip" file containing a `404` response.  I assumed that everything was fine since it returned to me an asset id, and no error.

```
# this was a 404
curl -o asset.zip $url

earl assets deploy $TS_CLUSTER -f asset.zip
Asset posted to teraslice-cluster-01: 38dd28219082fea56e8703e45cb3975e00ff2a6a
```
