### ISSUE TITLE
Remove OpTestHarness references in docs and interface

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3669]
There are still these references to the `OpTestHarness` that need to be removed:

* https://terascope.github.io/teraslice/docs/packages/teraslice-test-harness/overview#optestharness
* https://github.com/terascope/teraslice/blob/04497a7f0e03a13787b5bbde191ba61ff7f53ff7/packages/teraslice-test-harness/src/interfaces.ts#L22

The OpTestHarness was removed here:

https://github.com/terascope/teraslice/commit/ff1ad2eb40257789ce39422de02bd81ad8bb5955#diff-98464134439b6728e8f8934133e3fe5246b34ef9208908e3166323573a14ecd6

**Comment by busma13** [comment]
Also this: https://terascope.github.io/teraslice/docs/packages/teraslice-op-test-harness/overview
