### ISSUE TITLE
Add Asset/Teraslice Version Dependency Check on Asset Load

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3685]
Add the ability for an asset to state what versions of Teraslice it requires and Teraslice should use this to validate the asset against it's current version at the time the asset is uploaded.

Right now the `asset.json` file looks like this:

```json
{
    "name": "elasticsearch",
    "version": "4.0.0"
}
```

I propose we extend it with a `dependencies` property, like the `package.json` 

```json
{
    "name": "elasticsearch",
    "version": "4.0.0"
    "dependencies": {
        "teraslice": "^2.0.0"
   }
}
```

Other things to consider:

* Should the output of `/txt/assets` change (show incompatible versions)
* We could publish an asset registry as a json file in our docs and use it to render a compatibility chart

**Comment by kstaken** [comment]
This seems more akin to the `engines` setting in package.json rather than `dependencies`. You're defining what the minimum runtime environment needs to be which is more of an execution time dependency rather than a build time dependency.

**Comment by godber** [comment]
> This seems more akin to the engines setting in package.json rather than dependencies. You're defining what the minimum runtime environment needs to be which is more of an execution time dependency rather than a build time dependency.

Yeah, excellent observation.  I have no strong opinions on how the key is named and had only decided to mimic npm because I wanted to avoid inventing my own thing.  These are still things I consider open questions:

* What should we name the Teraslice version requirement property in the asset?
* Is there some reason we should mimic npm or even better, are there any arguments for not mimicking it?

**Comment by busma13** [comment]
Possible keys:
```
{
    "name": "elasticsearch",
    "version": "4.0.0",
    "needs": {
        "teraslice": "^2.0.0"
    },
    "requires": {
        "teraslice": "^2.0.0"
    },
    "minimum-versions": {
        "teraslice": "^2.0.0"
    },
    "minimum-teraslice-version": "^2.0.0"
}
```
