### ISSUE TITLE
Add earl jobs export that creates tjm file

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3695]
This `earl jobs ts-tmp1 <JOBID>` to a `file.json` that is compatible with `tjm`.

**Comment by busma13** [comment]
This seems similar to `earl jobs save`. We could default to saving in the `.teraslice` directory like it does and provide the same options if they are applicable.

**Comment by busma13** [comment]
If we want this command to be able to export multiple jobs, then it would be nice to have the file names come from some default, so the user doesn't have to provide a name for every file. This could simply be the `name` property from the job config. It could possibly be helpful to include the cluster alias and the date in the file name.

If we only want to support exporting one job file at a time we can simply pass the name we want as an argument to the command.

**Comment by busma13** [comment]
Current setup:
- job file saves to `~/.teraslice/export/<clusterAlias>/<jobConfig.name>.json` by default
- pass `--export-dir` flag to save to a different directory
- pass `--file-name` or `-f` to save under a different name
- if exporting multiple job files `file-name`s are assigned to `job_id`s based on their order
```
➜  teraslice git:(earl-tjm-export) ✗ earl jobs export local 382b41df-588e-4df6-ab0d-42f063a629f2 9988d547-aee3-4872-932b-b1a0c688f500 --export-dir ./config/test --file-name test382b.json test9988.json

➜  teraslice git:(earl-tjm-export) ✗ ls ./config/test
test382b.json test9988.json
```

**Comment by busma13** [comment]
TBD: 
- do we want to support passing `all` as a `job_id`? If so we would want to disable the `--file-name` option in that case.
- status option?
