### ISSUE TITLE
Retag service images from docker and put them in GHCR registry

### ISSUE THREAD

**Issue by sotojn** [terascope/teraslice#3713]
It was suggested that we move all services that we use (Kafka, Zookeeper, Elasticsearch, and Minio) from Docker Hub to our GHCR registry. This would resolve any potential issues with Docker Hub rate limits. The downside is that we would need to pull, retag, and push an image to GHCR whenever we want to add or update a version of a service. 

If we were to do this we could put each image in the respective repository thats associated with the asset. 
Ex: `ghcr.io/terascope/elasticsearch:7.9.3` and this should be visible in `elasticsearch-assets`

**Comment by godber** [comment]
Unless we continue to have an issue getting rate limited with docker hub I think the cost of doing this is pretty high.  So lets just keep this option in our back pocket but not implement for now.
