### ISSUE TITLE
Earl assets build on standard assets fails

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3725]
After updating terascope packages within standard assets to ESM versions I get the following error:
`Bundled asset failed to require: TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>`

It looks like within `packages/data-mate/src/index.ts` the cloning of `FieldTransform` and `RecordTransform` fail.

Steps to reproduce: 
- pull master branch of standard-assets (currently 1.0.0)
- run `yarn upgrade-interactive --latest` and update all teraslice libraries to their ESM versions
- run `yarn setup`
- run `teraslice-cli assets build`

**Comment by busma13** [comment]
`cloneDeep` calls this `object` function:
```
object(input: any): any {
        const descriptors = Object.getOwnPropertyDescriptors(input);
        // eslint-disable-next-line guard-for-in
        for (const key in descriptors) {
            descriptors[key].value = cloneDeep(descriptors[key].value);
        }
        return Object.create(
            Object.getPrototypeOf(input),
            descriptors
        );
    }
```

`input.key` before and after the recursive deepClone call within the for loop:
```
@@@@ before:  {
  get: [Function: decodeBase64],
  set: undefined,
  enumerable: true,
  configurable: false
}
@@@@ after:  {
  get: [Function: decodeBase64],
  set: undefined,
  enumerable: true,
  configurable: false,
  value: undefined
}
```

**Comment by busma13** [comment]
ESBuild creates this export function that is directly defining a getter:
```
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
```

**Comment by busma13** [comment]
The simplest way to fix this was to not use `cloneDeep` and instead copy over all properties of the imported objects.

**Comment by godber** [comment]
The MR above resolved this problem.
