### ISSUE TITLE
[teraslice] New Feature: Add new state "relocating" to execution controller status

### ISSUE THREAD

**Issue by sotojn** [terascope/teraslice#3762]
We've introduced a new feature in the `kubernetesV2` backend that allows for execution controller pods to be relocated in the event a pod is deleted or a `kubectl drain` is called in the node. The issue is that in the case on an `OOM` on the execution controller, we leave ourselves open to a `crashbackoffloop` because we check to see if the execution initializes in a `running` state.

https://github.com/terascope/teraslice/blob/500a0054db69335d1d58176671d7861c3db9c703/packages/teraslice/src/lib/workers/execution-controller/index.ts#L939-L960

We can fix this by adding a new state called `relocating` which we can set in the scenario we are expecting to relocate here.

https://github.com/terascope/teraslice/blob/500a0054db69335d1d58176671d7861c3db9c703/packages/teraslice/src/lib/workers/execution-controller/index.ts#L423-L439

We would need to make sure we handle this new state in all the cases that we have logic based around what state the execution controller is in.

**Comment by godber** [comment]
We may choose to do this in the future, but closing for now.
