### ISSUE TITLE
Expose execution status as virtual property on job resource - teraslice api

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#3770]
Would it make sense to expose the `ex._status` property as `.status` or perhaps `.exStatus` on the Teraslice job API resources?

I would expect this to be implemented by making a request to see if a current ex exists for the job, if so, return it's status, if not, return ... 🤷 

This would simplify a lot of client side logic.  I am not sure what the downsides would be.  The extra DB requests of course.  Anything else?

See also #535 , this is effectively a duplicate of that.

**Comment by busma13** [comment]
In teraslice-cli we give the job a registered status if there isn't an execution
```
export interface JobMetadata {
    id: string;
    api: Job;
    config: Teraslice.JobConfig;
    status: Teraslice.ExecutionStatus | RegisteredStatus;
}

export type RegisteredStatus = keyof typeof RegisteredStatusEnum;

export enum RegisteredStatusEnum {
    no_execution = 'no_execution'
}
```

**Comment by godber** [comment]
I talked with Kimbro about this a little bit today and he suggested if we chose to go this route we should probably make a distinction between this "virtual property" (if there's a word for this someone let me know) and the other properties.  That way if we start extending the use of this technique, they will all be grouped together.

So maybe something like

```json
"_ex": {
  "status": "running"
}
```

**Comment by godber** [comment]
This PR:

https://github.com/terascope/teraslice/pull/3792

only added the functionality to `/jobs/<JOB_ID>`.  We want it added to `/jobs` too ...
