### ISSUE TITLE
Set Node 22 as default version

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3771]
Node 22 has been tested for quite some time, but now we want to set it as the default.

Places where there is a default node version:
- `test.yml` - used by `verify-build`, `lint-and-sync` , `and e2e-external-storage-tests` jobs 
- `publish-master.yml`
- `publish-tag.yml`
- `Dockerfile` and `Dockerfile.dev`
- scripts `config.ts`
- teraslice-cli `asset-src.ts`

`@types/node` should be moved to 22, but the node engines setting should stay at 18

**Comment by godber** [comment]
#3773 probably closed this issue yeah?
