### ISSUE TITLE
queue retries

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#379]
This is a standing ticket to take notice possible duplications on retries. If there are queue overflows during a running job, and that job is terminated. It is possible that The slice will partially complete but the shutdown timeout would occur shutting down the worker, but the slice would be partially complete but on recovery, it would retry the whole thing thus leading to duplicate documents

**Comment by kstaken** [comment]
This is a note that needs to be added to the documentation. Our target delivery guarantee is "at least once" so the retries in that scenario are correct behavior.

**Comment by kstaken** [comment]
This expected behavior for at least once.
