### ISSUE TITLE
Review and refactor ts-scripts sync

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3825]
While working on #3823 I ran into an issue where sync assumes that we will be using a minor range(^), so `yarn sync` failed when it changed all the `~` back to `^`.

We at minimum need to convert `sync` to expect a patch range, but we have run into other problems with sync doing things we did not expect recently.
If we can review the code and determine what functionality is still needed, and it doesn't look to difficult to separate it out and discard the rest, that would be best.

**Comment by busma13** [comment]
After taking a look, we are going to remove `generateTSConfig` and `executeHook` from the `sync` command. The tsconfig is easy to update and executeHook is not used anywhere.

**Comment by godber** [comment]
Closed by #3831
