### ISSUE TITLE
point-in-polygon-hao dependency error

### ISSUE THREAD

**Issue by busma13** [terascope/teraslice#3850]
`point-in-polygon-hao` is a nested dependency of `utils`. Version 1.2.0 has a breaking change related to ESM and `require()`.
https://github.com/rowanwins/point-in-polygon-hao/issues/20

The yarn.locks in `teraslice` and our public assets are still on version 1.1.0, so there's no issue there.

The problem is that asset test workflows install `teraslice-cli`, which doesn't have a yarn.lock, and therefore installs version 1.2.0 of `point-in-polygon-hao`, which throws an error when trying to run any `teraslice-cli` command.

We have a PR that updates the `workflows` repo to add a resolution to the yarn global package.json, but it's messy:
https://github.com/terascope/workflows/pull/26, ref: https://github.com/terascope/teraslice/issues/3544

Instead we are going to try to use `esbuild` on the `teraslice-cli` and upload that artifact to npm.

**Comment by busma13** [comment]
The `point-in-polygon-hao` package has been fixed here: https://github.com/rowanwins/point-in-polygon-hao/pull/21. We will continue with the build step for teraslice-cli so this is never an issue again.

**Comment by godber** [comment]
Was this resolved?
