### ISSUE TITLE
Consolidate redundant boolean options on elasticsearch_index_selector into multi-value option

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#411]
There are options on the the `elasticsearch_index_selector` operator that I think are mutually exclusive, these include:

* delete
* upsert
* create
* update

Could these be replaced with a single `operation` option that allows the user to select one of the values?

https://github.com/terascope/teraslice/blob/master/docs/reference.md#elasticsearch_index_selector

**Comment by godber** [comment]
This doesn't really matter much but might resolve some ambiguities in the code.

**Comment by kstaken** [comment]
Yes this would probably help.

**Comment by kstaken** [comment]
This is a big breaking change but gets into the over complication of this particular processor. The processor likely needs to be refactored and broken up to reduce this complexity. The existing processor can be deprecated but kept around until all jobs have been converted.

**Comment by jsnoble** [comment]
migrated issue to elasticsearch-assets repo
