### ISSUE TITLE
processor testing improvements

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#425]
I think a small utility/framework/fixture can be implemented to improve and generalize the testing of processors.  The framework aspect of it would execute tests that should be common across all processors like:

```javascript
describe('properly defined processor', function() {
    it('has a schema and newProcessor method', function() {
        expect(processor).toBeDefined();
        expect(processor.newProcessor).toBeDefined();
        expect(processor.schema).toBeDefined();
        expect(typeof processor.newProcessor).toEqual('function');
        expect(typeof processor.schema).toEqual('function');
    });
});
```

The fixture aspect would provide skeleton `context`, `jobConfig`, and `jobConfig` objects that processors could use.  For that matter a common input `dataArray` containing data generator-like data and ES query result-like data could be shared.

**Comment by kstaken** [comment]
This has been implemented here: https://github.com/terascope/teraslice_op_test_harness
