### ISSUE TITLE
Problem loading custom processors

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#442]
The [regex used to append .js extension](https://github.com/terascope/teraslice/blob/9d0ad826904fb0f927f6196374584645b230c44f/lib/cluster/runners/op.js#L35) should be more specific.  In my case, I defined a processor named `read_json` which would not get the += '.js' love.  As a workaround, I can use `read_json.js` in my job spec.

**Comment by twkiel** [comment]
I may have inadvertently duped this with #466. If this is the same issue, mine should probably be nuked.

**Comment by jsnoble** [comment]
Could i get more clarification on this bug? Is this using assets or opPath? How do you have your code structured? For individual javascript files they must all have a `.js` suffix, that is just standard like markdown files have .md and any other language have their own suffix. You can specify a module format which has the name as a directory with an index.js file that you specify, (or it can be changed using the package.json) . In this case you would `require` the directory with the module name. 
```
/read_json
   node_modules/
   index.js
   package.json
or
read_json.js

```

Either way on the job operation you can just reference it as `_op: read_json`

**Comment by erik-stephens** [comment]
I don't have that example any more but I'm pretty sure it was in an asset and only defined as `read_json.js` (no sub-dir).  I think I confused the custom operations docs where the example shows `count.js` with the asset docs.  It might simplify things a bit to require the opPath case to have same structure as assets.
