### ISSUE TITLE
full_response:true required even when not reading from elasticsearch

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#444]
Unable [to submit jobs with `preserve_id:true`](https://github.com/terascope/teraslice/blob/8d4ad2cece967c864fb770d335c18f82fe0cb767/lib/processors/elasticsearch_index_selector.js#L320):

```
{
    "error": 500,
    "message": "Job submission failed: Error validating job: Error: elasticsearch_index_selector was set to preserve_id but full_response on readers was not set to true"
}
```

**Comment by kstaken** [comment]
This is an issue with the cross processor validation making incorrect assumptions about how they're going to be used. We need to back out this cross processor validation mechanism as it's not allowing jobs to be properly composable.
