### ISSUE TITLE
Preferred way to reference assets?

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#447]
Word on the street is that jobs can refer to assets by name instead of hash, but I can't find details about that in either the api or ops documentation.  Looks like [assets are looked up by id](https://github.com/terascope/teraslice/blob/236ba2918098688fda022223f58c1b731cd3e52b/lib/cluster/runners/op.js#L59) and the [asset id can only ever be the hash](https://github.com/terascope/teraslice/blob/236ba2918098688fda022223f58c1b731cd3e52b/lib/cluster/storage/assets.js#L25).

**Comment by kstaken** [comment]
Here's an example job.

```
{
    "name": "bt-clients import first pass",
    "lifecycle": "persistent",
    "workers": 3,
    "assets": ["common_processors", "bt_processors"],
    "operations": [
        {
            "_op": "teraslice_kafka_reader",
            "topic": "incoming-bt",
            "connection": "kafka_gen1",
            "group": "bt-clients-import-r3",
            "size": 100000,
            "wait": 30000
        },
        {
            "_op": "protocol"
        },
        {
            "_op": "clients_prep"
        },
        {
            "_op": "elasticsearch_index_selector",
            "index": "clients-v2",
            "type": "client",
            "create": true,
            "id_field": "_id"
        },
        {
            "_op": "drop_id"
        },
        {
            "_op": "elasticsearch_bulk",
            "size": 10000,
            "connection": "es_rc1"
        }
    ]
}

```

**Comment by erik-stephens** [comment]
I should've been more clear and said assets created via the asset api.  All I have is the asset id (hash).  Unsure if user error or a gap in the asset api functionality.

**Comment by godber** [comment]
The `name` you set in your `assets.json` can be used to reference your asset in the same way the hash returned by the API.

**Comment by kstaken** [comment]
asset.json supports `name`, `version` and `description` fields. 

You can look at /txt/assets to see what exists.

**Comment by erik-stephens** [comment]
I tried by name first against my local teraslice instance.  Can't duplicate now so must've been user error.  I might've confused the asset name with the op name.
