### ISSUE TITLE
Validate job connections on job submission

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#451]
It doesn't appear that connections are tested when a job is submitted.  So if you fat finger a connection name you end up with failed slices.  It should be possible to validate all connections at job submission time.

**Comment by godber** [comment]
Note to self, this just bit us again.

**Comment by erik-stephens** [comment]
Going to follow the moderator's validation lead here.  One difference is that moderators has the shape {connection_type: connection_name} while operations only has the shape connection_name.  Spoke with @jsnoble and we agreed that a good first crack at this is to look for the operation's connection in *all* terafoundation connection types and throw an error if nothing found.  That should handle the most common cases.  It will not handle the following cases:

- The operation's connection is `default` and only another connection type in the terafoundation config has `default` defined.  That might better be enforced in terafoundation anyway.

- The operation's connection is `foo` for connection type `bar` but the terafoundation config only has a `foo` connection defined for another connection type `baz`.

Addressing those cases will require more painful changes.

**Comment by kstaken** [comment]
Yeah, this is going to be almost impossible to do right without actually running the job. As you've found each _op will use connections in a different way and the only way to know what it requires is to look in the code.

**Comment by godber** [comment]
My intent was just to catch cases where `connection` parameters provided by the jobs simply didn't match those found in the terafoundation config.  Nothing more.
