### ISSUE TITLE
Job does not see updated asset

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#452]
While iterating through some issues with my asset code, I tried:

1. stop job
1. update asset
1. restart job

but the job looks to be referencing old version.  Even though I'm referencing asset by name, the `job.assets` field is the hash id.

```
grep assets test.json
    "assets": ["test"],

curl -X POST localhost:5678/jobs -d@test.json
{
    "ex_id": "1c806045-e2fc-4e7e-b87f-9e2737afeb7e",
    "job_id": "a80c21fa-6cc3-4bee-96d8-af2533032ae8"
}

curl -s localhost:9200/erik__jobs/job/a80c21fa-6cc3-4bee-96d8-af2533032ae8 | jq ._source.assets
[
  "053f0cc52c9974cabe1e1f7caa484c8339034a6d"
]
```

**Comment by godber** [comment]
I bet if you resubmit the job it's fine.

**Comment by jsnoble** [comment]
Im not totally sure what your curl is doing at the end, but once a job is submitted all assets are converted to the hash id as that is the true reference for the asset and its were the asset is saved on disk. The only question is whether that returned hash is the id for the old asset or for the new asset. If this is the old asset then we have a problem, if not then this works as expected and we can close this ticket

**Comment by erik-stephens** [comment]
Sorry, my snippets don't paint the whole picture.  I'll try to reproduce & post better snippets.

**Comment by kstaken** [comment]
This should be fixed.
