### ISSUE TITLE
Handle out-of-range documents in index selector op

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#456]
With a timeseries index selector, there is potential to create unintended indices when data source contains bad data.  Would be nice to specify a valid range in relative terms (eg ["-1 year", "+1 month"]) and specify the index to ship such documents to (eg "errors").

If decide to include something like this, then should consider breaking index selector into two processors, one for time series and one for not.

**Comment by erik-stephens** [comment]
Maybe we should bump the priority.

**Comment by jsnoble** [comment]
migrated issue to elasticsearch-assets repo
