### ISSUE TITLE
Cleanup job states on cluster restart

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#458]
Currently if there are jobs running and something like a cluster restart occurs the jobs get left labeled as 'running'. We may want to add another state `terminated` that indicates that an execution context was ended outside of a users request. If there was a restart then any jobs labeled as running that aren't really running should be marked as `terminated` as part of the startup process for the cluster.

**Comment by godber** [comment]
Should this apply to jobs in the `failing` state too?

**Comment by kstaken** [comment]
Yeah probably but then the question is do jobs in `failing` state move to `failed` or to `terminated`

**Comment by erik-stephens** [comment]
Either one could make sense and since cluster restarts should be so rare, it probably won't be too impactful which we choose.  I vote `terminated` since `failed` should be a hint for user to investigate before resubmitting/restarting jobs.

**Comment by jsnoble** [comment]
#470

**Comment by kstaken** [comment]
In theory this was fixed in #470.
