### ISSUE TITLE
Events for _op processing

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#460]
With the kafka stuff there are two different scenarios that have cropped up where the reader needs to hook into the process.

  1. When a job stops the kafka reader needs to be able to receive notification of that so it can stop waiting for data and immediately complete the slice and the process can exit.
  2. When the job is running the kafka reader currently moves the offset as the data is read. What needs to happen in that case is that the reader needs to read the data but the offset shouldn't move until the slice has been successfully processed. This requires an event at the end of the slice.

These are just a couple concrete examples though. There will be others so I want to outline what we think the reasonable events might be. From the two use cases above I see:

 * job:stopped or job:stopping
 * slice:success <- only triggered on success
 * slice:failure <- only triggered on failure
 * slice:finalize <- always called when a slice is complete regardless of outcome.

So what other scenarios make sense?

Maybe
 * job:paused
 * job:resume
 
Other slice states?

**Comment by jsnoble** [comment]
others that might be good are:
network:error
network:disconnect  // these three deal with worker connection to slicer
network:connect

worker:shutdown  //its similar to job:stopped but slighty different as well

from slicer standpoint:
worker:slice:complete  
network:disconnect  // could be useful if we know what slice was sent to a given worker

slicer:processing:error  // internal slicer error, needed for cleanup
slicer:job:finished

**Comment by jsnoble** [comment]
events listed in preliminary pr:
for slicer:
- job:pause
- job:resume
- job:stop
- job:finished
- slice:failure
- slice:success
- network:disconnect

for worker:
- network:error
- network:disconnect
- slice:success
- slice:failure
- slice:finalize
- worker:shutdown
