### ISSUE TITLE
Teraslice should warn or fail if its state indices have the wrong mappings

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#463]
When upgrading teraslice it is possible that the new version of teraslice will require new mappings on some of its support indices.  Right now, teraslice will continue to function even with bad mappings.  It should check the mappings and either warn the user or fail to start completely.

**Comment by godber** [comment]
Perhaps users can be warned of errors at job submission time.

**Comment by kstaken** [comment]
This appears to be resolved.
