### ISSUE TITLE
Expose version & some configuration details via api

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#465]
As an operator of teraslice, would be nice to be able to easily query the version and location of storage via the api.  Endpoint isn't import but some ideas: /about or even the root page ala elasticsearch.

**Comment by jsnoble** [comment]
Im not sure what you mean by location of storage, do you mean if writiing to a file what the file path is, or if sending to elasticsearch then the index? as for the version, its being listed in /cluster/state. Each node lists what version of teraslice it is using

**Comment by godber** [comment]
I think Erik means which ES server stores the state and other indices, probably should provide those index names too.

Ah, yes, @erik-stephens look at `/cluster/state` it shows the version https://github.com/terascope/teraslice/blob/master/docs/api.md#get-clusterstate

Thanks Jared.

**Comment by godber** [comment]
Is is a requirement that all members of a teraslice cluster have the same nodejs and teraslice versions?  If so is this enforced in any way?

**Comment by godber** [comment]
Actually, I think what we need is a `/cluster/config` endpoint that provides access to some, if not all, of the `terafoundation.yaml` information.  Without this, we end up building operational solutions that require access to that file, which ends up being a lot of hoop jumping.

**Comment by godber** [comment]
I am just killing this discussion for now.  There are likely to be much broader changes to the configuration mechanisms of teraslice that would render this moot anyway.  Everyone is aware of the needs and risks of this.
