### ISSUE TITLE
Add time filters to /jobs api endpoint

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#471]
Add `from` & `to` options that accept whatever `moment()` accepts as well as relative times (eg now-1d).  Outstanding questions:

- Defaults?  `to=now` and `from=now-1d`?

- Which timestamp?  _created or _updated?  Probably _updated.  Which entity, the job or the job's last or active execution?

**Comment by kstaken** [comment]
This has not proven to be needed.
