### ISSUE TITLE
Integration test should timeout on wait on container startup

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#488]
Right now the integration test framework will wait indefinitely for the containers to startup.  It should timeout after waiting 60 seconds (?? unsure) or 50 iterations (more sure).

After timing out the suite should exit, leaving the containers in whatever state they were in and print an error that indicates which container timed out and suggest the user use `docker-compose logs` to see why the container is not starting correctly:

```
ERROR: Timeout - The integrationtests_elasticsearch_1 container failed to start.

You can use the following command to investigate the issue:

  docker-compose logs
```

A current startup looks like this, 16 iterations for ES startup and 4 iterations for TS startup:

```
 - Waiting for Elasticsearch to be ready
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
 - Waiting for Teraslice to be ready
    - still waiting...
    - still waiting...
    - still waiting...
    - still waiting...
```

**Comment by erik-stephens** [comment]
Was closed in PR #491
