### ISSUE TITLE
Implement script example

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#494]
Teraslice includes a basic external script interface, it should have an example in the `examples/` directory.

https://github.com/terascope/teraslice/blob/master/docs/ops-reference.md#script

I will try and think of a meaningful example, but if anyone else thinks of one in the meantime feel free to share.

**Comment by kstaken** [comment]
This is being addressed in #503

**Comment by kstaken** [comment]
@jeffmontagna can this be closed?

**Comment by jeffmontagna** [comment]
yes

**Comment by kstaken** [comment]
Resolved in #503
