### ISSUE TITLE
Release Process Proposal

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#506]
An option for handling releases is to fully automate the process of releasing using the Semantic Release package:

https://github.com/semantic-release/semantic-release

I have done this with my teraslice-top package as an experiment:

* https://github.com/godber/teraslice-top

This method is a little strange in that any commit or merge on the master branch will result in a release automatically being created on GitHub and NPM.  It also relies on structured commit messages to automatically infer what part of the semantic version get updated.  It relieves you from having to think about version numbers at all during the development process.  You can manage your **stable** releases using npm's built in `dist-tag` functionality.  This controls what package is installed by default.  It allows us to make as many `dev` builds as we want but when people do an npm install, they still get the version tagged with `latest`.

One possible drawback, other than the various mess created by so many releases, is that the whole process is very automated and we trust our github and travis credentials to the script.

**Comment by erik-stephens** [comment]
Never used it but looks promising.  If the number of releases is a concern, we can add more branches (eg dev) and reserve the semantic-release build task for more special branches.

**Comment by godber** [comment]
Semantic release can be configured to trigger off of a branch other than `master`.

**Comment by godber** [comment]
I have been doing a manual release process.  We can punt on anything more formal now.
