### ISSUE TITLE
Integration tests should auto-discover new test cases

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#512]
I tried to add a test this morning ... I had to wait 10 minutes to find out that the framework lacks the flexibility to add tests ... mostly due to these lines I suspect

```
    require('./cases/data/id-reader')();
    require('./cases/data/elasticsearch-bulk')();
    require('./cases/data/reindex')();
    require('./cases/cluster/worker-allocation')();
    require('./cases/cluster/state')();
    require('./cases/validation/job')();
```

https://github.com/terascope/teraslice/blob/v0.12.0/integration-tests/spec/setup.js#L180-L185

**Comment by erik-stephens** [comment]
That's a side-effect of the global setup we do and lack of global setup support in jasmine.  There's `beforeAll()` but that will run before each `describe` block.  We could make the global setup idempotent and add that to a a top level beforeAll, but that will slow the tests down.  Perhaps can be accomplished with a jasmine helper.  Or, we could walk ./cases and require whatever we find.  Or, maybe another test runner has that functionality.

**Comment by jsnoble** [comment]
This has been addressed in the new testing additions that @peterdemartini has made in the framework
