### ISSUE TITLE
Unable to update job.workers

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#533]
```
$ grep workers some-job.json
    "workers": 2,
    "recycle_workers": 1000,

$ http PUT gen1:5678/jobs/12977f33-7688-4d3e-bbb8-58e7db3fc9d4 < some-job.json

$ http gen1:5678/jobs/12977f33-7688-4d3e-bbb8-58e7db3fc9d4 | jq '._updated, .workers'
"2017-09-08T23:33:24.962Z"
1
```

**Comment by godber** [comment]
I'd think an integration test could be written to test this case.

**Comment by godber** [comment]
Passes integration tests with the recently merge client changes:

![screen shot 2017-09-13 at 1 26 34 pm](https://user-images.githubusercontent.com/1249/30399244-ed338168-9887-11e7-8028-0ef3973a4d8b.png)
