### ISSUE TITLE
Testing failure modes

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#534]
Saw this [pumba](https://github.com/gaia-adm/pumba) tool in my news feed and thought would be good to help test failure modes.  To make this actionable, write an integration test that simulates a network partition between X & Y.  What X & Y would be most valuable to test right now?  slicer & cluster master?  slicer & worker?

**Comment by godber** [comment]
I think @peterdemartini worked with this in a branch somewhere.  Still a good suggestion eventually.

**Comment by kstaken** [comment]
Internal testing frameworks are covering validation testing.
