### ISSUE TITLE
Rename op & post_validation

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#540]
The functions `op_validation` and `post_validation` are defined as part the processor API but are inconsistently named. This should be fixed before they become wide used. The should be named `opValidation` and `postValidation` although is there a more descriptive name that can be used for `opValidation` it's not clear to me what that does?

**Comment by jsnoble** [comment]
Leaving this as a note:
- Schema: it constrains the basic form of the config, and the type of values it can have
- opValidation: this performs a validation check on its own op to make sure there are no conflicting settings within itself
- postValidation: this allows for cross of ops/job to make sure there are no conflicting settings across the entire job. ie kafka_reader to be a persistent job, preserve_id in index_selector to be pair with full_response in elasticsearch_reader

**Comment by kstaken** [comment]
Proposed names: `selfValidation` and `crossValidation`.
