### ISSUE TITLE
long running jobs get marked failed on the last slice

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#576]
We've been running some id_reader jobs that run for about 24 hours and then get marked `failed` on the final slice when the job is completed. They're in `running` up to the end and there aren't any `error` slices so it seems to be some kind of issue that occurs as the job is finishing. Not entirely sure this is reader related but seems likely since the rest of the job is pretty normal stuff.

**Comment by godber** [comment]
Can you give us an idea what options are used on the `id_reader` in these cases?

**Comment by jsnoble** [comment]
i have run id_reader jobs several times, some short some a bit longer (5 million index) and I cant seem to duplicate this issue. Could we get any additional info like the actual job that you posted?

**Comment by kstaken** [comment]
I've seen an occurrence of this on a non id_reader job now. Simple straightforward ES reindexing job. Appears to run through with no errors but ends in this failure state.

```
"_failureReason": "Slicer for ex_id: 78c1cd54-bd77-48d3-89e0-948c4a758310 runtime error led to a restart, terminating job with failed status, please use the recover api to return slicer to a consistent state"
```

Logs for the slicer show:

```
all work for job: 78c1cd54-bd77-48d3-89e0-948c4a758310 has completed, starting cleanup
```

And then logs for the jobs_service show:

```
job 78c1cd54-bd77-48d3-89e0-948c4a758310 has failed to complete
```

Something I noticed is that the ex record gets marked as failed with the failureReason but does not have the slicer stats included even though the slicer appeared to complete.

**Comment by kstaken** [comment]
One other possible clue on this, this failure occurred on a 3 node cluster. The exact same job run on a single node cluster completed without issue.

**Comment by kstaken** [comment]
Appears to be hitting this case in the slicer: https://github.com/terascope/teraslice/blob/master/lib/cluster/slicer.js#L326
