### ISSUE TITLE
Restart workers when total memory out of control

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#581]
In the spirit of `recycle_worker` functionality, let's restart workers when `process.memoryUsage().rss` "goes to 11".  We've seen spikes in memory that ramp up before recycle_worker hits.  This form of failure is especially painful in that it requires `kill -9`'s, assuming you're lucky enough to be able to issue the kill command without an OOM exception.

**Comment by kstaken** [comment]
I think this is something that should ultimately be handled by the cluster manager.

**Comment by kstaken** [comment]
No, should be handled based on the memory restrictions.
