### ISSUE TITLE
Repeatedly crashing workers is not detected as a failure

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#599]
If a worker gets into a state where it crashes repeatedly the slices are not marked as `error` and the job continues in running status even though the workers continuously crash. One case where this occurs is if you hit a code path where there is a runtime error in the code on the worker, i.e. hitting an undefined variable or something. The worker crashes and restarts but no error is detected. The error does seem to be caught at the terafoundation level as we do get a log entry but Teraslice isn't handling this in a manageable way.

**Comment by jsnoble** [comment]
This was determined to be an issue with the way hdfs sends back error messages. The message in the error would contain the entire data set that was sent. These data sets were up to 100k docs. The quickly repeating of the docs would overwhelm the worker process and crash it. To solve this issue we decided to make the error parser truncate the error message if its over 5k chars. https://github.com/terascope/error_parser/pull/1
