### ISSUE TITLE
Workers don't stop in all cases

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#605]
We've been seeing various cases where workers are getting orphaned on the cluster. They still show up in /txt/workers but the slicer for the job will be gone and the workers are left doing nothing. Sometimes this corresponds with a timeout on the stop request but I don't think that always happens.

The most recent case when this occurred the workers were in a crash cycle due to a bug in the HDFS library. First call to _stop got stuck and eventually returned an empty response. Second call to _stop returned with success almost immediately but not all workers were stopped.

This is not the only scenario where it occurs though. The node master is going to need to be more aggressive about watching the workers and making sure they get stopped when required. Including using `kill -9` if necessary.

**Comment by godber** [comment]
Another case where we have lingering workers is when there is some disruption that kills the slicer, usually the job ends up in failed state but workers remain.

I've been asking myself for a few weeks now if the master should have a reaper process that checks for workers with ex_ids that don't have running slicers.
