### ISSUE TITLE
Set the process title for all of the teraslice processes

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#617]
If no one has any objections (like hiding the path to the config file) perhaps we should set the process title of the processes spawned by teraslice.  Right now the processes look like this:

```
root     28564  2.1  0.7 1282948 117612 ?      Sl   09:18   0:07 /usr/local/bin/node /app/source/service.js -c /app/config/processor-master.yaml
root     28570  0.3  0.5 1228960 84512 ?       Sl   09:18   0:01 /usr/local/bin/node /app/source/service.js -c /app/config/processor-master.yaml
root     29459 65.0  3.5 1717396 579316 ?      Sl   09:20   3:07 /usr/local/bin/node /app/source/service.js -c /app/config/processor-worker.yaml
root     29465  0.5  0.6 1247524 105760 ?      Sl   09:20   0:01 /usr/local/bin/node /app/source/service.js -c /app/config/processor-worker.yaml
```

From that output we can't tell what's a slicer or what `ex_id` it is or anything like that.  I am not quite sure what each spawned process should say.  Maybe we should start of by proposing a list of possibilities.

See:
https://nodejs.org/dist/latest-v4.x/docs/api/process.html#process_process_title

**Comment by jsnoble** [comment]
@peterdemartini going through tickets and I see this might be helpful for debug testing and the like

**Comment by kstaken** [comment]
not really needed since we're focusing on K8s
