### ISSUE TITLE
Clean up logging

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#619]
Example [pulled from here](https://github.com/terascope/teraslice/blob/a5e15b0602af2581eba67a342fbbc238d6121ade/lib/cluster/slicer.js#L185):

    logger.error(`worker: ${workerId} has error on slice: ${JSON.stringify(sliceData)} , slicer: ${exId}`);

is better written as something like the following to maintain the structured logging:

    logger.error(Object.assign({worker: workerId, slicer: exId}, sliceData), 'error on slice');

**Comment by peterdemartini** [comment]
This should be addressed in the latest version of the teraslice
