### ISSUE TITLE
move retries to slicer

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#623]
After discussing with kimbro we decided that retries should happen from the slicer lever. However this change needs to happen after moving kafka to work in the slicer as well

**Comment by kstaken** [comment]
We've now also discussed having per _op retries to avoid having to retry full slices in some scenarios. It's likely both would be required as slicer controlled retries would still be necessary to handle complete failures of workers.

If we implement per _op retries we should track in analytics on a per op basis if retries occur. For slices it should be tracked as part of the state record.

**Comment by kstaken** [comment]
At this stage it appears per op retries is the preferred path forward. Closing this.
