### ISSUE TITLE
Assets doesn't handle version correctly

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#639]
It doesn't consider 0.0.11 or 0.0.12 to be greater than 0.0.10

**Comment by godber** [comment]
If you're not using something like [semver](https://www.npmjs.com/package/semver) you should probably consider it.

**Comment by kstaken** [comment]
It's possible this issue may not be the version but I'm definitely seeing cases where a new version of an asset is published but a stored job continues to use an older version. It appears that maybe the validation on creation of the new execution isn't working correctly.
 
Just has this situation with an asset versioned 0.0.2 and then 0.0.3 was published. The job was stopped and started but continued with the older asset. The stored job has the old asset_id as an explicit ID. 

Something that occurs to me is that this job was updated via PUT. Doing that again I see the stored job gets the correct asset_id for 0.0.3 but it's storing the asset_id in the job instead of leaving it as the name. With that the execution will always use the old version because the asset_id will never change. I think this ties in with @godber's comments in #634. The job should be stored as submitted, not as validated.

**Comment by kstaken** [comment]
This should be resolved with the fixes for #634 in v0.28.0.

**Comment by kstaken** [comment]
This issue isn't fixed. Updating existing jobs still converts asset names into IDs.

**Comment by kstaken** [comment]
Closing to defer to #634 which is more specific.
