### ISSUE TITLE
Slicer count missing from /txt/jobs output

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#644]
Now that the job is not expanded with the defaults from this: https://github.com/terascope/teraslice/pull/642 it doesn't contain `slicers` which is apparent from the output of the `/txt/jobs` api endpoint.  The example below shows a new job and then an old job:

```
job_id                                name     lifecycle   slicers  workers  _created                  _updated
------------------------------------  -------  ----------  -------  -------  ------------------------  ------------------------
7b7cc4e4-6240-426a-8996-992c4dc14226  foo      persistent           30       2018-01-10T23:46:16.836Z  2018-01-10T23:46:16.836Z
e6045322-0ec6-47c0-a599-7d9253ffe222  bar      persistent  1        30       2018-01-09T20:57:50.622Z  2018-01-10T22:05:49.853Z
```

The way this works is that `jobs` is passed into a utility called `makeTable` to generate the table here:

https://github.com/terascope/teraslice/blob/v0.28.0/lib/cluster/services/api.js#L423

I guess this can be resolve by merging `executionService` with `jobsService` prior to passing to `makeTable` or we could just remove the `slicers` column, which might be more appropriate since this value is already reported by `/txt/ex` where the information is actually stored.

**Comment by kstaken** [comment]
This doesn't seem like a problem to me since it's showing information about the job as submitted. Since you're viewing the job record and the record doesn't specify the field it makes sense that the field would be empty. Defaults are applied when the execution is created and would show up in that record which also seems consistent.

**Comment by godber** [comment]
I'd remove the column from that view in this case, otherwise we're stuck explaining why it's missing to curious users from here to eternity.

**Comment by peterdemartini** [comment]
I agree with @godber I think removing the column would make the most sense.

However, I think there is value in adding another endpoint that lists all active jobs and a summary of their "lastest execution" stats.

**Comment by kstaken** [comment]
Isn't that what /txt/controllers does?

**Comment by peterdemartini** [comment]
Umm, yes. Disregard that suggestion then
