### ISSUE TITLE
Offset storage mechanism for new kafka reader

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#647]
The new kafka slicer will need to know the offsets that the worker consumed up to.  There needs to be a way for the worker to communicate that back to the slicer.  Does such a mechanism already exist?  Chatted with @jsnoble and he didn't think so.

**Comment by kstaken** [comment]
We need a solution for storing offsets for the new kafka reader. 

I think there are a couple possible solutions.

1. store the committed offsets in the state record. On the surface this is good however state records are associated with a particular execution so stopping / restarting a job would result in offsets being lost. It would require a job `_recover` to restore it and that is not really viable operationally. Positive attributes though is that this does bring the ability to run once jobs and to recover offsets.
1. Use a general state storage mechanism to store the offsets. This would build on the general state storage mechanism that we've been discussing to store the offsets in external storage (likely ES). Using this approach the job could recover automatically but you lose the recover benefits of storing explicit offsets.
1. Maybe a combination of both mechanisms. Downside is that these will not be atomic update operations so the risk of inconsistency will be high.

**Comment by jsnoble** [comment]
migrated to kafka-assets repo
