### ISSUE TITLE
slicer secondary slice update functionality

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#649]
An issue arises when a worker crashes that it is possible that the state for the given slice is left in started state since the worker loses any reference to the slice. We should have the slicer be a backup to update the individual slice if worker fails. 

Current idea: 
- Have the worker have the same process restart check that slicer utilizes and send a flag on the network:connect' event, worker:ready message.
- Slicer needs to keep track of what slice was sent where
- Slicer on receiving flag updates slice state to failed or send else where

**Comment by jsnoble** [comment]
@peterdemartini is this still an issue with the refactored changes?

**Comment by peterdemartini** [comment]
This is still an issue

**Comment by kstaken** [comment]
@peterdemartini thinks this shouldn't matter now.
