### ISSUE TITLE
Improve monitoring inter-op

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#656]
Some monitoring system gaps:

- There is no dedicated health endpoint.  We have `/cluster/state` which could be a bit too heavy for a simple health check.  We have `/cluster/stats` which is a bit too low-level for a health check.

- There is some "filling in the blanks" for cluster-level attributes (eg version, status).  We have some useful attributes in `/cluster/state` but they are specific to the role.

Let's define a `/` endpoint similar to elasticsearch's.  Can be pretty bare to start and fleshed out more as we choose how best to report things like version, status, etc.

**Comment by kstaken** [comment]
This has been added.
