### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#678]
We're really bad about updating dependencies and things are really falling behind. 

Anyone have any experience with Greenkeeper? https://greenkeeper.io/#how-it-works

**Comment by godber** [comment]
I think I've seen projects use it ... and ignore the PRs which I found annoying.  I think if we have confidence in our testsuite and are willing to accept it's MRs then it's not a bad idea.

Looks like lodash is successful in using it: https://github.com/lodash/lodash/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+greenkeeper though the MRs seemed to stop a while ago.

**Comment by peterdemartini** [comment]
I have used greenkeeper in the past, and constant the pull requests can be annoying. However, I think using it automatically verify the dependencies are up-to-date when submitting, and updating, a pull request will be a more natural workflow.

**Comment by peterdemartini** [comment]
I think doing this in an automated fashion would be annoying and could be potentially dangerous. I think manually upgrading the packages when we submit PRs is the safest. I am going to close this issue.
