### ISSUE TITLE
id slicer will not work with elasticsearch 6

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#687]
They are depreciating how _uid operates in this version, and it starting to use a _id search instead which only allows for simple queries like term searches. This will also affect our elasticsearch_reader if we use the capability to further split a time segment further down.

docs:
 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-uid-field.html
 https://www.elastic.co/guide/en/elasticsearch/reference/6.2/mapping-id-field.html

for that last one pay attention to the note posted towards the top of the page and the paragraph just past it.

**Comment by kstaken** [comment]
My interpretation of this is that they have now made the `_id` field directly searchable which is actually a good thing as this will eventually allow the removal of the requirement to specify the type. The docs say that _id is available in various query contexts so I'm not sure that this is broken beyond requiring special casing for ES 6.

**Comment by jsnoble** [comment]
note to run intergration tests on v6 of elasticsearch

**Comment by jsnoble** [comment]
have doc in index with "_id":"rW_PZ2IBxDTJSO59gQq0"
    These following query failed. Some threw an error while others just returned an empty array

    {"index":"test_index","size":10,"body":{"query":{"bool":{"must":[{"wildcard":{"_uid":"events#r*"}}]}}}}
    {"index":"test_index","size":10,"body":{"query":{"bool":{"must":[{"wildcard":{"_uid":"r*"}}]}}}}   => bad query error
    {"index":"test_index","size":10,"body":{"query":{"bool":{"must":[{"wildcard":{"_id":"r*"}}]}}}};
    {"index":"test_index","size":10,"body":{"query":{"bool":{"must":[{"wildcard":{"_id":"events#r*"}}]}}}};
    {"index": "test_index", "size": 10, "body": {"query": {"ids" : {"type" : "events", "values" : ["r*"]}}}}

    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"default_field" : "_id", "query" : "r*"}}}  => bad query
    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"default_field" : "_uid", "query" : "r*"}}}  => bad query

    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"query" : "_uid:r*"}}}
    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"query" : "_uid:events#r*"}}}
    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"query" : "_id:events#r*"}}}
    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"query" : "_id:r*"}}}

    "index": "test_index", "size": 10, "body": {"query": {"query_string" : {"query" : "_id:/r*"}}} has the/ after the *


Works

    {"index": "test_index", "size": 10, "body": {"query": {"terms": {"_uid": ["events#rW_PZ2IBxDTJSO59gQq0"]}}}

**Comment by kstaken** [comment]
This appears to be the root of the problem: https://github.com/elastic/elasticsearch/issues/18154

And where they decided to not worry about what this breaks: https://github.com/elastic/elasticsearch/issues/24247

**Comment by kstaken** [comment]
Just so that we maintain an option for working in this regard we may need to look at sliced scroll queries and evaluate just how much risk there is from the state held server side on active indices.  https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

Also if this were applied as a subslicing technique for further division of an indivisible date range query, the impact of the state held server side would be relatively small and not held for the entire duration of a reader operation. It would only have to be held for the duration of the subslicing.

In cases where an index is `static` using the scroll API should be perfectly fine so it may still give us a reasonable set of options for when range slicing doesn't work.

**Comment by jsnoble** [comment]
migrated issue to elasticsearch-assets repo
