### ISSUE TITLE
recovery changes

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#705]
After discussing with @kstaken and @ciorg we decided to move recovery to /ex. We should provide a hint from the /job side to use the execution. add behavior to just recover and not pick up afterwards. ex/exid/_recover?cleanup=errors || all. Using cleanup implicitly does not restart where it left off.

**Comment by godber** [comment]
So it will look like this:

* `ex/exid/_recover` - redo failed and uncompleted slices then continue job
* `ex/exid/_recover?cleanup=errors` - redo failed slices then stop
* `ex/exid/_recover?cleanup=all` - redo failed and uncompleted slices then stop
