### ISSUE TITLE
Slices aren't failing correctly

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#715]
It appears in build 0.36.0 that slices no longer get marked as `error`. They appear to be left in `started` status. Looking in the logs for the job showing this shows many `mapper_parsing_exception` errors coming from ES which previously would have failed the slice.

I suspect something in #707

**Comment by godber** [comment]
We should get a test that exposes this.

**Comment by peterdemartini** [comment]
I was unable to replicate this issue. However, we found a potential problem where workers are double assigned slices, which could explain why slices aren't being marked as `completed`.

**Comment by godber** [comment]
> I was unable to replicate this issue. However, we found a potential problem where workers are double assigned slices, which could explain why slices aren't being marked as completed.

Did the fix for this make it into one of these `0.36.?` releases (https://github.com/terascope/teraslice/releases)?

**Comment by kstaken** [comment]
It looks like this has been resolved.
