### ISSUE TITLE
id_reader doesn't appear to correctly handle keys that begin with dash or underscore

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#734]
We've been trying to run a job with the id_reader and there was some data that it refused to process. We found one common attribute of the records it was ignoring is that all keys start with either `-` or `_`.

This is on a node:8 build. @ciorg is testing the same job on a node:4 build.

**Comment by kstaken** [comment]
@ciorg has confirmed this behavior also exists on node:4 so this is not related to the node:8 build.

**Comment by peterdemartini** [comment]
@kstaken @ciorg I can't replicate this issue, https://github.com/terascope/teraslice/blob/id-reader/integration-tests/spec/cases/data/id-reader.js#L103-L173. Is there something I should change?

**Comment by kstaken** [comment]
The problem keys would look something like `-xGd6iDGdlOH7AuqmVq-uj` or `_xGd6iDGdlOH7AuqmVq-uj`. Is that what you're testing?

**Comment by peterdemartini** [comment]
Basically the id is a 15 character string made up of any assortment of the following characters, `agnrz-_-_ `

**Comment by kstaken** [comment]
It's conceivable maybe this is something in elasticsearch's handling of key searches or maybe the assessment is just incorrect. It was the only common element of the missed records that kind of jumped out.

**Comment by peterdemartini** [comment]
It’s possible, but I’d like try and see if we can replicate it in this integration test

**Comment by godber** [comment]
@peterdemartini were you able to replicate this like you wanted?

**Comment by peterdemartini** [comment]
I was not able to replicate it, it appeared to handle the characters appropriately. I did not test using a query which could be changing the behavior

**Comment by jsnoble** [comment]
cannot reproduce and we have not seen this issue since
