### ISSUE TITLE
integration test feature regression

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice#741]
We used to be able to use sym linked libraries to be used in the integration test. This is an important feature to test functionality and development. In my node_modules I have terafoundation sym linked but when I run my integration tests it flat out fails telling me that `Error: Cannot find module 'terafoundation`.

**Comment by peterdemartini** [comment]
I have a fix for that in `https://github.com/terascope/teraslice/tree/choas-integration-tests`

**Comment by jsnoble** [comment]
If a test fails, there is no way to check elasticsearch or teraslice as they are immediately shut down after the test finishes. We might need a flag or something to determine how this is run. This is built for CI, not for local development. We need to be able to develop along side these tests

**Comment by jsnoble** [comment]
@peterdemartini we have made a lot of changes to e2e testing. Is this still an issue?

**Comment by peterdemartini** [comment]
I am not sure if we need linking support in the e2e tests since we've switched to a monorepo. If there are cases we need to link we should probably add them to this repo.
