### ISSUE TITLE
Proper readyForAllocation in k8s

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#744]
For the initial first pass of implementing support for kubernetes I am going to punt on implementing `readyForAllocation`.  This issue should serve as a reminder that the k8s clustering doesn't currently provide any feedback to users if they submit a job to an oversubscribed cluster.

According to the [k8s resource management docs](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/)
the current behavior will be:
 
> If the scheduler cannot find any node where a Pod can fit, the Pod remains unscheduled until a place can be found.

It might not work this way until the pods explicitly request resources.

(Refs PR #738)

**Comment by kstaken** [comment]
I guess this isn't surprising. Teraslice native actually works the same way. It means the job queue in Teraslice will never have any effect as it will always be handed off to Kubernetes.

**Comment by godber** [comment]
At the very least the Teraslice master could ping the k8s API somehow.

**Comment by jsnoble** [comment]
We indirectly do this though the monitoring systems we use
