### ISSUE TITLE
k8s cluster master should make use of executionService

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#750]
The current implementation of the k8s cluster does not use executionService for anything.  Jared indicates that this is probably an issue in [this comment](https://github.com/terascope/teraslice/pull/738#discussion_r196437568):

> this might be a little bit of an issue. The executionService was used as a backup to mark executions as failed in the 'execution:error:terminal' event. This happens on a terminal error on the execution_controller and its plausible that it would not be able to mark the state as failed itself. We don't want executions exiting without being marked. The executionService was also used to potentially terminate executions if they disconnected for to long from cluster_master. Im not sure how applicable this is in kuberenetes. What should be done if cluster_master does not have an active connection?

We will likely see issues until this is dealt with.

**Comment by peterdemartini** [comment]
I believe those changes should be sufficient to mark this as complete.
