### ISSUE TITLE
Dynamic tracing or logging

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#754]
As an operator, would be nice to open & close the log flood gates on demand, specifically the librdkafka logs.  Some options:

1. The bunyan logger [has support for dtrace](https://github.com/trentm/node-bunyan#runtime-log-snooping-via-dtrace) but only on systems with good dtrace support (linux not being one of them).

1. Linux is slowly catching up to dtrace-like functionality.  There is growing support for userspace dynamic tracing (USDT).  [Here is an example](https://medium.com/sthima-insights/we-just-got-a-new-super-power-runtime-usdt-comes-to-linux-814dc47e909f) that shows how to define userspace probes in node & python.

1. Roll our own, even if specific to getting at librdkafka debug logs.  Spit-balling a workflow:
    1. Operator connects to some control channel `nc ts_gen1 5000 <<< "probe job ${JOB_ID}"`
    1. Start listening to consumer's `event.log` & `event.error` events
    1. The event handler relays all msgs to the probe channel
    1. When operator closes socket, remove that event listener

1. Put log msgs [into a ring buffer](https://github.com/trentm/node-bunyan#raw--ringbuffer-stream) and expose an api for operators to dump the buffer.  May still call for a way to dynamically enable the ring buffer since volume of msgs could introduce an unnacceptable time penalty.  And will probably only want to see msgs for a specific job/consumer.

Option 1 is a no-go.  I think option 2 worth exploring even if the USDT landscape is still a bit difficult to navigate in linux.  I see options 3 & 4 as fallbacks.

**Comment by kstaken** [comment]
This is will be related to #846

**Comment by kstaken** [comment]
This is handled by operational systems.
