### ISSUE TITLE
k8s clustering worker restart policy should match terafoundation expectations

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#767]
Terafoundation's expectations for workers is that:

Workers exiting with a:

* zero exit status should not be restarted
* non-zero exit status should be restarted

The k8s clustering should behave this way as well.

**Comment by godber** [comment]
I am concerned about the following comment

> Only a .spec.template.spec.restartPolicy equal to Always is allowed, which is the default if not specified.

at

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template

**Comment by godber** [comment]
So the possible `restartPolicy`s are described [here](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy):

> A PodSpec has a restartPolicy field with possible values Always, OnFailure, and Never. The default value is Always. restartPolicy applies to all Containers in the Pod. restartPolicy only refers to restarts of the Containers by the kubelet on the same node. Exited Containers that are restarted by the kubelet are restarted with an exponential back-off delay (10s, 20s, 40s …) capped at five minutes, and is reset after ten minutes of successful execution. As discussed in the Pods document, once bound to a node, a Pod will never be rebound to another node.

If the statement in the comment above doesn't forbid it, then the policy we want is `OnFailure`.  Otherwise we need to figure out how trigger the deletion of the slicer deployment, slicer service and worker deployment when a once job completes.  See [`k8s.deleteExecution()`](https://github.com/terascope/teraslice/blob/master/lib/cluster/services/cluster/backends/kubernetes/k8s.js#L217).

**Comment by godber** [comment]
Ah, here's the design logic around the Deployment `restartPolicy` being forced to `Always`:

> Three types of controllers are available:
Use a Job for Pods that are expected to terminate, for example, batch computations. Jobs are appropriate only for Pods with restartPolicy equal to OnFailure or Never.
Use a ReplicationController, ReplicaSet, or Deployment for Pods that are not expected to terminate, for example, web servers. ReplicationControllers are appropriate only for Pods with a restartPolicy of Always.
Use a DaemonSet for Pods that need to run one per machine, because they provide a machine-specific system service.

Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime

**Comment by godber** [comment]
So based on the logic outlined above, I guess teraslice `once` jobs should be [k8s jobs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) while persistent jobs should be k8s deployments.  Currently everything is a deployment.

**Comment by peterdemartini** [comment]
@godber I feel like using Jobs for execution controllers and workers would be more appropriate than a Deployment, even for persistent Teraslice jobs. Is there any case where the Kubernetes Job wouldn’t be handled correctly?

**Comment by godber** [comment]
I started reading through the docs on Jobs to see if that would really work.  Like the rest of k8s it's concept heavy and I didn't manage to figure out whether jobs really match our needs yet.  There's no simple `scale` parameter I can map to our number of workers.  We have to understand their parallelism types.

**Comment by godber** [comment]
None of these modes really seem to map to what we expect:

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#parallel-jobs

I get the feeling we'll be better off using our messaging to just handle the teraslice job complete scenario on once jobs and squeeze it in as a deployment.  Maybe a third reading of the above link will make more sense in our context.  Just not seeing it now.

Or I wonder how hard/nasty it is to fork the Deployment controller and tweak it for our own needs.

**Comment by peterdemartini** [comment]
From my understanding, I think the Execution Controller falls under the job type 1, and I think the works fall under job type 3. For example:

**EXECUTION CONTROLLER JOB SPEC:**

```
.spec.parallelism = N/A;
.spec.completions = 1;
.spec.restartPolicy = 'Never'
```

Using that configuration, the execution controller would run until it exits. Since restart is `Never` and the job won't be marked completed unless it exits with a non-zero exit code. We can use the completion status of Kubenetes job should reflect the completion status of the execution context;

**WORK JOB SPEC:**
```
.spec.parallelism = numberOfWorkers;
.spec.completions = N/A;
.spec.restartPolicy = 'OnFailure'
```

Using that configuration, the workers will run and restart only on failure. When they all exit with a non-zero status code the "work" should be considered complete.

**Comment by godber** [comment]
For now we will make the `execution_controller` a `Job` and leave the worker as is.

**Comment by godber** [comment]
I've pushed my changes that make the `execution_controller` a `Job` to this branch: https://github.com/terascope/teraslice/tree/k8s-and-teraslice-worker

**Comment by godber** [comment]
## Design Question

When an `execution_controller` completes, the container exits with a `0` exit status, this causes the k8s Pod to stop and go to the `Succeeded` state and the k8s Job stops as well.  These are not currently deleted by Teraslice:

https://github.com/terascope/teraslice/blob/de6efd0f05f4fabe4915121c97f13513f60ae5de/lib/cluster/services/cluster/backends/kubernetes/k8s.js#L225-L247

I have made sure these stopped pods do not show up as workers in the Teraslice cluster state though.

The k8s `Jobs` will need to be manually [cleaned up periodically](https://github.com/terascope/teraslice/issues/772).  Or we can just go back to deleting the Jobs on completion.  Keeping the pods around leaves the logs available for review.

I think the ideal behavior would be to allow this behavior to be changed via cluster or job configuration.  Something like `k8s_completed_execution_controller_pod_timeout`:

* `-1` - means delete on completion
* `0` - means manual curation
* `N` - delete after some time

**Comment by godber** [comment]
Actually, by not deleting the `Job` calling `_stop` no longer stops the `execution_controller` pod ...

https://github.com/terascope/teraslice/blob/de6efd0f05f4fabe4915121c97f13513f60ae5de/lib/cluster/services/cluster/backends/kubernetes/index.js#L291-L298

So, we'd have to arrange for the `Job` to stop somehow.

**Comment by erik-stephens** [comment]
> Or I wonder how hard/nasty it is to fork the Deployment controller and tweak it for our own needs.

I'd consider Custom Resource Definitions (CRD's) if it starts feeling too much like shoving a square peg into a round hole.  Understanding & knowing how to develop CRD's will serve us more broadly as operators as well.

**Comment by godber** [comment]
> I'd consider Custom Resource Definitions (CRD's) if it starts feeling too much like shoving a square peg into a round hole. Understanding & knowing how to develop CRD's will serve us more broadly as operators as well.

Yeah, CRDs, thats what I was trying to remember at the time.  Though I think what I pushed up yesterday worked out pretty well.

**Comment by peterdemartini** [comment]
Regarding stopping the execution, I think it would make send a message to the execution_controller to tell it to exit; otherwise, we should delete the Job.

Regarding the execution cleanup, maybe we can use the [Garbage Collection](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/).

**Comment by godber** [comment]
The current master branch implements `execution_controllers` as Jobs and workers as Deployments. We've done what we can here.  There's a possibility we revisit this in the future.
