### ISSUE TITLE
ees_writer - ephemeral elastic search writer in k8s

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#771]
I was thinking about @kstaken's higher level view of things.  Specifically I have an idea about how we can use ES dynamically for temporary result sets from larger datasets.  This is for discussion only, maybe never to be implemented.

We could create a new writer `ees_writer`, which stands for ephemeral elasticsearch writer.  This writer will automatically create it's destination ES cluster in k8s.  As it writes to this cluster it can expand the cluster as necessary (for space or write rate).  Every result set ends up with it's own ES cluster.  These clusters just use ephemeral disk, they are not intended to be persistent.  One of the writer options is the timeout for the cluster ... the time after which the cluster gets removed.  If persistence is needed, then the data needs to be moved ... or perhaps theres a way to "persistify" an ephemeral ES cluster (e.g. rolling in nodes with persistent storage).

It should deploy a kibana to go with the ES cluster.

**Comment by godber** [comment]
Or perhaps this could be implemented just as an option on existing ES writers.

**Comment by kstaken** [comment]
Not sure this belongs here. Maybe more an internal thing.
