### ISSUE TITLE
job status set to stopped before all workers exit

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/teraslice#783]
When stopping jobs on the k8s qa instance of teraslice (v0.38.1) I found that the job status will be set to stopped before all the workers have exited.  The job was reading from kafka with 50 workers, so stopping the all the workers takes about 30 seconds.

**Comment by godber** [comment]
I had been thinking that this was OK behavior and maybe it still is.  But one definite drawback is that it could be possible to stop a job, then immediately start that job again, while workers from the previous job are still running and working (but will shutdown soon).  This isn't a problem for jobs reading from Kafka but could be a problem when reading from other data sources (I haven't fully thought it through).

This raises the point that I don't think there's anything that will prevent users from starting the same job twice in k8s clustering, unless that is managed elsewhere.

**Comment by peterdemartini** [comment]
I agree that this can be potentially dangerous, I also think this behaviour would be unexpected from an end user.

**Comment by jsnoble** [comment]
We decided that this will be handled mostly in the api layer. We will block returning until it finishes. We will put it in a `stopping` state when the command is received, then we will poll cluster state until we can determine that it no longer exists. We will mark the job as `stopped` only if it is not already in a terminal status and then return.
