### ISSUE TITLE
Teraslice Manager command line tool

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#792]
Project: `teraslice-cli`
Command: `tjm`

This is to become THE tool for managing Teraslice clusters from the command line. There will be at least 3 categories of users for this.

1. data engineers - job and asset management with access to the job file or asset bundle. What TJM was originally designed to do.

2. cluster admins - Commands related to provisioning and managing clusters

3. job operations - Commands related to job management in the absence of the job file.

This will merge `teraslice_job_manager` with some of the cluster commands being created internally. 

A major component of the design of this tool is that it will need to easily work with multiple clusters and everything about the tool should accommodate that and make it easy. The tool should maintain a local repository of information about the clusters it knows about to make managing those clusters easy.

NOTE: the expectation is that this will be the first thing that people install and eventually it should be able to bootstrap a Teraslice environment either locally or in K8s.

NOTE: it is critical to approach this tool with the understanding that there will eventually be a web UI that mirrors much of this functionality. The CLI is just a different kind of UI. This means the presentation and logic for the more advanced commands should ideally be developed in a loosely coupled manner so that the logic may be reusable with alternative front end presentations. 

## Cluster shorthand

The tool should allow the registration of a cluster under a shorthand alias so that commands can reference specific clusters without needing to provide the full URL. Any place where a URL is required should allow the substitution of the shorthand name. This is referred to as `cluster_sh`.

Examples:

```
tjm cluster alias ts_gen1 ts_gen1.example.com:5678

tjm run job.json -c ts_gen1
```

## Identifiers

Many commands will take identifiers of the form `cluster_sh:ID` or `cluster_sh:TYPE:ID`. In this case `TYPE` can be one of `asset`, `job` or `ex`. If `TYPE` is omitted then  the ID is evaluated relative to the context of the current command. If `TYPE` is provided and is not usable within the context of the current command then an error should be thrown. This means every command that takes in an ID will have an internal concept of type. This is referred to as `object_id`.

In some contexts a wildcard id `cluster_sh:*` may also make sense.

Examples:

```
ts_gen1:59654d64-95a8-4dd5-9634-1734c2f62f37
ts_gen1:ex:59654d64-95a8-4dd5-9634-1734c2f62f37
ts_gen1:job:d0cd6381-488f-4fa7-ab7b-59388cc7728c

ts_gen1:*
```

## Draft command list

* cluster
     * list
        * Will display a table of all registered clusters
     * alias <alias> <url>
          * Adds an alias for the URL that will be stored in a config file under the current users account.
     * init <--local --kubernetes>
         * Lots of detail TBD around this

* asset
     * list <cluster_sh>
         * Lists all assets deployed on the specified cluster
     * deploy <asset.json | URL>
         * 
     * update <asset.json | URL>
          * 
     * init <asset_name>
           * Sets up a new asset bundle directory
     * status <asset_name>
            * Shows the status of a deployed asset on all clusters
     * replace <asset_name> -c cluster_sh
            * Removes and replaces the asset on the cluster. This puts a different version of the same asset  under the same version number. Only useful during development.      
     
* job
     * Most of these are enhanced version of existing tjm commands.
     * list <cluster_sh>
          * Shows all jobs defined for the cluster
     * run <job.json>
     * update <job.json>
     * stop <cluster_sh:* | job.json | object_id>
     * start <cluster_sh:* | job.json | object_id>
     * restart <cluster_sh:* | job.json | object_id>
     * save <cluster_sh:* | object_id>
          * Save the state of jobs on a cluster
     * errors <job.json | object_id>
     * reset <job.json>
     * pause <job.json> 
     * resume <job.json>
     * view <job.json | object_id>
     * find <job_name>
         * Looks for a job by name across clusters
     * init <job.json>
          * Creates a stubbed out job file

* worker
     * list <cluster_sh>

* node
     * list <cluster_sh>

* ex
     * list <cluster_sh>
     * status <object_id>
     * stop <object_id>
     * start <object_id>
     * errors <object_id>

* controller
     * list <cluster_sh>
     * stats <object_id>

## Example commands

```
tjm job list ts_gen1
tjm asset list ts_gen1
tjm controller list ts_gen1
tjm node list ts_gen1

tjm job stop some-job.json
tjm job errors some-job.json
tjm job stop ts_gen1:*
tjm job save ts_gen1:*

tjm job stop ts_gen1:job:d0cd6381-488f-4fa7-ab7b-23888cc7728c

tjm ex stop ts_gen1:6764c982-0a7a-4deb-beca-fd82c9902300

```

**Comment by kstaken** [comment]
We'll make the project name `teraslice-cli`

**Comment by kstaken** [comment]
refs #843

**Comment by godber** [comment]
I think this is sufficiently done, fixes can be requested in future tickets ... like 

https://github.com/terascope/teraslice/issues/874

Also, noteworthy changes from this issue include:

* we abandoned the *Identified* concept
* we stopped overloading the `job` command and split it out to `job` and `tjm`.
