### ISSUE TITLE
Add support for job specific resource requests and limits

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#793]
K8s supports both resource requests and resource limits.  We should have a way of allowing users to specify these on a per job basis.  We should also probably be making at least some resource request by default in the case where users do not specify them for the job.

**Comment by godber** [comment]
For managing worker resource requests and limits we will continue to use the `cluster` key on the job and extend it with the `resource.request` and `resource.limit` keys.  These will both take `cpu` and `memory` subkeys which map to k8s `vcore` and `memory` resources.  So a job would look like this:

```json
{
    "name": "gen-tenk-noop",
    "lifecycle": "persistent",
    "workers": 1,
    "cluster":{
        "resource": {
            "request": {"cpu": 1, "memory": 2147483648},
            "limit": {"cpu": 2, "memory": 4294967296}
        }},
    "operations": [
        {
            "_op": "elasticsearch_data_generator",
            "json_schema": "",
            "size": 10000,
            "start": "",
            "end": "",
            "format": "",
            "stress_test": false,
            "date_key": "created",
            "set_id": "",
            "id_start_key": ""
        },
        {
            "_op": "noop"
        }
    ],
    "analytics": true
}
```

Which would map to a resource snippet as follows on the worker deployment:

```yaml
    resources:
      requests:
        memory: 2147483648
        cpu: 1
      limits:
        memory: 4294967296
        cpu: 2
```

## Questions

**Q** If a job omits these, does the cluster master insert defaults or do we let workers run without resource settings?

**A** Perhaps if there are cluster defaults defined, then we apply them.  Otherwise there are no defaults.

**Q** What to do if `limits` are provided but `requests` are not?  It's probably OK to have `requests` without limits. 

**Q** What validation should be enforced?  Must `limits` be greater than `requests`?

**Comment by peterdemartini** [comment]
If kubernetes works with a limit but no minimum, we should allow that. 

Yes, I think validations should enforce that limits are greater than the minimum. Additionally there should be a lower validation limit for both values, for example Teraslice requires at `60M` RAM. 

Also it would be easier for user’s to deal with human readable bytes, like `1G` or `2048M`

**Comment by godber** [comment]
The section linked to here describes how scheduling decisions are made based on resources

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled

The section following the one above describes how BOTH `requests` and `limits` are applied for both CPU and memory.  Mostly:

* The `spec.containers[].resources.requests.cpu` is converted to its core value, which is potentially fractional, and multiplied by 1024. The greater of this number or 2 is used as the value of the `--cpu-shares` flag in the docker run command.
* The `spec.containers[].resources.limits.cpu` is converted to its millicore value and multiplied by 100. The resulting value is the total amount of CPU time that a container can use every 100ms. A container cannot use more than its share of CPU time during this interval.
* The `spec.containers[].resources.limits.memory` is converted to an integer, and used as the value of the `--memory` flag in the docker run command.
* If a Container exceeds its memory limit, it might be terminated. If it is restartable, the kubelet will restart it, as with any other type of runtime failure.
* If a Container exceeds its memory request, it is likely that its Pod will be evicted whenever the node runs out of memory.
* A Container might or might not be allowed to exceed its CPU limit for extended periods of time. However, it will not be killed for excessive CPU usage.

**Comment by kstaken** [comment]
So based on this sounds like the memory request is just used for scheduling like you were saying. And the memory limitation is not anything different than what we've typically seen with docker memory management. 

Seems to support simplifying to just `memory` and `cpu` and then set both requests and limits the same.

**Comment by godber** [comment]
I find that specific set of behaviors to be inconsistent, but yeah, `minimum` definitely doesn't convey what happens in any real sense.  Heck, they even use `requests.memory` as a soft upper limit of sorts.

**Comment by godber** [comment]
Done in #802
