### ISSUE TITLE
Convert jobname to valid k8s label

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#816]
Since we use the Teraslice jobname as a label on k8s objects we need to make sure these names are actually valid.  The error we get is:

```
    Error: Request k8s.post of service with body {"kind":"Service","apiVersion":"v1","metadata":{"labels":{"app":"teraslice","nodeType":"execution_controller","exId":"5e1b0f15-e0e7-4e98-b9cc-efe9ee06917c","jobId":"a9128d83-3a13-41df-84cb-9d2bac568c3d","jobName":"datagen 10b to tera1 kafka_data1","clusterName":"teraslice-qa3"},"name":"teraslice-execution-controller-5e1b0f15-e0e7-4e98-b9cc-efe9ee06","namespace":"default"},"spec":{"ports":[{"port":45680,"targetPort":45680}],"selector":{"app":"teraslice","nodeType":"execution_controller","exId":"5e1b0f15-e0e7-4e98-b9cc-efe9ee06917c"}}} failed: Error: Service "teraslice-execution-controller-5e1b0f15-e0e7-4e98-b9cc-efe9ee06" is invalid: metadata.labels: Invalid value: "datagen 10b to tera1 kafka_data1": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
        at K8s.post (/app/source/packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/k8s.js:138:25)
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Conveniently this provides the following:

```
a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**Comment by godber** [comment]
We have this issue with the `clusterName` as well:

https://github.com/terascope/teraslice/blob/v0.40.2/packages/teraslice/lib/cluster/services/cluster/backends/kubernetes/deployments/worker.hbs#L11

The only constraint put on the cluster name is that it's a string:

https://github.com/terascope/teraslice/blob/v0.40.2/packages/teraslice/lib/config/schemas/system.js#L68-L72

I can enforce this naming constraint in the same way but perhaps we do want to constrain the cluster name at the config level.  @kstaken you have feelings on this?  Should users be free to name their teraslice cluster `Teraslice Cluster: Marty's Super Cluster of DOOOM!!!!`?

Actually, regardless of the answer to the question above, I should probably enforce the clusterName label thing myself here at this level.  Given that, it's probably not worth even considering my question above.

**Comment by kstaken** [comment]
Cluster name should definitely be restricted. It's used to name indices in ES too which would break in the same manner if spaces were allowed. Should follow whatever restrictions exist for ES names + K8s names.

**Comment by godber** [comment]
Oh yeah, I forgot about the indices ... I'll file a separate ticket but plan to address it now-ish.
