### ISSUE TITLE
Teraslice k8s cluster init cli command

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#851]
We could possibly implement an `earl cluster init` command that deploys a teraslice master into k8s and sets up all of the various things one needs.  The steps for bootstrapping are covered in my `setup-all` Make target here:

https://github.com/terascope/teraslice/blob/v0.42.2/examples/k8s/Makefile#L91

```
earl cluster init --type k8s <VALUES.YAML>

Options:
  -t/--type          - Teraslice cluster type, only k8s is currently supported,
                       default: k8s

Arguments:
  VALUES.YAML - Teraslice and Terafoundation configuration settings
```

The command could either:

* Use the k8s api
* Wrap `kubectl` - I think wrapping kubectl would be easier since that pushes all of the k8s cluster selection and setup stuff to `kubectl` config, which the user has probably done already.

**Comment by godber** [comment]
Unfortunately I think we have to use this `values.yaml` method because there are too many parameters to configure when setting up a teraslice cluster.  Mostly because the connections are statically configured in the yaml file.  If these were stored elsewhere, then we can be more opinionated and just expose a few parameterized things as arguments on the command like, with more complex settings overridden with a values.yaml.

**Comment by godber** [comment]
@busma13 This issue reminds me of more use cases for the work you're doing ....

1. dev KIND initial standup
2. dev KIND rebuild
3. actual users in KIND locally
4. actual users in ANY kuberenetes cluster ... 

So for now, the dev use case being implemented in ts-scripts makes sense, but in the long run, I have some doubts about that.

**Comment by busma13** [comment]
@godber Jared suggested creating a top level javascript file in teraslice to start the k8s environment from. This would be analogous to running `yarn:start` which runs the `service.js` script to start teraslice. Maybe this would fit the other use cases better?

**Comment by godber** [comment]
I think for now the work done to make `k8senv` work cover our needs here.  There are other use cases that can be addressed but we'll ignore those for now.

**Comment by godber** [comment]
See these docs:

https://terascope.github.io/teraslice/docs/development/k8s#kubernetes-development-environment
