### ISSUE TITLE
job-components: Consider serialization/deserialization at framework level

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#855]
We should consider how to handle serialization/deserialization at the framework level so we don't end up with slightly incompatible implementations in each reader/sender. The Kafka and HDFS readers are the obvious places where this will apply as the data can be in many formats. We've considered adding this directly to the readers and it seems simultaneously to be both the right and wrong place for it. The same with adding it to the job. 

I'm thinking maybe `DataEntity` is the correct place to deal with this since it will ultimately be what's responsible for managing the record content. So then the readers only need to pass through a configuration option on what framework supported format the data is in and then the DataEntity can handle any needed conversion. Format support would of course be open and extensible.

**Comment by peterdemartini** [comment]
For deserialization, I purpose we add another factory method to the `DataEntity` with an interface of `DataEntity#makeFrom(data: string|Buffer, opConfig: OpConfig, metadata?: object)`. Alternative names for this method could be, `deserialize`, `fromEncoding`, `fromBuffer`, `fromData`, `fromString`, or `marshal`.

For serialization, I purpose we add a method to the `DataEntity` with an interface of `DataEntity->serialize(opConfig: OpConfig)`. Alternative names for this method could be, `serialize`, `toEncoding`, `toBuffer`, `toData`, `toString`, or `unmarshal`.

Additionally we will need to add another configuration on the operation config, `_encoding: 'json'`, which can be used serialization and deserialization.

**Comment by kstaken** [comment]
I think maybe `DataEntity#fromBuffer` may make sense and leaves it open for other types of conversions like `fromString` if that ends up being needed.

And that makes `DataEntity#toBuffer` the logical inverse.

**Comment by peterdemartini** [comment]
I agree
