### ISSUE TITLE
Worker slice analytics logs the full slice definition

### ISSUE THREAD

**Issue by macgyver603** [terascope/teraslice#865]
[This](https://github.com/terascope/teraslice/blob/61116dff01dc5dd40854771de7e8d7e02e7658f9/packages/teraslice/lib/workers/helpers/op-analytics.js#L42) function ends up logging the full slice definition for each completed slice. For slicers [like the one in the kafka reader](https://github.com/terascope/kafka-assets/blob/master/asset/teraslice_kafka_reader/index.js#L435), this isn't a problem, but for other processors that generate much larger slice definitions, this could clutter the log files rather quickly. Additionally, there may be some scenario later on where it would be undesirable to log the slice definitions in general.

The workers should have the option to prevent this logging or at least have it truncated to some extent.

**Comment by peterdemartini** [comment]
I agree, perhaps it would make sense to have minimal information logged using info and any additional information logged using trace
