### ISSUE TITLE
`${response.slice_id}` is undefined in the execution controller

### ISSUE THREAD

**Issue by macgyver603** [terascope/teraslice#866]
In kubernetes clustering, [this](https://github.com/terascope/teraslice/blob/2793da2987618b4f86dbe24e901d4f0f0c297bf2/packages/teraslice/lib/workers/execution-controller/index.js#L177) message is logged as `has completed its slice undefined` on the execution controller pod.

**Comment by peterdemartini** [comment]
It should be `response.slice.slice_id` I believe.
