### ISSUE TITLE
Bootstrap teraslice with assets

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#868]
There should be a simple way for users to bootstrap a new deployment of teraslice with the standard set of assets.

**Comment by godber** [comment]
Ok, I've got the basic assets building in Travis on 

* https://github.com/terascope/elasticsearch-assets/releases/tag/v1.0.3
  * https://github.com/terascope/elasticsearch-assets/releases/download/v1.0.3/elasticsearch-v1.0.3-node-8-linux-x64.zip
* https://github.com/terascope/kafka-assets/releases/tag/v1.1.0
  * https://github.com/terascope/kafka-assets/releases/download/v1.1.0/kafka-v1.1.0-node-8-linux-x64.zip
* https://github.com/terascope/file-assets/releases/tag/v0.2.1
  * https://github.com/terascope/file-assets/releases/download/v0.2.1/file-assets-v0.2.1-node-8-linux-x64.zip

Feel free to try them out ... a few things to note ... I've forgotten the HDFS asset, I'll add that.  The names are inconsistent (`file-assets`, `elasticsearch`, `kafka`) because it comes from each project's `asset.json`.  I can go tweak them all ... possibly they should all match `*-asset` or `teraslice-*-asset`?  Or probably `*-assets` to match the project names ... yeah that.

I am perpetually annoyed by the fact that each asset has three places to define name and version:

* `package.json`
* `asset/package.json`
* `asset/asset.json`

They are always going to mismatch unless we force it or eliminate something.

I'd feel better if we actually tested the assets themselves, though perhaps thats something to be done downstream of here.

**Comment by godber** [comment]
Oh, obviously I need to get the MacOS assets built too.

**Comment by peterdemartini** [comment]
We should probably start building node 10 as well

**Comment by peterdemartini** [comment]
Ahh, I think I know what’s up, it has to do with the matrix only being applied to one of the jobs. I will post an example of how to fix it

**Comment by godber** [comment]
Yeah, I've been reading and re-reading the docs.  I get it better now, the matrix is expanded and runs the implicit `test` job ... and then my `jobs` stuff runs with the first elements of the matrix.

**Comment by peterdemartini** [comment]
Makes sense, I don't think we need the jobs. I think if we use the matrix builds, then run the tests on every build, and keep the only deploy if the tags are set, it should work. Also if we do that it would make sense to move change the `script: yarn build` to `before_deploy: yarn build`. This will only cause it to just run if there if it is a tagged release.

**Comment by godber** [comment]
I think this is what we want:

https://github.com/travis-ci/travis-ci/issues/8295

At the very least I think I can explicitly list the build stages with the various matrix values.  I don't think there's a way to do this without doing that.

**Comment by godber** [comment]
I think this is what you're saying, though I have doubts it will work:


```
language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx

before_deploy: yarn build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: builds/*.zip
  skip_cleanup: true
  on:
    tags: true
```

Maybe it will.

**Comment by godber** [comment]
Ok, we have all four "required" assets setup for CI and package release.

* https://github.com/terascope/file-assets/releases/tag/v0.2.1
* https://github.com/terascope/kafka-assets/releases/tag/v1.1.1
* https://github.com/terascope/elasticsearch-assets/releases/tag/v1.1.0
* https://github.com/terascope/hdfs-assets/releases/tag/v0.1.43

This includes the following for each asset:

* Linux on Node 8
* Linux on Node 10
* OS X on Node 8
* OS X on Node 10

Each asset now has at least VERY basic tests that pass too.  Kafka remains effectively untested though.

**Comment by godber** [comment]
Discussed during today's phone call, this will be implemented as the following (approximately)

```
earl asset load cluster terascope/file-asset
```

This will retrieve (from github) the latest release of the `terascope/file-asset` for the node and OS release of the specified cluster (this implies we have this somehow, it's newly available on the root of teraslice's API).  Once retrieved it will be locally cached somewhere.  Then uploaded to the specified cluster.

There are a whole variety of behaviors that will have to be determined here (around updating and things like that).

The command will likely eventually accept version information as an argument or marshalled in the name like: `terascope/file-asset@v0.2.1`.

The command may need to optionally take platform and node version as options to support clusters that don't yet expose that.  Though I may just worry about this later.

**Comment by godber** [comment]
This was made possible by adding the `load` command in: https://github.com/terascope/teraslice/pull/890, however `load` is going to change to `deploy` upon completion of `https://github.com/terascope/teraslice/issues/894`.

If you need load in the meantime, it looks like this:

```
earl assets load <cluster_sh> [<asset>]

Uploads asset from file, github, or source to Teraslice


Options:
  --help, -h                  Show help                                [boolean]
  --version                   Show version number                      [boolean]
  --baseDir                   specify the base directory to use, defaults to cwd
    [string] [default: "/Users/godber/Workspace/terascope/opensource/teraslice"]
  --localhost, -l             short cut to localhost  [boolean] [default: false]
  --host-cluster, -c          Cluster to save jobs from.
                                              [default: "http://localhost:5678"]
  --config, --conf            Config file
                           [default: "/Users/godber/.teraslice/config-cli.yaml"]
  --state-file-dir, -d        Directory to save job state files to.
                           [default: "/Users/godber/.teraslice/job_state_files"]
  --output, -o                Output display format pretty or txt, default is
                              txt    [choices: "txt", "pretty"] [default: "txt"]
  --cluster-manager-type, -t  cluster manager type, kubernetes or native
                           [choices: "kubernetes", "native"] [default: "native"]
  --info, -i                  show cluster info                 [default: false]
  --yes, -y                   Answer 'Yes' or 'Y' to all prompts[default: false]
  -a, --arch                  The architecture of the Teraslice cluster, like:
                              `x32`, `x64`.  Determined automatically on newer
                              Teraslice releases.
  -f, --file                  When specified with a path to an asset file,
                              uploads provided asset without retriving from
                              GitHub.  Useful for offline use.          [string]
  -n, --node-version          The node version of the Teraslice cluster, like:
                              `v8.11.1`, `v10.13.0`  Determined automatically on
                              newer Teraslice releases.
  -p, --platform              The platform of the Teraslice cluster, like:
                              `darwin`, `linux`.  Determined automatically on
                              newer Teraslice releases.
  -q, --quiet                 Silence non-error logging.
  -s, --skip-upload           Skips upload to Teraslice, useful to just download
                              the asset.

Examples:
  earl assets load ts-qa1 terascope/file-assets
  earl assets load ts-qa1 terascope/file-assets -a x64 -p linux -n v8.10.1
  earl assets load ts-qa1 -f /tmp/file-assets-v0.2.1-node-8-linux-x64.zip
```

But I didn't update the pkg version so I don't think we'll end up with a new NPM package until I address the rework ticket mentioned above.
