### ISSUE TITLE
Do better asset validation

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#872]
We need to do a better job of validating that an asset if correctly formatted before accepting it. 

In particular if the asset has dependencies then we should verify that the dependencies are actually installed in the asset. If they're not installed than the asset should be rejected with a helpful message.

**Comment by godber** [comment]
This is from the perspective of Teraslice receiving an asset through its HTTP API.

**Comment by kstaken** [comment]
This has been improved with S3 storage of assets.
