### ISSUE TITLE
Respect build npm script in teraslice-cli

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#897]
To support Typescript and preparation build steps when building assets using teraslice-cli. I purpose we use NPM scripts as a generic but standardized way of specifying what to do; the script should be named `asset:build` or just `build`. For example, in the top-level `package.json` a user should be able to specify an NPM script, with a `tsc --project tsconfig.build.json --pretty` or `rm -rf asset/src` or `./scripts/build-asset.sh`.

This feature should only execute the script if it exists, in-order to prevent breaking changes.

**Comment by godber** [comment]
https://github.com/terascope/teraslice/pull/899 implements this ... the expected script name is `asset:build`.

**Comment by godber** [comment]
I overlooked:

> in the top-level package.json

**Comment by godber** [comment]
I think we're good here.  @peterdemartini correct me if I'm wrong.
