### ISSUE TITLE
teraslice-cli simplify lib/config 

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/teraslice#907]
The config object used for teraslice-cli is overly complex.  The conditionals for the different commands should removed to simplify the config.  The config should be made more universal regardless on which command is used.

**Comment by godber** [comment]
That is, the set of properties on the `cliConfig` object should be the same for all commands instead of changing for each command.  The values set will be `null` in some cases, but the properties should still be there.

**Comment by godber** [comment]
Now tracking this branch for this issue: https://github.com/terascope/teraslice/pull/913

**Comment by kstaken** [comment]
Is this still an issue?

**Comment by godber** [comment]
Done
