### ISSUE TITLE
Teraslice in k8s should set default memory and CPU limits

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#914]
The Dockerfile currently enforces a 2GB node heap limit:

https://github.com/terascope/teraslice/blob/v0.44.2/Dockerfile#L39

Though k8s does not have any limits set by default.  Since the 2GB is effectively an implicit limit, we should just accept that fact and make k8s also set memory and cpu limits by default.

**Comment by godber** [comment]
@kstaken you want the default node heap setting to be about 4GB right?

In recent release, it's 2GB.

**Comment by kstaken** [comment]
Since we can change it easily a smaller default is fine. We only set it that large before because it was hard to change.

**Comment by godber** [comment]
Ok, so the plan for this is as follows.

* I am adding `cpu` and `memory` to cluster config.  These will be optional but recommended.
* These can be overridden on a job by job basis (already implemented).
* Internally we will decide what are appropriate cluster wide values.

Keep in mind that both the k8s request and limit are set to the same value and that node's `max-old-space-size` is set to `0.9 * memory` and if `memory` is unset it is `2048`.
