### ISSUE TITLE
Try socket.io v2.2.0 or newer

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#916]
Previously we've had issues with socket.io running with kafka, but we not tested the recently released version [2.2.0](https://github.com/socketio/socket.io/releases/tag/2.2.0). I suggest we test that at some point in the future.

**Comment by godber** [comment]
Socket.io is up to 4.7.2 at this point.

https://github.com/socketio/socket.io/releases/tag/4.7.2

This may be a tough thing to upgrade, but if we're experiencing Node 18 problems that relate to Socket.io ... we may be forced to upgrade to get a fix.

**Comment by godber** [comment]
Actually, I'll close this and file a newer issue so old Peter doesn't have to get alerts.
