### ISSUE TITLE
[CHORE]: Move the remainder of native clustering messaging to teraslice-messaging

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#917]
The code for communication between the `node_master` and `cluster_master` was never migrated to the `teraslice-messaging` package.

**Comment by jsnoble** [comment]
We are slowly migrating our system from native clustering to use k8s, and node_master has a very high chance of being entirely removed as it not even used. We are even considering removing socket.io as is as well but that is still being discussed.
