### ISSUE TITLE
Consider renaming k8s deployments with teraslice job names

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#918]
The teraslice execution controller and workers all have the execution ID in their names.  It might be better to put the job name in the job and deployment names instead.  The labels would still contain jobId and exId.  Though this might have negative consequences.  I haven't fully thought through it.

**Comment by erik-stephens** [comment]
Might want to abbreviate "teraslice-worker-..." to something like "ts-wkr-".  I thought we were limited to 64 characters, but looks like [up to 253 is supported](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/), so maybe not that important.

Also, if going to bake an id from the job, I think job_id makes more sense than ex_id since we almost always operate against job ids and there shouldn't be two instances of the same job running.

**Comment by erik-stephens** [comment]
Out of scope for this issue but wanted to point out another point where it would be useful to bake worker details into the name: kafka consumer client ids.  Being able to look at something like kafka manager and quickly see which workers are lagging would be useful.

**Comment by godber** [comment]
Seems for some reason 63 is still the max for deployment names ... when I try to exceed that I get:

```
Error: Deployment.apps \"ts-wkr-example-data-generator-job-d7fe2074-d0c6-4168-9300-065a1c04d944\" is invalid: spec.template.spec.containers[0].name: Invalid value: \"ts-wkr-example-data-generator-job-d7fe2074-d0c6-4168-9300-065a1c04d944\": must be no more than 63 characters\n    at K8s.post
```

**Comment by godber** [comment]
@erik-stephens how do you feel about:

```
ts-exc-example-data-generator-job-d9e36896-f0b9-p2hdc             1/1     Running   0          20s
ts-wkr-example-data-generator-job-d9e36896-f0b9-bb6d4cc66-dcdd2   1/1     Running   0          19s
ts-wkr-example-data-generator-job-d9e36896-f0b9-bb6d4cc66-wchl8   1/1     Running   0          19s 
```

That's this template:

```
        const name = `ts-exc-${jobNameLabel.substring(0, 43)}-${execution.job_id.substring(0, 13)}`;
```

**Comment by erik-stephens** [comment]
GET OUT OF MY HEAD! /s  That's exactly what I was hoping for in the face of that limitation.

**Comment by godber** [comment]
I include more of the job name and less of the job Id on the assumption that the job name is more likely to collide.
