### ISSUE TITLE
Removing workers removed too many workers

### ISSUE THREAD

**Issue by mkhpalm** [terascope/teraslice#919]
I had an issue today where a job was running 181 workers on a teraslice cluster. I removed 91 workers to decrease workers to 90 but it resulted in only 5 active workers total.

This was running on a native teraslice cluster version `0.37.1`

**Comment by godber** [comment]
@mkhpalm you said this was on a cluster running native clustering?

**Comment by godber** [comment]
I've confirmed with Mike that this was on native clustering, so I'm removing the k8s tag.

**Comment by jsnoble** [comment]
Is this still an issue? Its been 5 months and we are on version 0.51 now

**Comment by godber** [comment]
We don't maintain any internal clusters with native clustering anymore so this is hard to answer.

**Comment by kstaken** [comment]
Native clustering can be considered deprecated so this isn't a concern anymore.
