### ISSUE TITLE
Better tooling and documentation for development

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#928]
I believe there is a knowledge gap for using this monorepo. I am aware of the following things that could be better explained or automated. If there is anything else that needs to be addressed, please let me know.

- [x] Removing non-existant packages, see #887.
- [x] Adding a new TS/JS package.
- [x] Running tests on individual packages or files.
- [x] How to use the different NPM scripts available
- [x] How is does the release cycle work  

It would also be good to build a `CONTRIBUTING.md` guideline set that describes some of the conventions we use, e.g. file naming, folder structure, test coverage, etc. So we can avoid having inconsistencies which will make it harder for us, or 3rd party developers, to work on the different packages.

**Comment by peterdemartini** [comment]
Using something like https://github.com/egoist/maid would be helpful for documentation around scripts

**Comment by kstaken** [comment]
Everything in this ticket is checked off. Is there still more work?

**Comment by peterdemartini** [comment]
I think we can close this, we can make more specific issues if there are more improvements needed.
