### ISSUE TITLE
ElasticSearch Index API/Manager

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#930]
**Requirements:**

- It should have an API abstraction, similar to the `@terascope/elasticsearch-api` package.
- It should expose APIs to replace the majority of the elasticsearch backend in Teraslice.
- It should have an index mapping management API, that can do the following:
    * Detect a mapping change and determine if it can do a seamless update.
    * Provide an API for doing the seamless upgrade.
    * Provide an API for migrating an index (this will likely not be done automatically).

**Misc Goals:**

- It should be well-tested with at least 90% test coverage.
- It should use TypeScript.
- It should use Classes.
- It should be battle tested.
- It should reside in its own package with the teraslice repo.

**Future Goals:**

- Add CLI support for in doing an index migration.

**Comment by kstaken** [comment]
Versioning is the critical aspect of this and I think there a couple ways to think about it.

1. Index based versioning
2. Record based versioning

So far all our data engineering processes have been based around index based versioning and given the restrictions of ES it self that may still be the best approach but I'd like to at least give some thought to record based versioning. That may not help in regard to index mappings but it could be useful from a code compatibility perspective.

**Comment by kstaken** [comment]
This is covered by ElasticsearchStore.
