### ISSUE TITLE
Posting the same identical asset twice should return error

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#934]
Previously when posting the same asset, same contents, same version, etc, teraslice would return an error.  Now it just acts like it accepts the asset:

```
# first run, no asset present
$ curl -Ss -XPOST -H 'Content-Type: applicatin/octet-stream' http://ts-test1:80/v1/assets --data-binary @test/fixtures/testAsset/build/testAsset-v0.0.1-node-8-darwin-x64.zip
{
    "_id": "b94bff8304de8d7c0d1bd5d4f573527b33185660"
}
# second run, immediately after first asset
$ curl -Ss -XPOST -H 'Content-Type: applicatin/octet-stream' http://ts-test1:80/v1/assets --data-binary @test/fixtures/testAsset/build/testAsset-v0.0.1-node-8-darwin-x64.zip
{
    "_id": "b94bff8304de8d7c0d1bd5d4f573527b33185660"
}
```

The timestamp doesn't update after the second post.

**Comment by kstaken** [comment]
After seeing this spelled out here I suspect this is how it always behaved. It should be fine to have the exact same asset posted multiple times under the same version. The error scenario I was thinking of is when you change an asset and then don't change the version. The system does defend against that being posted. 

Is there a scenario I'm not thinking of where the behavior described in this ticket causes a problem?

**Comment by godber** [comment]
Nope, just that.  I'll just close this I guess.

So the error condition is when an asset with the same `name` and `version` is posted, but it's hash differs?

**Comment by peterdemartini** [comment]
In the case where you post it and it already exists, it shouldn’t return an error. I have found it using status codes to indicate this works well. For example, return a 200 when it already exists and a 201 for when it creates it.

**Comment by godber** [comment]
When you post an asset there are at least the following three scenarios:

* Asset with matching `name` and `version` did not exist - return `201`
* Asset with matching `name` and `version` did exist but new asset hash was the same - return `200`
* Asset with matching `name` and `version` did exist but new asset hash was note the same - return `4XX` maybe `409` Conflict?

I'm just trying to spell out the requirement at this point.

**Comment by godber** [comment]
Oh, I see my problem here ... the cli currently acts like the package gets updated because it returns a 200 status code but with a text error message in the JSON body:

```
curl --verbose -Ss -XPOST -H 'Content-Type: applicatin/octet-stream' http://ts-test1:80/v1/assets --data-binary @/Users/godber/temp/asset/file-assets-v0.2.1-node-8-linux-x64.zip
*   Trying 192.168.1.1...
* TCP_NODELAY set
* Connected to c3b7s1.tera4.terascope.io (192.168.1.1) port 80 (#0)
> POST /v1/assets HTTP/1.1
> Host: ts-test1
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: applicatin/octet-stream
> Content-Length: 12494338
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Server: nginx/1.13.12
< Date: Thu, 20 Dec 2018 00:19:31 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
<
{
    "error": "asset name:file-assets and version:0.2.1 already exists, please increment the version and send again"
* Connection #0 to host ts-test1 left intact
}
```

So Teraslice should actually set some sort of `400` status code in this case ... if we intend for this to be like an error.

**Comment by peterdemartini** [comment]
Ya that’s kind of odd behavior. We should respect the http status codes for this kind of logic. And yes, a 409 would be the correct status code to us.
