### ISSUE TITLE
Duplicate running `job_id`s when posting a job definition for a running job

### ISSUE THREAD

**Issue by macgyver603** [terascope/teraslice#936]
This can be replicated by specifying a `job_id` in the job definition and then posting it twice to the cluster.

<img width="1303" alt="screen shot 2018-12-20 at 2 39 19 pm" src="https://user-images.githubusercontent.com/11929901/50312474-acdec780-0465-11e9-85fe-95a4b1bee21b.png">

```
{
    "arch": "x64",
    "clustering_type": "kubernetes",
    "name": "my-test-cluster",
    "node_version": "v8.12.0",
    "platform": "linux",
    "teraslice_version": "v0.45.1"
}
```

**Comment by peterdemartini** [comment]
@macgyver603 What API endpoint using when you "post it" twice?

**Comment by macgyver603** [comment]
I am using the [`POST /v1/jobs`](https://github.com/terascope/teraslice/blob/master/docs/api.md#post-v1jobs) API endpoint

**Comment by peterdemartini** [comment]
I found the problem and yup, it is problem
