### ISSUE TITLE
Teraslice v1 http api asset delete should not return 404 instead of 500

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#944]
Right now if you try to delete an asset that does not exist, teraslice returns an http response with a 500 status code.  Wouldn't we want to return a 404 in this case?

```
curl -v -XDELETE http://teraslice.lan:80/assets/f6cfd8f24be708d2fdb2f1bb1ba992fe4274baa9
*   Trying 10.6.6.6...
* TCP_NODELAY set
* Connected to teraslice.lan (10.6.6.6) port 80 (#0)
> DELETE /assets/f6cfd8f24be708d2fdb2f1bb1ba992fe4274baa9 HTTP/1.1
> Host: teraslice.lan
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.13.12
< Date: Sun, 06 Jan 2019 17:45:16 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
<
{
    "error": 500,
    "message": "Could not delete asset f6cfd8f24be708d2fdb2f1bb1ba992fe4274baa9, error: invoking elasticsearch-api _runRequest resulted in a runtime error: Not Found"
* Connection #0 to host teraslice.lan left intact
```

The distinction being from the CLI perspective, a 404 is not treated by an error on delete.  Where as other legitimate 5XX errors should be treated as errors.

**Comment by peterdemartini** [comment]
This is fixed in `v0.46.0`, ref: https://github.com/terascope/teraslice/blob/822c7a718b5d17d9c065787ca99a3b2102d2d070/packages/teraslice/lib/cluster/storage/assets.js#L177-L182
