### ISSUE TITLE
Oversubscribing CPUs results in data loss

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#95]
Reindexing jobs start to lose data if you allocate more workers than available CPU cores, or at least it appears that's the correlation. The more workers you add the more data gets dropped. Test system has 4 cores and jobs up to 4 workers seem to work but going to 5 starts to lose data.

**Comment by kode4food** [comment]
I think the Henny Youngman solution is in order here

**Comment by kstaken** [comment]
Subsequent testing has shown elasticsearch was dropping data due to overflowing the bulk request queue with default sizing on dev nodes.
