### ISSUE TITLE
Conventional Metadata Properties on DataEntity

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#950]
@kstaken recommended we add conventional properties for the `DataEntity` metadata. Currently, the creation of a `DataEntity` will add `_created` property.

I purpose we add the following **recommended** properties:

```ts
interface DataEntityMetadata {
    /** The time at which the DataEntity was created **/
    readonly _createTime: number;

    // conventional properties...

    /** The time at which the data was ingested into the source data */
    _ingestTime?: Date;

    /** The time at which the data was consumed by the reader */
    _processTime?: Date;

    /**
    * The time associated with this data entity,
    * usually off of a specific field on source data or message
    */
    _eventTime?: Date;

    /** A unique key for the data which will be can be used to key the data */
    _key?: string;
}
```

Since storing multiple Date objects on each metadata property will decrease performance, it will be best if we use a getter and setter to abstract the Date object creation until needed.

**Comment by kstaken** [comment]
Are there still places this needs to be applied? Has it been more generally documented outside this ticket?

**Comment by peterdemartini** [comment]
It’s been partially applied to the elasticsearch assets and the kafka assets. They both need to have configuration to pull the evenTime from the incoming data. We still need documentation for this and we need to formalize the date format/usage.

**Comment by kstaken** [comment]
This just needs access APIs to further solidify the convention.
