### ISSUE TITLE
Pull common convict types into terafoundation

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#959]
The `optional_String` and related convict types defined [here](https://github.com/terascope/teraslice/blob/v0.42.2/packages/job-components/src/formats.ts) should be moved out of Teraslice and into Terafoundation.

We had to implement a workaround here:
https://github.com/terascope/terafoundation/pull/118

**Comment by jsnoble** [comment]
This has been migrated to job-components to make it more accessible to assets and other libraries
