### ISSUE TITLE
Support multiple config files

### ISSUE THREAD

**Issue by erik-stephens** [terascope/teraslice#961]
Would be nice if we could factor out common terafoundation configuration into a separate file.  Some implementation ideas:

1. https://www.npmjs.com/package/config-directory

2. An extra cmd-line option to specify a common config file.

3. Have existing cmd-line option treat value as a glob pattern:

/tmp/multi-yaml/01-common.yaml
```yaml
phrases:
  yeee: boye
  hi: mom
```
/tmp/multi-yaml/02-specific.yaml
```yaml
phrases:
  yeee: BOYE!
extra:
  foo: bar
```

```javascript
> g = require('glob').glob('/tmp/multi-yaml/*.yaml')
> yaml = require('js-yaml')
> _ = require('lodash')
> _.reduce(_.map(_.map(g.found, (i) => fs.readFileSync(i)), yaml.load), _.merge)
{ phrases: { yeee: 'BOYE!', hi: 'mom' }, extra: { foo: 'bar' } }
```

**Comment by kstaken** [comment]
I think the real solution to this is to get the connector configs out of terafoundation so they can be more dynamic and managed independently.
