### ISSUE TITLE
Regex should allow // around the regex

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#971]
Everyone in the industry uses // to delimit regexes so end users are going to expect that's what is required here too. Anywhere that a regex is allowed should allow the regex to be specified inside slashes. 

For the regex attribute in particular both of these should be allowed and considered equivalent.

```
"regex":"key\"\:(.*),"
"regex":"/key\"\:(.*),/"
```

**Comment by jsnoble** [comment]
this was resolved in https://github.com/terascope/teraslice/pull/979
