### ISSUE TITLE
jobs restart only stops job

### ISSUE THREAD

**Issue by jeffmontagna** [terascope/teraslice#980]
Job will not start when using `earl jobs restart job_id` if the job has an api error/timeout during `stop`.

**Comment by kstaken** [comment]
Wasn't this resolved?

**Comment by jeffmontagna** [comment]
This is still an issue and to properly fix it I need to add mocked testing.

**Comment by godber** [comment]
@ciorg was this resolved in your `tjm`/`jobs` refactor work?

**Comment by jsnoble** [comment]
This has been resolved, and no longer an issue
