### ISSUE TITLE
Teraslice worker versions should report NA in k8s clustering

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#981]
In k8s mode, I think teraslice currently reports the master version as the `teraslice_version` for each worker node.  It should probably report `N/A`.  Perhaps each worker listed under `active` should report it's own stats.

```
    "10.6.6.6": {
        "node_id": "10.6.6.6",
        "hostname": "10.6.6.6",
        "pid": "N/A",
        "node_version": "v8.12.0",
        "teraslice_version": "0.44.4",
        "total": "N/A",
        "state": "connected",
        "available": "N/A",
        "active": [...
```

**Comment by godber** [comment]
Rather than reporting `NA`, it could report the worker's version (doing so would be ideal).  I am not sure what's involved in that, probably a lot of fiddly messaging that may not be worth the effort.  Unless it's stored in the deployment, oh, it probably is.

**Comment by peterdemartini** [comment]
I think the reason why we used `N/A` was not that it was difficult to get information but the "node" could potentially have many executions running on it, with different teraslice versions.

**Comment by godber** [comment]
Ok, for now, I am going to do this:

* Set `node_version` and `teraslice_version` to `N/A` at the worker/node level since it doesn't really have meaning in the k8s case (there's not node manager, a single node can run workers with versions that differ)
* Add an `image` property that reports the docker image used, including tag, which in our case provides version and build information.

I think this solution makes a decent compromise, maybe the `/txt` output should show `image` instead of `node_version` and `teraslice_version` in the k8s master case.  We haven't introduced any differences at the `/txt` api based on cluster type, but I'll see if doing so is convenient.

**Comment by godber** [comment]
`/txt/workers` will now read more usefully:

```
######  Workers  ######

assignment  job_id  ex_id  node_id    pod_name                           image
----------  ------  -----  ---------  ---------------------------------  ------------------
master      N/A     N/A    10.0.2.15  teraslice-master-794bdf85f6-dl49k  teraslice-k8sdev:1
```
