### ISSUE TITLE
Formalized Release Cycle Proposal

### ISSUE THREAD

**Issue by peterdemartini** [terascope/teraslice#983]
Our release cycle consists of many "feature" and "bug fix" releases that are often made once or twice a week. When the release is first made it is marked as a "prerelease" until it makes it through QA to our production environment which then marked as a "latest" release.

**IMPORTANT:** When I refer to a *release*, I am referring to a *Teraslice as a whole* release, not any individual package.

## The Problem

Getting a release into production can take a month, which means that we can have many releases that aren't stable or even tested. Which means we always go back to that "latest" release and we increase our chance of instability going to the forward.

## Proposed Solution

I propose we start planning our releases more and moving slower to match our release cycle. Instead of making  "feature" and "patch" releases as we develop, I propose creating a Github Milestones for each release. Each release would be a larger set of changes; additionally, each issue and PR would be attached to the milestone for each historical reference and for adding "unresolved" issues or regressions.

Ideally, we should only have two releases in-flight at a time, one release that is actively in QA and one that is in development/alpha stage.

Once a release considered "Ready for QA" we will create "release" branch for it, label the Github release as "prelease" and add "RC" to the title. If there are problems in QA we would patch that release until it makes into production at that point we mark it as "stable" and remove "prelease" and "RC". Any changes made to the release branch would have to coordinated with master as well.

Other projects that do this:

- [TypeScript](https://github.com/Microsoft/TypeScript)
- [VSCode](https://github.com/Microsoft/VSCode)
- [Yarn](https://github.com/yarnpkg/yarn)

**Comment by peterdemartini** [comment]
I am beginning to think, that maybe I am suggesting something like "monthly" releases vs semantic releases

**Comment by godber** [comment]
One benefit of lumping these together into Github milestones is it would be easier to tell what all has changed between releases.  Under the current model we have to read through a bunch of releases to get an idea what all changed.

**Comment by kstaken** [comment]
I think we have a much better process for this now.
