### ISSUE TITLE
Improve logging in k8s

### ISSUE THREAD

**Issue by godber** [terascope/teraslice#994]
In kubernetes clustering the logs are likely to be centralized and it would be useful to add more information to them.

* cluster name
* add `ex_id` and `job_id` in more places (they are probably only in a subset of the logs).

**Comment by godber** [comment]
What are the differences of `logger`s created like:

```
const { makeLogger, generateWorkerId } = require('../helpers/terafoundation');
...
const logger = makeLogger(context, executionContext, 'execution_controller');
```

and those created like:

```
const logger = context.apis.foundation.makeLogger({module: 'kubernetes_cluster_service'});
```

Or rather, which one is what we should be using?  Couldn't the one on the context use the helper?

**Comment by godber** [comment]
The helper is kind enough to add some teraslice/job related stuff

```
function makeLogger(context, executionContext, moduleName, extra = {}) {
    const {
        exId,
        jobId,
    } = executionContext;
    const {
        assignment,
        cluster,
    } = context;

    return context.apis.foundation.makeLogger(Object.assign({
        ex_id: exId,
        job_id: jobId,
        module: moduleName,
        worker_id: cluster.worker.id,
        assignment,
    }, extra));
}
```

**Comment by godber** [comment]
It's easy for me to tack `clusterName` on in the case of just the kuberenetes cluster master with this:

```
    const logger = context.apis.foundation.makeLogger({
        module: 'kubernetes_cluster_service',
        clusterName
    });
```

but I think the use of the logger in general is at least a little inconsistent throughout the code so there's no real great way to say ... ensure `exId` is set when it's in context.

I could even tack `clusterName` on with the helper, and that would get it in the cases we use the helper.

**Comment by peterdemartini** [comment]
In `v0.53` and `v0.54` I migrated all of the teraslice modules to create better logger instances, see: https://github.com/terascope/teraslice/blob/098e2464f8ddc9abc27f43a9d8ca50a9c6f4162d/packages/teraslice/lib/workers/helpers/terafoundation.js#L13-L41

I am going to close this unless you find any other issues.
